// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bob

import (
	"context"
	_ "embed"
	"io"
	"iter"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed system.bob.sql
var formattedQueries_system string

var getTimeZoneSQL = formattedQueries_system[149:232]

type GetTimeZoneQuery = orm.ModQuery[*dialect.SelectQuery, getTimeZone, *TimeZoneDB, TimeZoneDBSlice, bob.SliceTransformer[*TimeZoneDB, TimeZoneDBSlice]]

func GetTimeZone() *GetTimeZoneQuery {
	var expressionTypArgs getTimeZone

	return &GetTimeZoneQuery{
		Query: orm.Query[getTimeZone, *TimeZoneDB, TimeZoneDBSlice, bob.SliceTransformer[*TimeZoneDB, TimeZoneDBSlice]]{
			ExecQuery: orm.ExecQuery[getTimeZone]{
				BaseQuery: bob.BaseQuery[getTimeZone]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: scan.StructMapper[*TimeZoneDB](),
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 19))
			q.SetTable(expressionTypArgs.subExpr(25, 42))
			q.AppendWhere(expressionTypArgs.subExpr(49, 83))
		}),
	}
}

type getTimeZone struct{}

func (o getTimeZone) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
	}
}

func (o getTimeZone) raw(from, to int) string {
	return getTimeZoneSQL[from:to]
}

func (o getTimeZone) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(getTimeZoneSQL, from, to, o.args())
}

func (o getTimeZone) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(getTimeZoneSQL)).WriteSQL(ctx, w, d, start)
}

var assertTableIncludesColumnsSQL = formattedQueries_system[265:314]

type AssertTableIncludesColumnsQuery = orm.ModQuery[*dialect.SelectQuery, assertTableIncludesColumns, string, []string, assertTableIncludesColumnsTransformer]

func AssertTableIncludesColumns(ToCheckTable string, SourceTable string) *AssertTableIncludesColumnsQuery {
	var expressionTypArgs assertTableIncludesColumns

	expressionTypArgs.ToCheckTable = psql.Arg(ToCheckTable)
	expressionTypArgs.SourceTable = psql.Arg(SourceTable)

	return &AssertTableIncludesColumnsQuery{
		Query: orm.Query[assertTableIncludesColumns, string, []string, assertTableIncludesColumnsTransformer]{
			ExecQuery: orm.ExecQuery[assertTableIncludesColumns]{
				BaseQuery: bob.BaseQuery[assertTableIncludesColumns]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: scan.ColumnMapper[string]("fn_assert_table_includes_columns"),
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 49))
		}),
	}
}

type AssertTableIncludesColumnsRow = struct {
	FNAssertTableIncludesColumns string `db:"fn_assert_table_includes_columns"`
}

type assertTableIncludesColumnsTransformer = bob.SliceTransformer[string, []string]

type assertTableIncludesColumns struct {
	ToCheckTable bob.Expression
	SourceTable  bob.Expression
}

func (o assertTableIncludesColumns) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "toCheckTable",
			Start:      40,
			Stop:       42,
			Expression: o.ToCheckTable,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "sourceTable",
			Start:      45,
			Stop:       47,
			Expression: o.SourceTable,
		}) {
			return
		}
	}
}

func (o assertTableIncludesColumns) raw(from, to int) string {
	return assertTableIncludesColumnsSQL[from:to]
}

func (o assertTableIncludesColumns) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(assertTableIncludesColumnsSQL, from, to, o.args())
}

func (o assertTableIncludesColumns) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(assertTableIncludesColumnsSQL)).WriteSQL(ctx, w, d, start)
}
