// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	factoryVisitedCtx = newContextual[map[uintptr]struct{}]("factoryVisited")

	// Relationship Contexts for casbin_rules_v1
	casbinRulesV1WithParentsCascadingCtx = newContextual[bool]("casbinRulesV1WithParentsCascading")

	// Relationship Contexts for client
	clientWithParentsCascadingCtx = newContextual[bool]("clientWithParentsCascading")

	// Relationship Contexts for goose_version
	gooseVersionWithParentsCascadingCtx = newContextual[bool]("gooseVersionWithParentsCascading")

	// Relationship Contexts for mail
	mailWithParentsCascadingCtx = newContextual[bool]("mailWithParentsCascading")

	// Relationship Contexts for mail_domain
	mailDomainWithParentsCascadingCtx = newContextual[bool]("mailDomainWithParentsCascading")
	mailDomainRelDomainMailingsCtx    = newContextual[bool]("mail_domain.mailing.mailing.mailing_domain_id_fkey")

	// Relationship Contexts for mail_list
	mailListWithParentsCascadingCtx        = newContextual[bool]("mailListWithParentsCascading")
	mailListRelCreatedByUserUserProfileCtx = newContextual[bool]("mail_list.user_profile.mail_list.mail_list_created_by_user_id_fkey")
	mailListRelUpdatedByUserUserProfileCtx = newContextual[bool]("mail_list.user_profile.mail_list.mail_list_updated_by_user_id_fkey")
	mailListRelListMailListRecipientsCtx   = newContextual[bool]("mail_list.mail_list_recipient.mail_list_recipient.mail_list_recipient_list_id_fkey")
	mailListRelListMailingsCtx             = newContextual[bool]("mail_list.mailing.mailing.mailing_list_id_fkey")

	// Relationship Contexts for mail_list_recipient
	mailListRecipientWithParentsCascadingCtx  = newContextual[bool]("mailListRecipientWithParentsCascading")
	mailListRecipientRelLastMailingMailingCtx = newContextual[bool]("mail_list_recipient.mailing.mail_list_recipient.mail_list_recipient_last_mailing_id_fkey")
	mailListRecipientRelListMailListCtx       = newContextual[bool]("mail_list.mail_list_recipient.mail_list_recipient.mail_list_recipient_list_id_fkey")

	// Relationship Contexts for mail_template
	mailTemplateWithParentsCascadingCtx        = newContextual[bool]("mailTemplateWithParentsCascading")
	mailTemplateRelCreatedByUserUserProfileCtx = newContextual[bool]("mail_template.user_profile.mail_template.mail_template_created_by_user_id_fkey")
	mailTemplateRelUpdatedByUserUserProfileCtx = newContextual[bool]("mail_template.user_profile.mail_template.mail_template_updated_by_user_id_fkey")
	mailTemplateRelTemplateMailingsCtx         = newContextual[bool]("mail_template.mailing.mailing.mailing_template_id_fkey")

	// Relationship Contexts for mailing
	mailingWithParentsCascadingCtx             = newContextual[bool]("mailingWithParentsCascading")
	mailingRelLastMailingMailListRecipientsCtx = newContextual[bool]("mail_list_recipient.mailing.mail_list_recipient.mail_list_recipient_last_mailing_id_fkey")
	mailingRelCreatedByUserUserProfileCtx      = newContextual[bool]("mailing.user_profile.mailing.mailing_created_by_user_id_fkey")
	mailingRelDomainMailDomainCtx              = newContextual[bool]("mail_domain.mailing.mailing.mailing_domain_id_fkey")
	mailingRelListMailListCtx                  = newContextual[bool]("mail_list.mailing.mailing.mailing_list_id_fkey")
	mailingRelTemplateMailTemplateCtx          = newContextual[bool]("mail_template.mailing.mailing.mailing_template_id_fkey")
	mailingRelUpdatedByUserUserProfileCtx      = newContextual[bool]("mailing.user_profile.mailing.mailing_updated_by_user_id_fkey")

	// Relationship Contexts for token
	tokenWithParentsCascadingCtx = newContextual[bool]("tokenWithParentsCascading")
	tokenRelUserUserProfileCtx   = newContextual[bool]("token.user_profile.token.token_user_id_fkey")

	// Relationship Contexts for user_group
	userGroupWithParentsCascadingCtx = newContextual[bool]("userGroupWithParentsCascading")

	// Relationship Contexts for user_profile
	userProfileWithParentsCascadingCtx          = newContextual[bool]("userProfileWithParentsCascading")
	userProfileRelCreatedByUserMailListsCtx     = newContextual[bool]("mail_list.user_profile.mail_list.mail_list_created_by_user_id_fkey")
	userProfileRelUpdatedByUserMailListsCtx     = newContextual[bool]("mail_list.user_profile.mail_list.mail_list_updated_by_user_id_fkey")
	userProfileRelCreatedByUserMailTemplatesCtx = newContextual[bool]("mail_template.user_profile.mail_template.mail_template_created_by_user_id_fkey")
	userProfileRelUpdatedByUserMailTemplatesCtx = newContextual[bool]("mail_template.user_profile.mail_template.mail_template_updated_by_user_id_fkey")
	userProfileRelCreatedByUserMailingsCtx      = newContextual[bool]("mailing.user_profile.mailing.mailing_created_by_user_id_fkey")
	userProfileRelUpdatedByUserMailingsCtx      = newContextual[bool]("mailing.user_profile.mailing.mailing_updated_by_user_id_fkey")
	userProfileRelUserTokensCtx                 = newContextual[bool]("token.user_profile.token.token_user_id_fkey")

	modelsInCreationCtx = newContextual[map[string]any]("modelsInCreation")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
