// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
)

type ClientMod interface {
	Apply(context.Context, *ClientTemplate)
}

type ClientModFunc func(context.Context, *ClientTemplate)

func (f ClientModFunc) Apply(ctx context.Context, n *ClientTemplate) {
	f(ctx, n)
}

type ClientModSlice []ClientMod

func (mods ClientModSlice) Apply(ctx context.Context, n *ClientTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ClientTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ClientTemplate struct {
	ClientSeq       func() int64
	IP              func() string
	EquipID         func() string
	Browser         func() string
	OrderListEquips func() null.Val[pq.StringArray]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the ClientTemplate
func (o *ClientTemplate) Apply(ctx context.Context, mods ...ClientMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Client
// according to the relationships in the template. Nothing is inserted into the db
func (t ClientTemplate) setModelRels(o *models.Client) {}

// BuildSetter returns an *models.ClientSetter
// this does nothing with the relationship templates
func (o ClientTemplate) BuildSetter() *models.ClientSetter {
	m := &models.ClientSetter{}

	if o.ClientSeq != nil {
		val := o.ClientSeq()
		m.ClientSeq = omit.From(val)
	}
	if o.IP != nil {
		val := o.IP()
		m.IP = omit.From(val)
	}
	if o.EquipID != nil {
		val := o.EquipID()
		m.EquipID = omit.From(val)
	}
	if o.Browser != nil {
		val := o.Browser()
		m.Browser = omit.From(val)
	}
	if o.OrderListEquips != nil {
		val := o.OrderListEquips()
		m.OrderListEquips = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.ClientSetter
// this does nothing with the relationship templates
func (o ClientTemplate) BuildManySetter(number int) []*models.ClientSetter {
	m := make([]*models.ClientSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Client
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ClientTemplate.Create
func (o ClientTemplate) Build() *models.Client {
	m := &models.Client{}

	if o.ClientSeq != nil {
		m.ClientSeq = o.ClientSeq()
	}
	if o.IP != nil {
		m.IP = o.IP()
	}
	if o.EquipID != nil {
		m.EquipID = o.EquipID()
	}
	if o.Browser != nil {
		m.Browser = o.Browser()
	}
	if o.OrderListEquips != nil {
		m.OrderListEquips = o.OrderListEquips()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ClientSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ClientTemplate.CreateMany
func (o ClientTemplate) BuildMany(number int) models.ClientSlice {
	m := make(models.ClientSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableClient(m *models.ClientSetter) {
	if !(m.IP.IsValue()) {
		val := random_string(nil, "256")
		m.IP = omit.From(val)
	}
	if !(m.EquipID.IsValue()) {
		val := random_string(nil, "256")
		m.EquipID = omit.From(val)
	}
	if !(m.Browser.IsValue()) {
		val := random_string(nil)
		m.Browser = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Client
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ClientTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Client) error {
	var err error

	return err
}

// Create builds a client and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ClientTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Client, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableClient(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.Clients.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a client and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ClientTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Client {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a client and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ClientTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Client {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple clients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ClientTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ClientSlice, error) {
	var err error
	m := make(models.ClientSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple clients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ClientTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ClientSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple clients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ClientTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ClientSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Client has methods that act as mods for the ClientTemplate
var ClientMods clientMods

type clientMods struct{}

func (m clientMods) RandomizeAllColumns(f *faker.Faker) ClientMod {
	return ClientModSlice{
		ClientMods.RandomClientSeq(f),
		ClientMods.RandomIP(f),
		ClientMods.RandomEquipID(f),
		ClientMods.RandomBrowser(f),
		ClientMods.RandomOrderListEquips(f),
	}
}

// Set the model columns to this value
func (m clientMods) ClientSeq(val int64) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.ClientSeq = func() int64 { return val }
	})
}

// Set the Column from the function
func (m clientMods) ClientSeqFunc(f func() int64) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.ClientSeq = f
	})
}

// Clear any values for the column
func (m clientMods) UnsetClientSeq() ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.ClientSeq = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clientMods) RandomClientSeq(f *faker.Faker) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.ClientSeq = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m clientMods) IP(val string) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.IP = func() string { return val }
	})
}

// Set the Column from the function
func (m clientMods) IPFunc(f func() string) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.IP = f
	})
}

// Clear any values for the column
func (m clientMods) UnsetIP() ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.IP = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clientMods) RandomIP(f *faker.Faker) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.IP = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m clientMods) EquipID(val string) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.EquipID = func() string { return val }
	})
}

// Set the Column from the function
func (m clientMods) EquipIDFunc(f func() string) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.EquipID = f
	})
}

// Clear any values for the column
func (m clientMods) UnsetEquipID() ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.EquipID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clientMods) RandomEquipID(f *faker.Faker) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.EquipID = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m clientMods) Browser(val string) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.Browser = func() string { return val }
	})
}

// Set the Column from the function
func (m clientMods) BrowserFunc(f func() string) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.Browser = f
	})
}

// Clear any values for the column
func (m clientMods) UnsetBrowser() ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.Browser = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clientMods) RandomBrowser(f *faker.Faker) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.Browser = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m clientMods) OrderListEquips(val null.Val[pq.StringArray]) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.OrderListEquips = func() null.Val[pq.StringArray] { return val }
	})
}

// Set the Column from the function
func (m clientMods) OrderListEquipsFunc(f func() null.Val[pq.StringArray]) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.OrderListEquips = f
	})
}

// Clear any values for the column
func (m clientMods) UnsetOrderListEquips() ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.OrderListEquips = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m clientMods) RandomOrderListEquips(f *faker.Faker) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.OrderListEquips = func() null.Val[pq.StringArray] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_pq_StringArray(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m clientMods) RandomOrderListEquipsNotNull(f *faker.Faker) ClientMod {
	return ClientModFunc(func(_ context.Context, o *ClientTemplate) {
		o.OrderListEquips = func() null.Val[pq.StringArray] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_pq_StringArray(f)
			return null.From(val)
		}
	})
}

func (m clientMods) WithParentsCascading() ClientMod {
	return ClientModFunc(func(ctx context.Context, o *ClientTemplate) {
		if isDone, _ := clientWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = clientWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
