// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type GooseVersionMod interface {
	Apply(context.Context, *GooseVersionTemplate)
}

type GooseVersionModFunc func(context.Context, *GooseVersionTemplate)

func (f GooseVersionModFunc) Apply(ctx context.Context, n *GooseVersionTemplate) {
	f(ctx, n)
}

type GooseVersionModSlice []GooseVersionMod

func (mods GooseVersionModSlice) Apply(ctx context.Context, n *GooseVersionTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// GooseVersionTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type GooseVersionTemplate struct {
	ID        func() int32
	VersionID func() int64
	IsApplied func() bool
	Tstamp    func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the GooseVersionTemplate
func (o *GooseVersionTemplate) Apply(ctx context.Context, mods ...GooseVersionMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.GooseVersion
// according to the relationships in the template. Nothing is inserted into the db
func (t GooseVersionTemplate) setModelRels(o *models.GooseVersion) {}

// BuildSetter returns an *models.GooseVersionSetter
// this does nothing with the relationship templates
func (o GooseVersionTemplate) BuildSetter() *models.GooseVersionSetter {
	m := &models.GooseVersionSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.VersionID != nil {
		val := o.VersionID()
		m.VersionID = omit.From(val)
	}
	if o.IsApplied != nil {
		val := o.IsApplied()
		m.IsApplied = omit.From(val)
	}
	if o.Tstamp != nil {
		val := o.Tstamp()
		m.Tstamp = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.GooseVersionSetter
// this does nothing with the relationship templates
func (o GooseVersionTemplate) BuildManySetter(number int) []*models.GooseVersionSetter {
	m := make([]*models.GooseVersionSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.GooseVersion
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use GooseVersionTemplate.Create
func (o GooseVersionTemplate) Build() *models.GooseVersion {
	m := &models.GooseVersion{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.VersionID != nil {
		m.VersionID = o.VersionID()
	}
	if o.IsApplied != nil {
		m.IsApplied = o.IsApplied()
	}
	if o.Tstamp != nil {
		m.Tstamp = o.Tstamp()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.GooseVersionSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use GooseVersionTemplate.CreateMany
func (o GooseVersionTemplate) BuildMany(number int) models.GooseVersionSlice {
	m := make(models.GooseVersionSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableGooseVersion(m *models.GooseVersionSetter) {
	if !(m.VersionID.IsValue()) {
		val := random_int64(nil)
		m.VersionID = omit.From(val)
	}
	if !(m.IsApplied.IsValue()) {
		val := random_bool(nil)
		m.IsApplied = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.GooseVersion
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *GooseVersionTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.GooseVersion) error {
	var err error

	return err
}

// Create builds a gooseVersion and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *GooseVersionTemplate) Create(ctx context.Context, exec bob.Executor) (*models.GooseVersion, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableGooseVersion(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.GooseVersions.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a gooseVersion and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *GooseVersionTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.GooseVersion {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a gooseVersion and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *GooseVersionTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.GooseVersion {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple gooseVersions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o GooseVersionTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.GooseVersionSlice, error) {
	var err error
	m := make(models.GooseVersionSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple gooseVersions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o GooseVersionTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.GooseVersionSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple gooseVersions and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o GooseVersionTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.GooseVersionSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// GooseVersion has methods that act as mods for the GooseVersionTemplate
var GooseVersionMods gooseVersionMods

type gooseVersionMods struct{}

func (m gooseVersionMods) RandomizeAllColumns(f *faker.Faker) GooseVersionMod {
	return GooseVersionModSlice{
		GooseVersionMods.RandomID(f),
		GooseVersionMods.RandomVersionID(f),
		GooseVersionMods.RandomIsApplied(f),
		GooseVersionMods.RandomTstamp(f),
	}
}

// Set the model columns to this value
func (m gooseVersionMods) ID(val int32) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m gooseVersionMods) IDFunc(f func() int32) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m gooseVersionMods) UnsetID() GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m gooseVersionMods) RandomID(f *faker.Faker) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m gooseVersionMods) VersionID(val int64) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.VersionID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m gooseVersionMods) VersionIDFunc(f func() int64) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.VersionID = f
	})
}

// Clear any values for the column
func (m gooseVersionMods) UnsetVersionID() GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.VersionID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m gooseVersionMods) RandomVersionID(f *faker.Faker) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.VersionID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m gooseVersionMods) IsApplied(val bool) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.IsApplied = func() bool { return val }
	})
}

// Set the Column from the function
func (m gooseVersionMods) IsAppliedFunc(f func() bool) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.IsApplied = f
	})
}

// Clear any values for the column
func (m gooseVersionMods) UnsetIsApplied() GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.IsApplied = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m gooseVersionMods) RandomIsApplied(f *faker.Faker) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.IsApplied = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m gooseVersionMods) Tstamp(val time.Time) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.Tstamp = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m gooseVersionMods) TstampFunc(f func() time.Time) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.Tstamp = f
	})
}

// Clear any values for the column
func (m gooseVersionMods) UnsetTstamp() GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.Tstamp = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m gooseVersionMods) RandomTstamp(f *faker.Faker) GooseVersionMod {
	return GooseVersionModFunc(func(_ context.Context, o *GooseVersionTemplate) {
		o.Tstamp = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m gooseVersionMods) WithParentsCascading() GooseVersionMod {
	return GooseVersionModFunc(func(ctx context.Context, o *GooseVersionTemplate) {
		if isDone, _ := gooseVersionWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = gooseVersionWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
