// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type MailMod interface {
	Apply(context.Context, *MailTemplate)
}

type MailModFunc func(context.Context, *MailTemplate)

func (f MailModFunc) Apply(ctx context.Context, n *MailTemplate) {
	f(ctx, n)
}

type MailModSlice []MailMod

func (mods MailModSlice) Apply(ctx context.Context, n *MailTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MailTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MailTemplate struct {
	ID               func() int32
	MailFrom         func() string
	MailTo           func() string
	MailSubject      func() string
	MailBody         func() string
	ExternalStatus   func() null.Val[string]
	ExternalStatusID func() null.Val[string]
	InternalStatus   func() int64
	CreatedAt        func() time.Time
	UpdatedAt        func() null.Val[time.Time]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the MailTemplate
func (o *MailTemplate) Apply(ctx context.Context, mods ...MailMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Mail
// according to the relationships in the template. Nothing is inserted into the db
func (t MailTemplate) setModelRels(o *models.Mail) {}

// BuildSetter returns an *models.MailSetter
// this does nothing with the relationship templates
func (o MailTemplate) BuildSetter() *models.MailSetter {
	m := &models.MailSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.MailFrom != nil {
		val := o.MailFrom()
		m.MailFrom = omit.From(val)
	}
	if o.MailTo != nil {
		val := o.MailTo()
		m.MailTo = omit.From(val)
	}
	if o.MailSubject != nil {
		val := o.MailSubject()
		m.MailSubject = omit.From(val)
	}
	if o.MailBody != nil {
		val := o.MailBody()
		m.MailBody = omit.From(val)
	}
	if o.ExternalStatus != nil {
		val := o.ExternalStatus()
		m.ExternalStatus = omitnull.FromNull(val)
	}
	if o.ExternalStatusID != nil {
		val := o.ExternalStatusID()
		m.ExternalStatusID = omitnull.FromNull(val)
	}
	if o.InternalStatus != nil {
		val := o.InternalStatus()
		m.InternalStatus = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.MailSetter
// this does nothing with the relationship templates
func (o MailTemplate) BuildManySetter(number int) []*models.MailSetter {
	m := make([]*models.MailSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Mail
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailTemplate.Create
func (o MailTemplate) Build() *models.Mail {
	m := &models.Mail{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.MailFrom != nil {
		m.MailFrom = o.MailFrom()
	}
	if o.MailTo != nil {
		m.MailTo = o.MailTo()
	}
	if o.MailSubject != nil {
		m.MailSubject = o.MailSubject()
	}
	if o.MailBody != nil {
		m.MailBody = o.MailBody()
	}
	if o.ExternalStatus != nil {
		m.ExternalStatus = o.ExternalStatus()
	}
	if o.ExternalStatusID != nil {
		m.ExternalStatusID = o.ExternalStatusID()
	}
	if o.InternalStatus != nil {
		m.InternalStatus = o.InternalStatus()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MailSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailTemplate.CreateMany
func (o MailTemplate) BuildMany(number int) models.MailSlice {
	m := make(models.MailSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMail(m *models.MailSetter) {
	if !(m.MailFrom.IsValue()) {
		val := random_string(nil)
		m.MailFrom = omit.From(val)
	}
	if !(m.MailTo.IsValue()) {
		val := random_string(nil)
		m.MailTo = omit.From(val)
	}
	if !(m.MailSubject.IsValue()) {
		val := random_string(nil)
		m.MailSubject = omit.From(val)
	}
	if !(m.MailBody.IsValue()) {
		val := random_string(nil)
		m.MailBody = omit.From(val)
	}
	if !(m.InternalStatus.IsValue()) {
		val := random_int64(nil)
		m.InternalStatus = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Mail
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MailTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Mail) error {
	var err error

	return err
}

// Create builds a mail and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MailTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Mail, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMail(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.Mails.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a mail and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MailTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Mail {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a mail and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MailTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Mail {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple mails and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MailTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MailSlice, error) {
	var err error
	m := make(models.MailSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple mails and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MailTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MailSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple mails and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MailTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MailSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Mail has methods that act as mods for the MailTemplate
var MailMods mailMods

type mailMods struct{}

func (m mailMods) RandomizeAllColumns(f *faker.Faker) MailMod {
	return MailModSlice{
		MailMods.RandomID(f),
		MailMods.RandomMailFrom(f),
		MailMods.RandomMailTo(f),
		MailMods.RandomMailSubject(f),
		MailMods.RandomMailBody(f),
		MailMods.RandomExternalStatus(f),
		MailMods.RandomExternalStatusID(f),
		MailMods.RandomInternalStatus(f),
		MailMods.RandomCreatedAt(f),
		MailMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m mailMods) ID(val int32) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailMods) IDFunc(f func() int32) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetID() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailMods) RandomID(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailMods) MailFrom(val string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailFrom = func() string { return val }
	})
}

// Set the Column from the function
func (m mailMods) MailFromFunc(f func() string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailFrom = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetMailFrom() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailFrom = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailMods) RandomMailFrom(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailFrom = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m mailMods) MailTo(val string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailTo = func() string { return val }
	})
}

// Set the Column from the function
func (m mailMods) MailToFunc(f func() string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailTo = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetMailTo() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailTo = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailMods) RandomMailTo(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailTo = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m mailMods) MailSubject(val string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailSubject = func() string { return val }
	})
}

// Set the Column from the function
func (m mailMods) MailSubjectFunc(f func() string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailSubject = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetMailSubject() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailSubject = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailMods) RandomMailSubject(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailSubject = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m mailMods) MailBody(val string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailBody = func() string { return val }
	})
}

// Set the Column from the function
func (m mailMods) MailBodyFunc(f func() string) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailBody = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetMailBody() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailBody = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailMods) RandomMailBody(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.MailBody = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m mailMods) ExternalStatus(val null.Val[string]) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatus = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m mailMods) ExternalStatusFunc(f func() null.Val[string]) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatus = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetExternalStatus() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatus = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailMods) RandomExternalStatus(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatus = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailMods) RandomExternalStatusNotNull(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatus = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailMods) ExternalStatusID(val null.Val[string]) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatusID = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m mailMods) ExternalStatusIDFunc(f func() null.Val[string]) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatusID = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetExternalStatusID() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatusID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailMods) RandomExternalStatusID(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatusID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailMods) RandomExternalStatusIDNotNull(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.ExternalStatusID = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailMods) InternalStatus(val int64) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.InternalStatus = func() int64 { return val }
	})
}

// Set the Column from the function
func (m mailMods) InternalStatusFunc(f func() int64) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.InternalStatus = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetInternalStatus() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.InternalStatus = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailMods) RandomInternalStatus(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.InternalStatus = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m mailMods) CreatedAt(val time.Time) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m mailMods) CreatedAtFunc(f func() time.Time) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetCreatedAt() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailMods) RandomCreatedAt(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m mailMods) UpdatedAt(val null.Val[time.Time]) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailMods) UpdatedAtFunc(f func() null.Val[time.Time]) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m mailMods) UnsetUpdatedAt() MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailMods) RandomUpdatedAt(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailMods) RandomUpdatedAtNotNull(f *faker.Faker) MailMod {
	return MailModFunc(func(_ context.Context, o *MailTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m mailMods) WithParentsCascading() MailMod {
	return MailModFunc(func(ctx context.Context, o *MailTemplate) {
		if isDone, _ := mailWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = mailWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
