// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type MailListMod interface {
	Apply(context.Context, *MailListTemplate)
}

type MailListModFunc func(context.Context, *MailListTemplate)

func (f MailListModFunc) Apply(ctx context.Context, n *MailListTemplate) {
	f(ctx, n)
}

type MailListModSlice []MailListMod

func (mods MailListModSlice) Apply(ctx context.Context, n *MailListTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MailListTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MailListTemplate struct {
	ID              func() int32
	Name            func() string
	Description     func() string
	CreatedByUserID func() null.Val[int32]
	UpdatedByUserID func() null.Val[int32]
	CreatedAt       func() time.Time
	UpdatedAt       func() null.Val[time.Time]

	r mailListR
	f *Factory

	alreadyPersisted bool
}

type mailListR struct {
	CreatedByUserUserProfile *mailListRCreatedByUserUserProfileR
	UpdatedByUserUserProfile *mailListRUpdatedByUserUserProfileR
	ListMailListRecipients   []*mailListRListMailListRecipientsR
	ListMailings             []*mailListRListMailingsR
}

type mailListRCreatedByUserUserProfileR struct {
	o *UserProfileTemplate
}
type mailListRUpdatedByUserUserProfileR struct {
	o *UserProfileTemplate
}
type mailListRListMailListRecipientsR struct {
	number int
	o      *MailListRecipientTemplate
}
type mailListRListMailingsR struct {
	number int
	o      *MailingTemplate
}

// Apply mods to the MailListTemplate
func (o *MailListTemplate) Apply(ctx context.Context, mods ...MailListMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MailList
// according to the relationships in the template. Nothing is inserted into the db
func (t MailListTemplate) setModelRels(o *models.MailList) {
	if t.r.CreatedByUserUserProfile != nil {
		rel := t.r.CreatedByUserUserProfile.o.Build()
		o.CreatedByUserID = null.From(rel.ID) // h2
		o.R.CreatedByUserUserProfile = rel
		o.R.Loaded.CreatedByUserUserProfile = true
	}

	if t.r.UpdatedByUserUserProfile != nil {
		rel := t.r.UpdatedByUserUserProfile.o.Build()
		o.UpdatedByUserID = null.From(rel.ID) // h2
		o.R.UpdatedByUserUserProfile = rel
		o.R.Loaded.UpdatedByUserUserProfile = true
	}

	if t.r.ListMailListRecipients != nil {
		rel := models.MailListRecipientSlice{}
		for _, r := range t.r.ListMailListRecipients {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ListID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ListMailListRecipients = rel
		o.R.Loaded.ListMailListRecipients = true
	}

	if t.r.ListMailings != nil {
		rel := models.MailingSlice{}
		for _, r := range t.r.ListMailings {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ListID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ListMailings = rel
		o.R.Loaded.ListMailings = true
	}
}

// BuildSetter returns an *models.MailListSetter
// this does nothing with the relationship templates
func (o MailListTemplate) BuildSetter() *models.MailListSetter {
	m := &models.MailListSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omit.From(val)
	}
	if o.CreatedByUserID != nil {
		val := o.CreatedByUserID()
		m.CreatedByUserID = omitnull.FromNull(val)
	}
	if o.UpdatedByUserID != nil {
		val := o.UpdatedByUserID()
		m.UpdatedByUserID = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.MailListSetter
// this does nothing with the relationship templates
func (o MailListTemplate) BuildManySetter(number int) []*models.MailListSetter {
	m := make([]*models.MailListSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MailList
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailListTemplate.Create
func (o MailListTemplate) Build() *models.MailList {
	m := &models.MailList{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}
	if o.CreatedByUserID != nil {
		m.CreatedByUserID = o.CreatedByUserID()
	}
	if o.UpdatedByUserID != nil {
		m.UpdatedByUserID = o.UpdatedByUserID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MailListSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailListTemplate.CreateMany
func (o MailListTemplate) BuildMany(number int) models.MailListSlice {
	m := make(models.MailListSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMailList(m *models.MailListSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "256")
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MailList
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MailListTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MailList) error {
	var err error

	isCreatedByUserUserProfileDone, _ := mailListRelCreatedByUserUserProfileCtx.Value(ctx)
	if !isCreatedByUserUserProfileDone && o.r.CreatedByUserUserProfile != nil {
		ctx = mailListRelCreatedByUserUserProfileCtx.WithValue(ctx, true)
		if o.r.CreatedByUserUserProfile.o.alreadyPersisted {
			m.R.CreatedByUserUserProfile = o.r.CreatedByUserUserProfile.o.Build()
			m.R.Loaded.CreatedByUserUserProfile = true
		} else {
			var rel0 *models.UserProfile
			rel0, err = o.r.CreatedByUserUserProfile.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachCreatedByUserUserProfile(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	isUpdatedByUserUserProfileDone, _ := mailListRelUpdatedByUserUserProfileCtx.Value(ctx)
	if !isUpdatedByUserUserProfileDone && o.r.UpdatedByUserUserProfile != nil {
		ctx = mailListRelUpdatedByUserUserProfileCtx.WithValue(ctx, true)
		if o.r.UpdatedByUserUserProfile.o.alreadyPersisted {
			m.R.UpdatedByUserUserProfile = o.r.UpdatedByUserUserProfile.o.Build()
			m.R.Loaded.UpdatedByUserUserProfile = true
		} else {
			var rel1 *models.UserProfile
			rel1, err = o.r.UpdatedByUserUserProfile.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachUpdatedByUserUserProfile(ctx, exec, rel1)
			if err != nil {
				return err
			}
		}

	}

	isListMailListRecipientsDone, _ := mailListRelListMailListRecipientsCtx.Value(ctx)
	if !isListMailListRecipientsDone && o.r.ListMailListRecipients != nil {
		ctx = mailListRelListMailListRecipientsCtx.WithValue(ctx, true)
		for _, r := range o.r.ListMailListRecipients {
			if r.o.alreadyPersisted {
				m.R.ListMailListRecipients = append(m.R.ListMailListRecipients, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachListMailListRecipients(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isListMailingsDone, _ := mailListRelListMailingsCtx.Value(ctx)
	if !isListMailingsDone && o.r.ListMailings != nil {
		ctx = mailListRelListMailingsCtx.WithValue(ctx, true)
		for _, r := range o.r.ListMailings {
			if r.o.alreadyPersisted {
				m.R.ListMailings = append(m.R.ListMailings, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachListMailings(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a mailList and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MailListTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MailList, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMailList(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.MailLists.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["mail_list:mail_list_recipient:mail_list_recipient.mail_list_recipient_list_id_fkey"] = m
	newMInCreation["mail_list:mailing:mailing.mailing_list_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a mailList and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MailListTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MailList {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a mailList and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MailListTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MailList {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple mailLists and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MailListTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MailListSlice, error) {
	var err error
	m := make(models.MailListSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple mailLists and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MailListTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MailListSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple mailLists and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MailListTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MailListSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MailList has methods that act as mods for the MailListTemplate
var MailListMods mailListMods

type mailListMods struct{}

func (m mailListMods) RandomizeAllColumns(f *faker.Faker) MailListMod {
	return MailListModSlice{
		MailListMods.RandomID(f),
		MailListMods.RandomName(f),
		MailListMods.RandomDescription(f),
		MailListMods.RandomCreatedByUserID(f),
		MailListMods.RandomUpdatedByUserID(f),
		MailListMods.RandomCreatedAt(f),
		MailListMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m mailListMods) ID(val int32) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailListMods) IDFunc(f func() int32) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m mailListMods) UnsetID() MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListMods) RandomID(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailListMods) Name(val string) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListMods) NameFunc(f func() string) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m mailListMods) UnsetName() MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListMods) RandomName(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Name = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailListMods) Description(val string) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Description = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListMods) DescriptionFunc(f func() string) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m mailListMods) UnsetDescription() MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListMods) RandomDescription(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.Description = func() string {
			return random_string(f, "500")
		}
	})
}

// Set the model columns to this value
func (m mailListMods) CreatedByUserID(val null.Val[int32]) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedByUserID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m mailListMods) CreatedByUserIDFunc(f func() null.Val[int32]) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedByUserID = f
	})
}

// Clear any values for the column
func (m mailListMods) UnsetCreatedByUserID() MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedByUserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailListMods) RandomCreatedByUserID(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailListMods) RandomCreatedByUserIDNotNull(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailListMods) UpdatedByUserID(val null.Val[int32]) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedByUserID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m mailListMods) UpdatedByUserIDFunc(f func() null.Val[int32]) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedByUserID = f
	})
}

// Clear any values for the column
func (m mailListMods) UnsetUpdatedByUserID() MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedByUserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailListMods) RandomUpdatedByUserID(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailListMods) RandomUpdatedByUserIDNotNull(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailListMods) CreatedAt(val time.Time) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m mailListMods) CreatedAtFunc(f func() time.Time) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m mailListMods) UnsetCreatedAt() MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListMods) RandomCreatedAt(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m mailListMods) UpdatedAt(val null.Val[time.Time]) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailListMods) UpdatedAtFunc(f func() null.Val[time.Time]) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m mailListMods) UnsetUpdatedAt() MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailListMods) RandomUpdatedAt(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailListMods) RandomUpdatedAtNotNull(f *faker.Faker) MailListMod {
	return MailListModFunc(func(_ context.Context, o *MailListTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m mailListMods) WithParentsCascading() MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		if isDone, _ := mailListWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = mailListWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserProfileWithContext(ctx, UserProfileMods.WithParentsCascading())
			m.WithCreatedByUserUserProfile(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserProfileWithContext(ctx, UserProfileMods.WithParentsCascading())
			m.WithUpdatedByUserUserProfile(related).Apply(ctx, o)
		}
	})
}

func (m mailListMods) WithCreatedByUserUserProfile(rel *UserProfileTemplate) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.CreatedByUserUserProfile = &mailListRCreatedByUserUserProfileR{
			o: rel,
		}
	})
}

func (m mailListMods) WithNewCreatedByUserUserProfile(mods ...UserProfileMod) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		related := o.f.NewUserProfileWithContext(ctx, mods...)

		m.WithCreatedByUserUserProfile(related).Apply(ctx, o)
	})
}

func (m mailListMods) WithExistingCreatedByUserUserProfile(em *models.UserProfile) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.CreatedByUserUserProfile = &mailListRCreatedByUserUserProfileR{
			o: o.f.fromExistingUserProfile(ctx, em),
		}
	})
}

func (m mailListMods) WithoutCreatedByUserUserProfile() MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.CreatedByUserUserProfile = nil
	})
}

func (m mailListMods) WithUpdatedByUserUserProfile(rel *UserProfileTemplate) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.UpdatedByUserUserProfile = &mailListRUpdatedByUserUserProfileR{
			o: rel,
		}
	})
}

func (m mailListMods) WithNewUpdatedByUserUserProfile(mods ...UserProfileMod) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		related := o.f.NewUserProfileWithContext(ctx, mods...)

		m.WithUpdatedByUserUserProfile(related).Apply(ctx, o)
	})
}

func (m mailListMods) WithExistingUpdatedByUserUserProfile(em *models.UserProfile) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.UpdatedByUserUserProfile = &mailListRUpdatedByUserUserProfileR{
			o: o.f.fromExistingUserProfile(ctx, em),
		}
	})
}

func (m mailListMods) WithoutUpdatedByUserUserProfile() MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.UpdatedByUserUserProfile = nil
	})
}

func (m mailListMods) WithListMailListRecipients(number int, related *MailListRecipientTemplate) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.ListMailListRecipients = []*mailListRListMailListRecipientsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m mailListMods) WithNewListMailListRecipients(number int, mods ...MailListRecipientMod) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		related := o.f.NewMailListRecipientWithContext(ctx, mods...)
		m.WithListMailListRecipients(number, related).Apply(ctx, o)
	})
}

func (m mailListMods) AddListMailListRecipients(number int, related *MailListRecipientTemplate) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.ListMailListRecipients = append(o.r.ListMailListRecipients, &mailListRListMailListRecipientsR{
			number: number,
			o:      related,
		})
	})
}

func (m mailListMods) AddNewListMailListRecipients(number int, mods ...MailListRecipientMod) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		related := o.f.NewMailListRecipientWithContext(ctx, mods...)
		m.AddListMailListRecipients(number, related).Apply(ctx, o)
	})
}

func (m mailListMods) AddExistingListMailListRecipients(existingModels ...*models.MailListRecipient) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		for _, em := range existingModels {
			o.r.ListMailListRecipients = append(o.r.ListMailListRecipients, &mailListRListMailListRecipientsR{
				o: o.f.fromExistingMailListRecipient(ctx, em),
			})
		}
	})
}

func (m mailListMods) WithoutListMailListRecipients() MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.ListMailListRecipients = nil
	})
}

func (m mailListMods) WithListMailings(number int, related *MailingTemplate) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.ListMailings = []*mailListRListMailingsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m mailListMods) WithNewListMailings(number int, mods ...MailingMod) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.WithListMailings(number, related).Apply(ctx, o)
	})
}

func (m mailListMods) AddListMailings(number int, related *MailingTemplate) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.ListMailings = append(o.r.ListMailings, &mailListRListMailingsR{
			number: number,
			o:      related,
		})
	})
}

func (m mailListMods) AddNewListMailings(number int, mods ...MailingMod) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.AddListMailings(number, related).Apply(ctx, o)
	})
}

func (m mailListMods) AddExistingListMailings(existingModels ...*models.Mailing) MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		for _, em := range existingModels {
			o.r.ListMailings = append(o.r.ListMailings, &mailListRListMailingsR{
				o: o.f.fromExistingMailing(ctx, em),
			})
		}
	})
}

func (m mailListMods) WithoutListMailings() MailListMod {
	return MailListModFunc(func(ctx context.Context, o *MailListTemplate) {
		o.r.ListMailings = nil
	})
}
