// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type MailingMod interface {
	Apply(context.Context, *MailingTemplate)
}

type MailingModFunc func(context.Context, *MailingTemplate)

func (f MailingModFunc) Apply(ctx context.Context, n *MailingTemplate) {
	f(ctx, n)
}

type MailingModSlice []MailingMod

func (mods MailingModSlice) Apply(ctx context.Context, n *MailingTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MailingTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MailingTemplate struct {
	ID              func() int32
	Name            func() string
	TemplateID      func() int32
	ListID          func() int32
	DomainID        func() int32
	Status          func() string
	SubjectSnapshot func() string
	BodySnapshot    func() string
	SentCount       func() int32
	FailedCount     func() int32
	StartedAt       func() null.Val[time.Time]
	FinishedAt      func() null.Val[time.Time]
	CreatedByUserID func() null.Val[int32]
	UpdatedByUserID func() null.Val[int32]
	CreatedAt       func() time.Time
	UpdatedAt       func() null.Val[time.Time]

	r mailingR
	f *Factory

	alreadyPersisted bool
}

type mailingR struct {
	LastMailingMailListRecipients []*mailingRLastMailingMailListRecipientsR
	CreatedByUserUserProfile      *mailingRCreatedByUserUserProfileR
	DomainMailDomain              *mailingRDomainMailDomainR
	ListMailList                  *mailingRListMailListR
	TemplateMailTemplate          *mailingRTemplateMailTemplateR
	UpdatedByUserUserProfile      *mailingRUpdatedByUserUserProfileR
}

type mailingRLastMailingMailListRecipientsR struct {
	number int
	o      *MailListRecipientTemplate
}
type mailingRCreatedByUserUserProfileR struct {
	o *UserProfileTemplate
}
type mailingRDomainMailDomainR struct {
	o *MailDomainTemplate
}
type mailingRListMailListR struct {
	o *MailListTemplate
}
type mailingRTemplateMailTemplateR struct {
	o *MailTemplateTemplate
}
type mailingRUpdatedByUserUserProfileR struct {
	o *UserProfileTemplate
}

// Apply mods to the MailingTemplate
func (o *MailingTemplate) Apply(ctx context.Context, mods ...MailingMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Mailing
// according to the relationships in the template. Nothing is inserted into the db
func (t MailingTemplate) setModelRels(o *models.Mailing) {
	if t.r.LastMailingMailListRecipients != nil {
		rel := models.MailListRecipientSlice{}
		for _, r := range t.r.LastMailingMailListRecipients {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.LastMailingID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.LastMailingMailListRecipients = rel
		o.R.Loaded.LastMailingMailListRecipients = true
	}

	if t.r.CreatedByUserUserProfile != nil {
		rel := t.r.CreatedByUserUserProfile.o.Build()
		o.CreatedByUserID = null.From(rel.ID) // h2
		o.R.CreatedByUserUserProfile = rel
		o.R.Loaded.CreatedByUserUserProfile = true
	}

	if t.r.DomainMailDomain != nil {
		rel := t.r.DomainMailDomain.o.Build()
		o.DomainID = rel.ID // h2
		o.R.DomainMailDomain = rel
		o.R.Loaded.DomainMailDomain = true
	}

	if t.r.ListMailList != nil {
		rel := t.r.ListMailList.o.Build()
		o.ListID = rel.ID // h2
		o.R.ListMailList = rel
		o.R.Loaded.ListMailList = true
	}

	if t.r.TemplateMailTemplate != nil {
		rel := t.r.TemplateMailTemplate.o.Build()
		o.TemplateID = rel.ID // h2
		o.R.TemplateMailTemplate = rel
		o.R.Loaded.TemplateMailTemplate = true
	}

	if t.r.UpdatedByUserUserProfile != nil {
		rel := t.r.UpdatedByUserUserProfile.o.Build()
		o.UpdatedByUserID = null.From(rel.ID) // h2
		o.R.UpdatedByUserUserProfile = rel
		o.R.Loaded.UpdatedByUserUserProfile = true
	}
}

// BuildSetter returns an *models.MailingSetter
// this does nothing with the relationship templates
func (o MailingTemplate) BuildSetter() *models.MailingSetter {
	m := &models.MailingSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.TemplateID != nil {
		val := o.TemplateID()
		m.TemplateID = omit.From(val)
	}
	if o.ListID != nil {
		val := o.ListID()
		m.ListID = omit.From(val)
	}
	if o.DomainID != nil {
		val := o.DomainID()
		m.DomainID = omit.From(val)
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = omit.From(val)
	}
	if o.SubjectSnapshot != nil {
		val := o.SubjectSnapshot()
		m.SubjectSnapshot = omit.From(val)
	}
	if o.BodySnapshot != nil {
		val := o.BodySnapshot()
		m.BodySnapshot = omit.From(val)
	}
	if o.SentCount != nil {
		val := o.SentCount()
		m.SentCount = omit.From(val)
	}
	if o.FailedCount != nil {
		val := o.FailedCount()
		m.FailedCount = omit.From(val)
	}
	if o.StartedAt != nil {
		val := o.StartedAt()
		m.StartedAt = omitnull.FromNull(val)
	}
	if o.FinishedAt != nil {
		val := o.FinishedAt()
		m.FinishedAt = omitnull.FromNull(val)
	}
	if o.CreatedByUserID != nil {
		val := o.CreatedByUserID()
		m.CreatedByUserID = omitnull.FromNull(val)
	}
	if o.UpdatedByUserID != nil {
		val := o.UpdatedByUserID()
		m.UpdatedByUserID = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.MailingSetter
// this does nothing with the relationship templates
func (o MailingTemplate) BuildManySetter(number int) []*models.MailingSetter {
	m := make([]*models.MailingSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Mailing
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailingTemplate.Create
func (o MailingTemplate) Build() *models.Mailing {
	m := &models.Mailing{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.TemplateID != nil {
		m.TemplateID = o.TemplateID()
	}
	if o.ListID != nil {
		m.ListID = o.ListID()
	}
	if o.DomainID != nil {
		m.DomainID = o.DomainID()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.SubjectSnapshot != nil {
		m.SubjectSnapshot = o.SubjectSnapshot()
	}
	if o.BodySnapshot != nil {
		m.BodySnapshot = o.BodySnapshot()
	}
	if o.SentCount != nil {
		m.SentCount = o.SentCount()
	}
	if o.FailedCount != nil {
		m.FailedCount = o.FailedCount()
	}
	if o.StartedAt != nil {
		m.StartedAt = o.StartedAt()
	}
	if o.FinishedAt != nil {
		m.FinishedAt = o.FinishedAt()
	}
	if o.CreatedByUserID != nil {
		m.CreatedByUserID = o.CreatedByUserID()
	}
	if o.UpdatedByUserID != nil {
		m.UpdatedByUserID = o.UpdatedByUserID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MailingSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailingTemplate.CreateMany
func (o MailingTemplate) BuildMany(number int) models.MailingSlice {
	m := make(models.MailingSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMailing(m *models.MailingSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "256")
		m.Name = omit.From(val)
	}
	if !(m.TemplateID.IsValue()) {
		val := random_int32(nil)
		m.TemplateID = omit.From(val)
	}
	if !(m.ListID.IsValue()) {
		val := random_int32(nil)
		m.ListID = omit.From(val)
	}
	if !(m.DomainID.IsValue()) {
		val := random_int32(nil)
		m.DomainID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Mailing
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MailingTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Mailing) error {
	var err error

	isLastMailingMailListRecipientsDone, _ := mailingRelLastMailingMailListRecipientsCtx.Value(ctx)
	if !isLastMailingMailListRecipientsDone && o.r.LastMailingMailListRecipients != nil {
		ctx = mailingRelLastMailingMailListRecipientsCtx.WithValue(ctx, true)
		for _, r := range o.r.LastMailingMailListRecipients {
			if r.o.alreadyPersisted {
				m.R.LastMailingMailListRecipients = append(m.R.LastMailingMailListRecipients, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachLastMailingMailListRecipients(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isCreatedByUserUserProfileDone, _ := mailingRelCreatedByUserUserProfileCtx.Value(ctx)
	if !isCreatedByUserUserProfileDone && o.r.CreatedByUserUserProfile != nil {
		ctx = mailingRelCreatedByUserUserProfileCtx.WithValue(ctx, true)
		if o.r.CreatedByUserUserProfile.o.alreadyPersisted {
			m.R.CreatedByUserUserProfile = o.r.CreatedByUserUserProfile.o.Build()
			m.R.Loaded.CreatedByUserUserProfile = true
		} else {
			var rel1 *models.UserProfile
			rel1, err = o.r.CreatedByUserUserProfile.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachCreatedByUserUserProfile(ctx, exec, rel1)
			if err != nil {
				return err
			}
		}

	}

	isUpdatedByUserUserProfileDone, _ := mailingRelUpdatedByUserUserProfileCtx.Value(ctx)
	if !isUpdatedByUserUserProfileDone && o.r.UpdatedByUserUserProfile != nil {
		ctx = mailingRelUpdatedByUserUserProfileCtx.WithValue(ctx, true)
		if o.r.UpdatedByUserUserProfile.o.alreadyPersisted {
			m.R.UpdatedByUserUserProfile = o.r.UpdatedByUserUserProfile.o.Build()
			m.R.Loaded.UpdatedByUserUserProfile = true
		} else {
			var rel5 *models.UserProfile
			rel5, err = o.r.UpdatedByUserUserProfile.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachUpdatedByUserUserProfile(ctx, exec, rel5)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a mailing and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MailingTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Mailing, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMailing(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel2 *models.MailDomain

	if o.r.DomainMailDomain == nil {
		if parentModel, found := mInCreation["mail_domain:mailing:mailing.mailing_domain_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.MailDomain); ok {
				rel2 = pModel
			}
		}
	}

	if rel2 == nil {
		if o.r.DomainMailDomain == nil {
			MailingMods.WithNewDomainMailDomain().Apply(ctx, o)
		}

		if o.r.DomainMailDomain.o.alreadyPersisted {
			rel2 = o.r.DomainMailDomain.o.Build()
		} else {
			rel2, err = o.r.DomainMailDomain.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.DomainID = omit.From(rel2.ID)

	var rel3 *models.MailList

	if o.r.ListMailList == nil {
		if parentModel, found := mInCreation["mail_list:mailing:mailing.mailing_list_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.MailList); ok {
				rel3 = pModel
			}
		}
	}

	if rel3 == nil {
		if o.r.ListMailList == nil {
			MailingMods.WithNewListMailList().Apply(ctx, o)
		}

		if o.r.ListMailList.o.alreadyPersisted {
			rel3 = o.r.ListMailList.o.Build()
		} else {
			rel3, err = o.r.ListMailList.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.ListID = omit.From(rel3.ID)

	var rel4 *models.MailTemplate

	if o.r.TemplateMailTemplate == nil {
		if parentModel, found := mInCreation["mail_template:mailing:mailing.mailing_template_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.MailTemplate); ok {
				rel4 = pModel
			}
		}
	}

	if rel4 == nil {
		if o.r.TemplateMailTemplate == nil {
			MailingMods.WithNewTemplateMailTemplate().Apply(ctx, o)
		}

		if o.r.TemplateMailTemplate.o.alreadyPersisted {
			rel4 = o.r.TemplateMailTemplate.o.Build()
		} else {
			rel4, err = o.r.TemplateMailTemplate.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.TemplateID = omit.From(rel4.ID)

	m, err := models.Mailings.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["mailing:mail_list_recipient:mail_list_recipient.mail_list_recipient_last_mailing_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.DomainMailDomain = rel2
	m.R.Loaded.DomainMailDomain = true
	m.R.ListMailList = rel3
	m.R.Loaded.ListMailList = true
	m.R.TemplateMailTemplate = rel4
	m.R.Loaded.TemplateMailTemplate = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a mailing and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MailingTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Mailing {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a mailing and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MailingTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Mailing {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple mailings and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MailingTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MailingSlice, error) {
	var err error
	m := make(models.MailingSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple mailings and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MailingTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MailingSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple mailings and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MailingTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MailingSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Mailing has methods that act as mods for the MailingTemplate
var MailingMods mailingMods

type mailingMods struct{}

func (m mailingMods) RandomizeAllColumns(f *faker.Faker) MailingMod {
	return MailingModSlice{
		MailingMods.RandomID(f),
		MailingMods.RandomName(f),
		MailingMods.RandomTemplateID(f),
		MailingMods.RandomListID(f),
		MailingMods.RandomDomainID(f),
		MailingMods.RandomStatus(f),
		MailingMods.RandomSubjectSnapshot(f),
		MailingMods.RandomBodySnapshot(f),
		MailingMods.RandomSentCount(f),
		MailingMods.RandomFailedCount(f),
		MailingMods.RandomStartedAt(f),
		MailingMods.RandomFinishedAt(f),
		MailingMods.RandomCreatedByUserID(f),
		MailingMods.RandomUpdatedByUserID(f),
		MailingMods.RandomCreatedAt(f),
		MailingMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m mailingMods) ID(val int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailingMods) IDFunc(f func() int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetID() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomID(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) Name(val string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m mailingMods) NameFunc(f func() string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetName() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomName(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Name = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailingMods) TemplateID(val int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.TemplateID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailingMods) TemplateIDFunc(f func() int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.TemplateID = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetTemplateID() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.TemplateID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomTemplateID(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.TemplateID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) ListID(val int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ListID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailingMods) ListIDFunc(f func() int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ListID = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetListID() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ListID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomListID(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.ListID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) DomainID(val int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.DomainID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailingMods) DomainIDFunc(f func() int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.DomainID = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetDomainID() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.DomainID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomDomainID(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.DomainID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) Status(val string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m mailingMods) StatusFunc(f func() string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetStatus() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomStatus(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.Status = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m mailingMods) SubjectSnapshot(val string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SubjectSnapshot = func() string { return val }
	})
}

// Set the Column from the function
func (m mailingMods) SubjectSnapshotFunc(f func() string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SubjectSnapshot = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetSubjectSnapshot() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SubjectSnapshot = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomSubjectSnapshot(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SubjectSnapshot = func() string {
			return random_string(f, "500")
		}
	})
}

// Set the model columns to this value
func (m mailingMods) BodySnapshot(val string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.BodySnapshot = func() string { return val }
	})
}

// Set the Column from the function
func (m mailingMods) BodySnapshotFunc(f func() string) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.BodySnapshot = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetBodySnapshot() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.BodySnapshot = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomBodySnapshot(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.BodySnapshot = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) SentCount(val int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SentCount = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailingMods) SentCountFunc(f func() int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SentCount = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetSentCount() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SentCount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomSentCount(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.SentCount = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) FailedCount(val int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FailedCount = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailingMods) FailedCountFunc(f func() int32) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FailedCount = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetFailedCount() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FailedCount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomFailedCount(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FailedCount = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) StartedAt(val null.Val[time.Time]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.StartedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailingMods) StartedAtFunc(f func() null.Val[time.Time]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.StartedAt = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetStartedAt() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.StartedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailingMods) RandomStartedAt(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.StartedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailingMods) RandomStartedAtNotNull(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.StartedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) FinishedAt(val null.Val[time.Time]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FinishedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailingMods) FinishedAtFunc(f func() null.Val[time.Time]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FinishedAt = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetFinishedAt() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FinishedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailingMods) RandomFinishedAt(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FinishedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailingMods) RandomFinishedAtNotNull(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.FinishedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) CreatedByUserID(val null.Val[int32]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedByUserID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m mailingMods) CreatedByUserIDFunc(f func() null.Val[int32]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedByUserID = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetCreatedByUserID() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedByUserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailingMods) RandomCreatedByUserID(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailingMods) RandomCreatedByUserIDNotNull(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) UpdatedByUserID(val null.Val[int32]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedByUserID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m mailingMods) UpdatedByUserIDFunc(f func() null.Val[int32]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedByUserID = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetUpdatedByUserID() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedByUserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailingMods) RandomUpdatedByUserID(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailingMods) RandomUpdatedByUserIDNotNull(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) CreatedAt(val time.Time) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m mailingMods) CreatedAtFunc(f func() time.Time) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetCreatedAt() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailingMods) RandomCreatedAt(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m mailingMods) UpdatedAt(val null.Val[time.Time]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailingMods) UpdatedAtFunc(f func() null.Val[time.Time]) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m mailingMods) UnsetUpdatedAt() MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailingMods) RandomUpdatedAt(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailingMods) RandomUpdatedAtNotNull(f *faker.Faker) MailingMod {
	return MailingModFunc(func(_ context.Context, o *MailingTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m mailingMods) WithParentsCascading() MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		if isDone, _ := mailingWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = mailingWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserProfileWithContext(ctx, UserProfileMods.WithParentsCascading())
			m.WithCreatedByUserUserProfile(related).Apply(ctx, o)
		}
		{

			related := o.f.NewMailDomainWithContext(ctx, MailDomainMods.WithParentsCascading())
			m.WithDomainMailDomain(related).Apply(ctx, o)
		}
		{

			related := o.f.NewMailListWithContext(ctx, MailListMods.WithParentsCascading())
			m.WithListMailList(related).Apply(ctx, o)
		}
		{

			related := o.f.NewMailTemplateWithContext(ctx, MailTemplateMods.WithParentsCascading())
			m.WithTemplateMailTemplate(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserProfileWithContext(ctx, UserProfileMods.WithParentsCascading())
			m.WithUpdatedByUserUserProfile(related).Apply(ctx, o)
		}
	})
}

func (m mailingMods) WithCreatedByUserUserProfile(rel *UserProfileTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.CreatedByUserUserProfile = &mailingRCreatedByUserUserProfileR{
			o: rel,
		}
	})
}

func (m mailingMods) WithNewCreatedByUserUserProfile(mods ...UserProfileMod) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		related := o.f.NewUserProfileWithContext(ctx, mods...)

		m.WithCreatedByUserUserProfile(related).Apply(ctx, o)
	})
}

func (m mailingMods) WithExistingCreatedByUserUserProfile(em *models.UserProfile) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.CreatedByUserUserProfile = &mailingRCreatedByUserUserProfileR{
			o: o.f.fromExistingUserProfile(ctx, em),
		}
	})
}

func (m mailingMods) WithoutCreatedByUserUserProfile() MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.CreatedByUserUserProfile = nil
	})
}

func (m mailingMods) WithDomainMailDomain(rel *MailDomainTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.DomainMailDomain = &mailingRDomainMailDomainR{
			o: rel,
		}
	})
}

func (m mailingMods) WithNewDomainMailDomain(mods ...MailDomainMod) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		related := o.f.NewMailDomainWithContext(ctx, mods...)

		m.WithDomainMailDomain(related).Apply(ctx, o)
	})
}

func (m mailingMods) WithExistingDomainMailDomain(em *models.MailDomain) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.DomainMailDomain = &mailingRDomainMailDomainR{
			o: o.f.fromExistingMailDomain(ctx, em),
		}
	})
}

func (m mailingMods) WithoutDomainMailDomain() MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.DomainMailDomain = nil
	})
}

func (m mailingMods) WithListMailList(rel *MailListTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.ListMailList = &mailingRListMailListR{
			o: rel,
		}
	})
}

func (m mailingMods) WithNewListMailList(mods ...MailListMod) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		related := o.f.NewMailListWithContext(ctx, mods...)

		m.WithListMailList(related).Apply(ctx, o)
	})
}

func (m mailingMods) WithExistingListMailList(em *models.MailList) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.ListMailList = &mailingRListMailListR{
			o: o.f.fromExistingMailList(ctx, em),
		}
	})
}

func (m mailingMods) WithoutListMailList() MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.ListMailList = nil
	})
}

func (m mailingMods) WithTemplateMailTemplate(rel *MailTemplateTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.TemplateMailTemplate = &mailingRTemplateMailTemplateR{
			o: rel,
		}
	})
}

func (m mailingMods) WithNewTemplateMailTemplate(mods ...MailTemplateMod) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		related := o.f.NewMailTemplateWithContext(ctx, mods...)

		m.WithTemplateMailTemplate(related).Apply(ctx, o)
	})
}

func (m mailingMods) WithExistingTemplateMailTemplate(em *models.MailTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.TemplateMailTemplate = &mailingRTemplateMailTemplateR{
			o: o.f.fromExistingMailTemplate(ctx, em),
		}
	})
}

func (m mailingMods) WithoutTemplateMailTemplate() MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.TemplateMailTemplate = nil
	})
}

func (m mailingMods) WithUpdatedByUserUserProfile(rel *UserProfileTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.UpdatedByUserUserProfile = &mailingRUpdatedByUserUserProfileR{
			o: rel,
		}
	})
}

func (m mailingMods) WithNewUpdatedByUserUserProfile(mods ...UserProfileMod) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		related := o.f.NewUserProfileWithContext(ctx, mods...)

		m.WithUpdatedByUserUserProfile(related).Apply(ctx, o)
	})
}

func (m mailingMods) WithExistingUpdatedByUserUserProfile(em *models.UserProfile) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.UpdatedByUserUserProfile = &mailingRUpdatedByUserUserProfileR{
			o: o.f.fromExistingUserProfile(ctx, em),
		}
	})
}

func (m mailingMods) WithoutUpdatedByUserUserProfile() MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.UpdatedByUserUserProfile = nil
	})
}

func (m mailingMods) WithLastMailingMailListRecipients(number int, related *MailListRecipientTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.LastMailingMailListRecipients = []*mailingRLastMailingMailListRecipientsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m mailingMods) WithNewLastMailingMailListRecipients(number int, mods ...MailListRecipientMod) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		related := o.f.NewMailListRecipientWithContext(ctx, mods...)
		m.WithLastMailingMailListRecipients(number, related).Apply(ctx, o)
	})
}

func (m mailingMods) AddLastMailingMailListRecipients(number int, related *MailListRecipientTemplate) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.LastMailingMailListRecipients = append(o.r.LastMailingMailListRecipients, &mailingRLastMailingMailListRecipientsR{
			number: number,
			o:      related,
		})
	})
}

func (m mailingMods) AddNewLastMailingMailListRecipients(number int, mods ...MailListRecipientMod) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		related := o.f.NewMailListRecipientWithContext(ctx, mods...)
		m.AddLastMailingMailListRecipients(number, related).Apply(ctx, o)
	})
}

func (m mailingMods) AddExistingLastMailingMailListRecipients(existingModels ...*models.MailListRecipient) MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		for _, em := range existingModels {
			o.r.LastMailingMailListRecipients = append(o.r.LastMailingMailListRecipients, &mailingRLastMailingMailListRecipientsR{
				o: o.f.fromExistingMailListRecipient(ctx, em),
			})
		}
	})
}

func (m mailingMods) WithoutLastMailingMailListRecipients() MailingMod {
	return MailingModFunc(func(ctx context.Context, o *MailingTemplate) {
		o.r.LastMailingMailListRecipients = nil
	})
}
