// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type MailListRecipientMod interface {
	Apply(context.Context, *MailListRecipientTemplate)
}

type MailListRecipientModFunc func(context.Context, *MailListRecipientTemplate)

func (f MailListRecipientModFunc) Apply(ctx context.Context, n *MailListRecipientTemplate) {
	f(ctx, n)
}

type MailListRecipientModSlice []MailListRecipientMod

func (mods MailListRecipientModSlice) Apply(ctx context.Context, n *MailListRecipientTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MailListRecipientTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MailListRecipientTemplate struct {
	ID                    func() int32
	ListID                func() int32
	Email                 func() string
	Forename              func() string
	Lastname              func() string
	LastStatus            func() string
	LastPostmarkMessageID func() string
	LastError             func() string
	LastSentAt            func() null.Val[time.Time]
	LastMailingID         func() null.Val[int32]
	CreatedAt             func() time.Time

	r mailListRecipientR
	f *Factory

	alreadyPersisted bool
}

type mailListRecipientR struct {
	LastMailingMailing *mailListRecipientRLastMailingMailingR
	ListMailList       *mailListRecipientRListMailListR
}

type mailListRecipientRLastMailingMailingR struct {
	o *MailingTemplate
}
type mailListRecipientRListMailListR struct {
	o *MailListTemplate
}

// Apply mods to the MailListRecipientTemplate
func (o *MailListRecipientTemplate) Apply(ctx context.Context, mods ...MailListRecipientMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MailListRecipient
// according to the relationships in the template. Nothing is inserted into the db
func (t MailListRecipientTemplate) setModelRels(o *models.MailListRecipient) {
	if t.r.LastMailingMailing != nil {
		rel := t.r.LastMailingMailing.o.Build()
		o.LastMailingID = null.From(rel.ID) // h2
		o.R.LastMailingMailing = rel
		o.R.Loaded.LastMailingMailing = true
	}

	if t.r.ListMailList != nil {
		rel := t.r.ListMailList.o.Build()
		o.ListID = rel.ID // h2
		o.R.ListMailList = rel
		o.R.Loaded.ListMailList = true
	}
}

// BuildSetter returns an *models.MailListRecipientSetter
// this does nothing with the relationship templates
func (o MailListRecipientTemplate) BuildSetter() *models.MailListRecipientSetter {
	m := &models.MailListRecipientSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.ListID != nil {
		val := o.ListID()
		m.ListID = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Forename != nil {
		val := o.Forename()
		m.Forename = omit.From(val)
	}
	if o.Lastname != nil {
		val := o.Lastname()
		m.Lastname = omit.From(val)
	}
	if o.LastStatus != nil {
		val := o.LastStatus()
		m.LastStatus = omit.From(val)
	}
	if o.LastPostmarkMessageID != nil {
		val := o.LastPostmarkMessageID()
		m.LastPostmarkMessageID = omit.From(val)
	}
	if o.LastError != nil {
		val := o.LastError()
		m.LastError = omit.From(val)
	}
	if o.LastSentAt != nil {
		val := o.LastSentAt()
		m.LastSentAt = omitnull.FromNull(val)
	}
	if o.LastMailingID != nil {
		val := o.LastMailingID()
		m.LastMailingID = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.MailListRecipientSetter
// this does nothing with the relationship templates
func (o MailListRecipientTemplate) BuildManySetter(number int) []*models.MailListRecipientSetter {
	m := make([]*models.MailListRecipientSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MailListRecipient
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailListRecipientTemplate.Create
func (o MailListRecipientTemplate) Build() *models.MailListRecipient {
	m := &models.MailListRecipient{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ListID != nil {
		m.ListID = o.ListID()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Forename != nil {
		m.Forename = o.Forename()
	}
	if o.Lastname != nil {
		m.Lastname = o.Lastname()
	}
	if o.LastStatus != nil {
		m.LastStatus = o.LastStatus()
	}
	if o.LastPostmarkMessageID != nil {
		m.LastPostmarkMessageID = o.LastPostmarkMessageID()
	}
	if o.LastError != nil {
		m.LastError = o.LastError()
	}
	if o.LastSentAt != nil {
		m.LastSentAt = o.LastSentAt()
	}
	if o.LastMailingID != nil {
		m.LastMailingID = o.LastMailingID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MailListRecipientSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailListRecipientTemplate.CreateMany
func (o MailListRecipientTemplate) BuildMany(number int) models.MailListRecipientSlice {
	m := make(models.MailListRecipientSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMailListRecipient(m *models.MailListRecipientSetter) {
	if !(m.ListID.IsValue()) {
		val := random_int32(nil)
		m.ListID = omit.From(val)
	}
	if !(m.Email.IsValue()) {
		val := random_string(nil, "256")
		m.Email = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MailListRecipient
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MailListRecipientTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MailListRecipient) error {
	var err error

	isLastMailingMailingDone, _ := mailListRecipientRelLastMailingMailingCtx.Value(ctx)
	if !isLastMailingMailingDone && o.r.LastMailingMailing != nil {
		ctx = mailListRecipientRelLastMailingMailingCtx.WithValue(ctx, true)
		if o.r.LastMailingMailing.o.alreadyPersisted {
			m.R.LastMailingMailing = o.r.LastMailingMailing.o.Build()
			m.R.Loaded.LastMailingMailing = true
		} else {
			var rel0 *models.Mailing
			rel0, err = o.r.LastMailingMailing.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachLastMailingMailing(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a mailListRecipient and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MailListRecipientTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MailListRecipient, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMailListRecipient(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel1 *models.MailList

	if o.r.ListMailList == nil {
		if parentModel, found := mInCreation["mail_list:mail_list_recipient:mail_list_recipient.mail_list_recipient_list_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.MailList); ok {
				rel1 = pModel
			}
		}
	}

	if rel1 == nil {
		if o.r.ListMailList == nil {
			MailListRecipientMods.WithNewListMailList().Apply(ctx, o)
		}

		if o.r.ListMailList.o.alreadyPersisted {
			rel1 = o.r.ListMailList.o.Build()
		} else {
			rel1, err = o.r.ListMailList.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.ListID = omit.From(rel1.ID)

	m, err := models.MailListRecipients.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.ListMailList = rel1
	m.R.Loaded.ListMailList = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a mailListRecipient and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MailListRecipientTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MailListRecipient {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a mailListRecipient and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MailListRecipientTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MailListRecipient {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple mailListRecipients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MailListRecipientTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MailListRecipientSlice, error) {
	var err error
	m := make(models.MailListRecipientSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple mailListRecipients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MailListRecipientTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MailListRecipientSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple mailListRecipients and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MailListRecipientTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MailListRecipientSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MailListRecipient has methods that act as mods for the MailListRecipientTemplate
var MailListRecipientMods mailListRecipientMods

type mailListRecipientMods struct{}

func (m mailListRecipientMods) RandomizeAllColumns(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModSlice{
		MailListRecipientMods.RandomID(f),
		MailListRecipientMods.RandomListID(f),
		MailListRecipientMods.RandomEmail(f),
		MailListRecipientMods.RandomForename(f),
		MailListRecipientMods.RandomLastname(f),
		MailListRecipientMods.RandomLastStatus(f),
		MailListRecipientMods.RandomLastPostmarkMessageID(f),
		MailListRecipientMods.RandomLastError(f),
		MailListRecipientMods.RandomLastSentAt(f),
		MailListRecipientMods.RandomLastMailingID(f),
		MailListRecipientMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m mailListRecipientMods) ID(val int32) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) IDFunc(f func() int32) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetID() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomID(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) ListID(val int32) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ListID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) ListIDFunc(f func() int32) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ListID = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetListID() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ListID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomListID(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.ListID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) Email(val string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) EmailFunc(f func() string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetEmail() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomEmail(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Email = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) Forename(val string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Forename = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) ForenameFunc(f func() string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Forename = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetForename() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Forename = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomForename(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Forename = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) Lastname(val string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Lastname = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) LastnameFunc(f func() string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Lastname = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetLastname() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Lastname = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomLastname(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.Lastname = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) LastStatus(val string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastStatus = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) LastStatusFunc(f func() string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastStatus = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetLastStatus() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastStatus = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomLastStatus(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastStatus = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) LastPostmarkMessageID(val string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastPostmarkMessageID = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) LastPostmarkMessageIDFunc(f func() string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastPostmarkMessageID = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetLastPostmarkMessageID() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastPostmarkMessageID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomLastPostmarkMessageID(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastPostmarkMessageID = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) LastError(val string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastError = func() string { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) LastErrorFunc(f func() string) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastError = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetLastError() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastError = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomLastError(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastError = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) LastSentAt(val null.Val[time.Time]) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastSentAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) LastSentAtFunc(f func() null.Val[time.Time]) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastSentAt = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetLastSentAt() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastSentAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailListRecipientMods) RandomLastSentAt(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastSentAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailListRecipientMods) RandomLastSentAtNotNull(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastSentAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) LastMailingID(val null.Val[int32]) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastMailingID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) LastMailingIDFunc(f func() null.Val[int32]) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastMailingID = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetLastMailingID() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastMailingID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailListRecipientMods) RandomLastMailingID(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastMailingID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailListRecipientMods) RandomLastMailingIDNotNull(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.LastMailingID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m mailListRecipientMods) CreatedAt(val time.Time) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m mailListRecipientMods) CreatedAtFunc(f func() time.Time) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m mailListRecipientMods) UnsetCreatedAt() MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailListRecipientMods) RandomCreatedAt(f *faker.Faker) MailListRecipientMod {
	return MailListRecipientModFunc(func(_ context.Context, o *MailListRecipientTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m mailListRecipientMods) WithParentsCascading() MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		if isDone, _ := mailListRecipientWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = mailListRecipientWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewMailingWithContext(ctx, MailingMods.WithParentsCascading())
			m.WithLastMailingMailing(related).Apply(ctx, o)
		}
		{

			related := o.f.NewMailListWithContext(ctx, MailListMods.WithParentsCascading())
			m.WithListMailList(related).Apply(ctx, o)
		}
	})
}

func (m mailListRecipientMods) WithLastMailingMailing(rel *MailingTemplate) MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		o.r.LastMailingMailing = &mailListRecipientRLastMailingMailingR{
			o: rel,
		}
	})
}

func (m mailListRecipientMods) WithNewLastMailingMailing(mods ...MailingMod) MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)

		m.WithLastMailingMailing(related).Apply(ctx, o)
	})
}

func (m mailListRecipientMods) WithExistingLastMailingMailing(em *models.Mailing) MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		o.r.LastMailingMailing = &mailListRecipientRLastMailingMailingR{
			o: o.f.fromExistingMailing(ctx, em),
		}
	})
}

func (m mailListRecipientMods) WithoutLastMailingMailing() MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		o.r.LastMailingMailing = nil
	})
}

func (m mailListRecipientMods) WithListMailList(rel *MailListTemplate) MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		o.r.ListMailList = &mailListRecipientRListMailListR{
			o: rel,
		}
	})
}

func (m mailListRecipientMods) WithNewListMailList(mods ...MailListMod) MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		related := o.f.NewMailListWithContext(ctx, mods...)

		m.WithListMailList(related).Apply(ctx, o)
	})
}

func (m mailListRecipientMods) WithExistingListMailList(em *models.MailList) MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		o.r.ListMailList = &mailListRecipientRListMailListR{
			o: o.f.fromExistingMailList(ctx, em),
		}
	})
}

func (m mailListRecipientMods) WithoutListMailList() MailListRecipientMod {
	return MailListRecipientModFunc(func(ctx context.Context, o *MailListRecipientTemplate) {
		o.r.ListMailList = nil
	})
}
