// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type MailBlacklistMod interface {
	Apply(context.Context, *MailBlacklistTemplate)
}

type MailBlacklistModFunc func(context.Context, *MailBlacklistTemplate)

func (f MailBlacklistModFunc) Apply(ctx context.Context, n *MailBlacklistTemplate) {
	f(ctx, n)
}

type MailBlacklistModSlice []MailBlacklistMod

func (mods MailBlacklistModSlice) Apply(ctx context.Context, n *MailBlacklistTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MailBlacklistTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MailBlacklistTemplate struct {
	ID        func() int32
	Email     func() string
	Reason    func() string
	Origin    func() string
	Stream    func() string
	Source    func() string
	CreatedAt func() time.Time
	UpdatedAt func() null.Val[time.Time]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the MailBlacklistTemplate
func (o *MailBlacklistTemplate) Apply(ctx context.Context, mods ...MailBlacklistMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MailBlacklist
// according to the relationships in the template. Nothing is inserted into the db
func (t MailBlacklistTemplate) setModelRels(o *models.MailBlacklist) {}

// BuildSetter returns an *models.MailBlacklistSetter
// this does nothing with the relationship templates
func (o MailBlacklistTemplate) BuildSetter() *models.MailBlacklistSetter {
	m := &models.MailBlacklistSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Reason != nil {
		val := o.Reason()
		m.Reason = omit.From(val)
	}
	if o.Origin != nil {
		val := o.Origin()
		m.Origin = omit.From(val)
	}
	if o.Stream != nil {
		val := o.Stream()
		m.Stream = omit.From(val)
	}
	if o.Source != nil {
		val := o.Source()
		m.Source = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.MailBlacklistSetter
// this does nothing with the relationship templates
func (o MailBlacklistTemplate) BuildManySetter(number int) []*models.MailBlacklistSetter {
	m := make([]*models.MailBlacklistSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MailBlacklist
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailBlacklistTemplate.Create
func (o MailBlacklistTemplate) Build() *models.MailBlacklist {
	m := &models.MailBlacklist{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Reason != nil {
		m.Reason = o.Reason()
	}
	if o.Origin != nil {
		m.Origin = o.Origin()
	}
	if o.Stream != nil {
		m.Stream = o.Stream()
	}
	if o.Source != nil {
		m.Source = o.Source()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MailBlacklistSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailBlacklistTemplate.CreateMany
func (o MailBlacklistTemplate) BuildMany(number int) models.MailBlacklistSlice {
	m := make(models.MailBlacklistSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMailBlacklist(m *models.MailBlacklistSetter) {
	if !(m.Email.IsValue()) {
		val := random_string(nil, "256")
		m.Email = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MailBlacklist
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MailBlacklistTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MailBlacklist) error {
	var err error

	return err
}

// Create builds a mailBlacklist and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MailBlacklistTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MailBlacklist, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMailBlacklist(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.MailBlacklists.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a mailBlacklist and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MailBlacklistTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MailBlacklist {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a mailBlacklist and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MailBlacklistTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MailBlacklist {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple mailBlacklists and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MailBlacklistTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MailBlacklistSlice, error) {
	var err error
	m := make(models.MailBlacklistSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple mailBlacklists and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MailBlacklistTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MailBlacklistSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple mailBlacklists and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MailBlacklistTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MailBlacklistSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MailBlacklist has methods that act as mods for the MailBlacklistTemplate
var MailBlacklistMods mailBlacklistMods

type mailBlacklistMods struct{}

func (m mailBlacklistMods) RandomizeAllColumns(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModSlice{
		MailBlacklistMods.RandomID(f),
		MailBlacklistMods.RandomEmail(f),
		MailBlacklistMods.RandomReason(f),
		MailBlacklistMods.RandomOrigin(f),
		MailBlacklistMods.RandomStream(f),
		MailBlacklistMods.RandomSource(f),
		MailBlacklistMods.RandomCreatedAt(f),
		MailBlacklistMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m mailBlacklistMods) ID(val int32) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) IDFunc(f func() int32) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetID() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailBlacklistMods) RandomID(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailBlacklistMods) Email(val string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) EmailFunc(f func() string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetEmail() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailBlacklistMods) RandomEmail(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Email = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailBlacklistMods) Reason(val string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Reason = func() string { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) ReasonFunc(f func() string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Reason = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetReason() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Reason = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailBlacklistMods) RandomReason(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Reason = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m mailBlacklistMods) Origin(val string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Origin = func() string { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) OriginFunc(f func() string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Origin = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetOrigin() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Origin = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailBlacklistMods) RandomOrigin(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Origin = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m mailBlacklistMods) Stream(val string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Stream = func() string { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) StreamFunc(f func() string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Stream = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetStream() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Stream = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailBlacklistMods) RandomStream(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Stream = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailBlacklistMods) Source(val string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Source = func() string { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) SourceFunc(f func() string) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Source = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetSource() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Source = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailBlacklistMods) RandomSource(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.Source = func() string {
			return random_string(f, "16")
		}
	})
}

// Set the model columns to this value
func (m mailBlacklistMods) CreatedAt(val time.Time) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) CreatedAtFunc(f func() time.Time) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetCreatedAt() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailBlacklistMods) RandomCreatedAt(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m mailBlacklistMods) UpdatedAt(val null.Val[time.Time]) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailBlacklistMods) UpdatedAtFunc(f func() null.Val[time.Time]) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m mailBlacklistMods) UnsetUpdatedAt() MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailBlacklistMods) RandomUpdatedAt(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailBlacklistMods) RandomUpdatedAtNotNull(f *faker.Faker) MailBlacklistMod {
	return MailBlacklistModFunc(func(_ context.Context, o *MailBlacklistTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m mailBlacklistMods) WithParentsCascading() MailBlacklistMod {
	return MailBlacklistModFunc(func(ctx context.Context, o *MailBlacklistTemplate) {
		if isDone, _ := mailBlacklistWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = mailBlacklistWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
