// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type MailDomainMod interface {
	Apply(context.Context, *MailDomainTemplate)
}

type MailDomainModFunc func(context.Context, *MailDomainTemplate)

func (f MailDomainModFunc) Apply(ctx context.Context, n *MailDomainTemplate) {
	f(ctx, n)
}

type MailDomainModSlice []MailDomainMod

func (mods MailDomainModSlice) Apply(ctx context.Context, n *MailDomainTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// MailDomainTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MailDomainTemplate struct {
	ID               func() int32
	Domain           func() string
	FromEmail        func() string
	FromName         func() string
	PostmarkStreamID func() string
	IsActive         func() bool
	CreatedAt        func() time.Time
	UpdatedAt        func() null.Val[time.Time]

	r mailDomainR
	f *Factory

	alreadyPersisted bool
}

type mailDomainR struct {
	DomainMailings []*mailDomainRDomainMailingsR
}

type mailDomainRDomainMailingsR struct {
	number int
	o      *MailingTemplate
}

// Apply mods to the MailDomainTemplate
func (o *MailDomainTemplate) Apply(ctx context.Context, mods ...MailDomainMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.MailDomain
// according to the relationships in the template. Nothing is inserted into the db
func (t MailDomainTemplate) setModelRels(o *models.MailDomain) {
	if t.r.DomainMailings != nil {
		rel := models.MailingSlice{}
		for _, r := range t.r.DomainMailings {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DomainID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.DomainMailings = rel
		o.R.Loaded.DomainMailings = true
	}
}

// BuildSetter returns an *models.MailDomainSetter
// this does nothing with the relationship templates
func (o MailDomainTemplate) BuildSetter() *models.MailDomainSetter {
	m := &models.MailDomainSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Domain != nil {
		val := o.Domain()
		m.Domain = omit.From(val)
	}
	if o.FromEmail != nil {
		val := o.FromEmail()
		m.FromEmail = omit.From(val)
	}
	if o.FromName != nil {
		val := o.FromName()
		m.FromName = omit.From(val)
	}
	if o.PostmarkStreamID != nil {
		val := o.PostmarkStreamID()
		m.PostmarkStreamID = omit.From(val)
	}
	if o.IsActive != nil {
		val := o.IsActive()
		m.IsActive = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.MailDomainSetter
// this does nothing with the relationship templates
func (o MailDomainTemplate) BuildManySetter(number int) []*models.MailDomainSetter {
	m := make([]*models.MailDomainSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MailDomain
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailDomainTemplate.Create
func (o MailDomainTemplate) Build() *models.MailDomain {
	m := &models.MailDomain{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Domain != nil {
		m.Domain = o.Domain()
	}
	if o.FromEmail != nil {
		m.FromEmail = o.FromEmail()
	}
	if o.FromName != nil {
		m.FromName = o.FromName()
	}
	if o.PostmarkStreamID != nil {
		m.PostmarkStreamID = o.PostmarkStreamID()
	}
	if o.IsActive != nil {
		m.IsActive = o.IsActive()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MailDomainSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MailDomainTemplate.CreateMany
func (o MailDomainTemplate) BuildMany(number int) models.MailDomainSlice {
	m := make(models.MailDomainSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMailDomain(m *models.MailDomainSetter) {
	if !(m.Domain.IsValue()) {
		val := random_string(nil, "256")
		m.Domain = omit.From(val)
	}
	if !(m.FromEmail.IsValue()) {
		val := random_string(nil, "256")
		m.FromEmail = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MailDomain
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MailDomainTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MailDomain) error {
	var err error

	isDomainMailingsDone, _ := mailDomainRelDomainMailingsCtx.Value(ctx)
	if !isDomainMailingsDone && o.r.DomainMailings != nil {
		ctx = mailDomainRelDomainMailingsCtx.WithValue(ctx, true)
		for _, r := range o.r.DomainMailings {
			if r.o.alreadyPersisted {
				m.R.DomainMailings = append(m.R.DomainMailings, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachDomainMailings(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a mailDomain and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MailDomainTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MailDomain, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMailDomain(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.MailDomains.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["mail_domain:mailing:mailing.mailing_domain_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a mailDomain and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *MailDomainTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.MailDomain {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a mailDomain and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *MailDomainTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.MailDomain {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple mailDomains and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MailDomainTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MailDomainSlice, error) {
	var err error
	m := make(models.MailDomainSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple mailDomains and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o MailDomainTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.MailDomainSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple mailDomains and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o MailDomainTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.MailDomainSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// MailDomain has methods that act as mods for the MailDomainTemplate
var MailDomainMods mailDomainMods

type mailDomainMods struct{}

func (m mailDomainMods) RandomizeAllColumns(f *faker.Faker) MailDomainMod {
	return MailDomainModSlice{
		MailDomainMods.RandomID(f),
		MailDomainMods.RandomDomain(f),
		MailDomainMods.RandomFromEmail(f),
		MailDomainMods.RandomFromName(f),
		MailDomainMods.RandomPostmarkStreamID(f),
		MailDomainMods.RandomIsActive(f),
		MailDomainMods.RandomCreatedAt(f),
		MailDomainMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m mailDomainMods) ID(val int32) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) IDFunc(f func() int32) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetID() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailDomainMods) RandomID(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m mailDomainMods) Domain(val string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.Domain = func() string { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) DomainFunc(f func() string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.Domain = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetDomain() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.Domain = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailDomainMods) RandomDomain(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.Domain = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailDomainMods) FromEmail(val string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromEmail = func() string { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) FromEmailFunc(f func() string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromEmail = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetFromEmail() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromEmail = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailDomainMods) RandomFromEmail(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromEmail = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailDomainMods) FromName(val string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromName = func() string { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) FromNameFunc(f func() string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromName = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetFromName() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailDomainMods) RandomFromName(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.FromName = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailDomainMods) PostmarkStreamID(val string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.PostmarkStreamID = func() string { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) PostmarkStreamIDFunc(f func() string) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.PostmarkStreamID = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetPostmarkStreamID() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.PostmarkStreamID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailDomainMods) RandomPostmarkStreamID(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.PostmarkStreamID = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m mailDomainMods) IsActive(val bool) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.IsActive = func() bool { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) IsActiveFunc(f func() bool) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.IsActive = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetIsActive() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.IsActive = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailDomainMods) RandomIsActive(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.IsActive = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m mailDomainMods) CreatedAt(val time.Time) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) CreatedAtFunc(f func() time.Time) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetCreatedAt() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mailDomainMods) RandomCreatedAt(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m mailDomainMods) UpdatedAt(val null.Val[time.Time]) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m mailDomainMods) UpdatedAtFunc(f func() null.Val[time.Time]) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m mailDomainMods) UnsetUpdatedAt() MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m mailDomainMods) RandomUpdatedAt(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m mailDomainMods) RandomUpdatedAtNotNull(f *faker.Faker) MailDomainMod {
	return MailDomainModFunc(func(_ context.Context, o *MailDomainTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m mailDomainMods) WithParentsCascading() MailDomainMod {
	return MailDomainModFunc(func(ctx context.Context, o *MailDomainTemplate) {
		if isDone, _ := mailDomainWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = mailDomainWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m mailDomainMods) WithDomainMailings(number int, related *MailingTemplate) MailDomainMod {
	return MailDomainModFunc(func(ctx context.Context, o *MailDomainTemplate) {
		o.r.DomainMailings = []*mailDomainRDomainMailingsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m mailDomainMods) WithNewDomainMailings(number int, mods ...MailingMod) MailDomainMod {
	return MailDomainModFunc(func(ctx context.Context, o *MailDomainTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.WithDomainMailings(number, related).Apply(ctx, o)
	})
}

func (m mailDomainMods) AddDomainMailings(number int, related *MailingTemplate) MailDomainMod {
	return MailDomainModFunc(func(ctx context.Context, o *MailDomainTemplate) {
		o.r.DomainMailings = append(o.r.DomainMailings, &mailDomainRDomainMailingsR{
			number: number,
			o:      related,
		})
	})
}

func (m mailDomainMods) AddNewDomainMailings(number int, mods ...MailingMod) MailDomainMod {
	return MailDomainModFunc(func(ctx context.Context, o *MailDomainTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.AddDomainMailings(number, related).Apply(ctx, o)
	})
}

func (m mailDomainMods) AddExistingDomainMailings(existingModels ...*models.Mailing) MailDomainMod {
	return MailDomainModFunc(func(ctx context.Context, o *MailDomainTemplate) {
		for _, em := range existingModels {
			o.r.DomainMailings = append(o.r.DomainMailings, &mailDomainRDomainMailingsR{
				o: o.f.fromExistingMailing(ctx, em),
			})
		}
	})
}

func (m mailDomainMods) WithoutDomainMailings() MailDomainMod {
	return MailDomainModFunc(func(ctx context.Context, o *MailDomainTemplate) {
		o.r.DomainMailings = nil
	})
}
