// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "app/mq"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type UserProfileMod interface {
	Apply(context.Context, *UserProfileTemplate)
}

type UserProfileModFunc func(context.Context, *UserProfileTemplate)

func (f UserProfileModFunc) Apply(ctx context.Context, n *UserProfileTemplate) {
	f(ctx, n)
}

type UserProfileModSlice []UserProfileMod

func (mods UserProfileModSlice) Apply(ctx context.Context, n *UserProfileTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserProfileTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserProfileTemplate struct {
	ID                     func() int32
	Email                  func() string
	Salutation             func() string
	Forename               func() string
	Lastname               func() string
	Password               func() string
	MustResetPassword      func() bool
	LastLogin              func() null.Val[time.Time]
	CreatedByUserProfileID func() null.Val[int32]
	LastUpdatedByUserID    func() null.Val[int32]
	Disabled               func() bool
	EmailValidated         func() bool
	CreatedAt              func() time.Time
	UpdatedAt              func() null.Val[time.Time]

	r userProfileR
	f *Factory

	alreadyPersisted bool
}

type userProfileR struct {
	CreatedByUserMailLists     []*userProfileRCreatedByUserMailListsR
	UpdatedByUserMailLists     []*userProfileRUpdatedByUserMailListsR
	CreatedByUserMailTemplates []*userProfileRCreatedByUserMailTemplatesR
	UpdatedByUserMailTemplates []*userProfileRUpdatedByUserMailTemplatesR
	CreatedByUserMailings      []*userProfileRCreatedByUserMailingsR
	UpdatedByUserMailings      []*userProfileRUpdatedByUserMailingsR
	UserTokens                 []*userProfileRUserTokensR
}

type userProfileRCreatedByUserMailListsR struct {
	number int
	o      *MailListTemplate
}
type userProfileRUpdatedByUserMailListsR struct {
	number int
	o      *MailListTemplate
}
type userProfileRCreatedByUserMailTemplatesR struct {
	number int
	o      *MailTemplateTemplate
}
type userProfileRUpdatedByUserMailTemplatesR struct {
	number int
	o      *MailTemplateTemplate
}
type userProfileRCreatedByUserMailingsR struct {
	number int
	o      *MailingTemplate
}
type userProfileRUpdatedByUserMailingsR struct {
	number int
	o      *MailingTemplate
}
type userProfileRUserTokensR struct {
	number int
	o      *TokenTemplate
}

// Apply mods to the UserProfileTemplate
func (o *UserProfileTemplate) Apply(ctx context.Context, mods ...UserProfileMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.UserProfile
// according to the relationships in the template. Nothing is inserted into the db
func (t UserProfileTemplate) setModelRels(o *models.UserProfile) {
	if t.r.CreatedByUserMailLists != nil {
		rel := models.MailListSlice{}
		for _, r := range t.r.CreatedByUserMailLists {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CreatedByUserID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.CreatedByUserMailLists = rel
		o.R.Loaded.CreatedByUserMailLists = true
	}

	if t.r.UpdatedByUserMailLists != nil {
		rel := models.MailListSlice{}
		for _, r := range t.r.UpdatedByUserMailLists {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UpdatedByUserID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.UpdatedByUserMailLists = rel
		o.R.Loaded.UpdatedByUserMailLists = true
	}

	if t.r.CreatedByUserMailTemplates != nil {
		rel := models.MailTemplateSlice{}
		for _, r := range t.r.CreatedByUserMailTemplates {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CreatedByUserID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.CreatedByUserMailTemplates = rel
		o.R.Loaded.CreatedByUserMailTemplates = true
	}

	if t.r.UpdatedByUserMailTemplates != nil {
		rel := models.MailTemplateSlice{}
		for _, r := range t.r.UpdatedByUserMailTemplates {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UpdatedByUserID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.UpdatedByUserMailTemplates = rel
		o.R.Loaded.UpdatedByUserMailTemplates = true
	}

	if t.r.CreatedByUserMailings != nil {
		rel := models.MailingSlice{}
		for _, r := range t.r.CreatedByUserMailings {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CreatedByUserID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.CreatedByUserMailings = rel
		o.R.Loaded.CreatedByUserMailings = true
	}

	if t.r.UpdatedByUserMailings != nil {
		rel := models.MailingSlice{}
		for _, r := range t.r.UpdatedByUserMailings {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UpdatedByUserID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.UpdatedByUserMailings = rel
		o.R.Loaded.UpdatedByUserMailings = true
	}

	if t.r.UserTokens != nil {
		rel := models.TokenSlice{}
		for _, r := range t.r.UserTokens {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = null.From(o.ID) // h2
			}
			rel = append(rel, related...)
		}
		o.R.UserTokens = rel
		o.R.Loaded.UserTokens = true
	}
}

// BuildSetter returns an *models.UserProfileSetter
// this does nothing with the relationship templates
func (o UserProfileTemplate) BuildSetter() *models.UserProfileSetter {
	m := &models.UserProfileSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Salutation != nil {
		val := o.Salutation()
		m.Salutation = omit.From(val)
	}
	if o.Forename != nil {
		val := o.Forename()
		m.Forename = omit.From(val)
	}
	if o.Lastname != nil {
		val := o.Lastname()
		m.Lastname = omit.From(val)
	}
	if o.Password != nil {
		val := o.Password()
		m.Password = omit.From(val)
	}
	if o.MustResetPassword != nil {
		val := o.MustResetPassword()
		m.MustResetPassword = omit.From(val)
	}
	if o.LastLogin != nil {
		val := o.LastLogin()
		m.LastLogin = omitnull.FromNull(val)
	}
	if o.CreatedByUserProfileID != nil {
		val := o.CreatedByUserProfileID()
		m.CreatedByUserProfileID = omitnull.FromNull(val)
	}
	if o.LastUpdatedByUserID != nil {
		val := o.LastUpdatedByUserID()
		m.LastUpdatedByUserID = omitnull.FromNull(val)
	}
	if o.Disabled != nil {
		val := o.Disabled()
		m.Disabled = omit.From(val)
	}
	if o.EmailValidated != nil {
		val := o.EmailValidated()
		m.EmailValidated = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserProfileSetter
// this does nothing with the relationship templates
func (o UserProfileTemplate) BuildManySetter(number int) []*models.UserProfileSetter {
	m := make([]*models.UserProfileSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.UserProfile
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserProfileTemplate.Create
func (o UserProfileTemplate) Build() *models.UserProfile {
	m := &models.UserProfile{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Salutation != nil {
		m.Salutation = o.Salutation()
	}
	if o.Forename != nil {
		m.Forename = o.Forename()
	}
	if o.Lastname != nil {
		m.Lastname = o.Lastname()
	}
	if o.Password != nil {
		m.Password = o.Password()
	}
	if o.MustResetPassword != nil {
		m.MustResetPassword = o.MustResetPassword()
	}
	if o.LastLogin != nil {
		m.LastLogin = o.LastLogin()
	}
	if o.CreatedByUserProfileID != nil {
		m.CreatedByUserProfileID = o.CreatedByUserProfileID()
	}
	if o.LastUpdatedByUserID != nil {
		m.LastUpdatedByUserID = o.LastUpdatedByUserID()
	}
	if o.Disabled != nil {
		m.Disabled = o.Disabled()
	}
	if o.EmailValidated != nil {
		m.EmailValidated = o.EmailValidated()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserProfileSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserProfileTemplate.CreateMany
func (o UserProfileTemplate) BuildMany(number int) models.UserProfileSlice {
	m := make(models.UserProfileSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUserProfile(m *models.UserProfileSetter) {
	if !(m.Email.IsValue()) {
		val := random_string(nil, "256")
		m.Email = omit.From(val)
	}
	if !(m.Salutation.IsValue()) {
		val := random_string(nil, "256")
		m.Salutation = omit.From(val)
	}
	if !(m.Forename.IsValue()) {
		val := random_string(nil, "256")
		m.Forename = omit.From(val)
	}
	if !(m.Lastname.IsValue()) {
		val := random_string(nil, "256")
		m.Lastname = omit.From(val)
	}
	if !(m.Password.IsValue()) {
		val := random_string(nil)
		m.Password = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.UserProfile
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserProfileTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.UserProfile) error {
	var err error

	isCreatedByUserMailListsDone, _ := userProfileRelCreatedByUserMailListsCtx.Value(ctx)
	if !isCreatedByUserMailListsDone && o.r.CreatedByUserMailLists != nil {
		ctx = userProfileRelCreatedByUserMailListsCtx.WithValue(ctx, true)
		for _, r := range o.r.CreatedByUserMailLists {
			if r.o.alreadyPersisted {
				m.R.CreatedByUserMailLists = append(m.R.CreatedByUserMailLists, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCreatedByUserMailLists(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUpdatedByUserMailListsDone, _ := userProfileRelUpdatedByUserMailListsCtx.Value(ctx)
	if !isUpdatedByUserMailListsDone && o.r.UpdatedByUserMailLists != nil {
		ctx = userProfileRelUpdatedByUserMailListsCtx.WithValue(ctx, true)
		for _, r := range o.r.UpdatedByUserMailLists {
			if r.o.alreadyPersisted {
				m.R.UpdatedByUserMailLists = append(m.R.UpdatedByUserMailLists, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUpdatedByUserMailLists(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isCreatedByUserMailTemplatesDone, _ := userProfileRelCreatedByUserMailTemplatesCtx.Value(ctx)
	if !isCreatedByUserMailTemplatesDone && o.r.CreatedByUserMailTemplates != nil {
		ctx = userProfileRelCreatedByUserMailTemplatesCtx.WithValue(ctx, true)
		for _, r := range o.r.CreatedByUserMailTemplates {
			if r.o.alreadyPersisted {
				m.R.CreatedByUserMailTemplates = append(m.R.CreatedByUserMailTemplates, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCreatedByUserMailTemplates(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUpdatedByUserMailTemplatesDone, _ := userProfileRelUpdatedByUserMailTemplatesCtx.Value(ctx)
	if !isUpdatedByUserMailTemplatesDone && o.r.UpdatedByUserMailTemplates != nil {
		ctx = userProfileRelUpdatedByUserMailTemplatesCtx.WithValue(ctx, true)
		for _, r := range o.r.UpdatedByUserMailTemplates {
			if r.o.alreadyPersisted {
				m.R.UpdatedByUserMailTemplates = append(m.R.UpdatedByUserMailTemplates, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUpdatedByUserMailTemplates(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	isCreatedByUserMailingsDone, _ := userProfileRelCreatedByUserMailingsCtx.Value(ctx)
	if !isCreatedByUserMailingsDone && o.r.CreatedByUserMailings != nil {
		ctx = userProfileRelCreatedByUserMailingsCtx.WithValue(ctx, true)
		for _, r := range o.r.CreatedByUserMailings {
			if r.o.alreadyPersisted {
				m.R.CreatedByUserMailings = append(m.R.CreatedByUserMailings, r.o.Build())
			} else {
				rel4, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCreatedByUserMailings(ctx, exec, rel4...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUpdatedByUserMailingsDone, _ := userProfileRelUpdatedByUserMailingsCtx.Value(ctx)
	if !isUpdatedByUserMailingsDone && o.r.UpdatedByUserMailings != nil {
		ctx = userProfileRelUpdatedByUserMailingsCtx.WithValue(ctx, true)
		for _, r := range o.r.UpdatedByUserMailings {
			if r.o.alreadyPersisted {
				m.R.UpdatedByUserMailings = append(m.R.UpdatedByUserMailings, r.o.Build())
			} else {
				rel5, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUpdatedByUserMailings(ctx, exec, rel5...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUserTokensDone, _ := userProfileRelUserTokensCtx.Value(ctx)
	if !isUserTokensDone && o.r.UserTokens != nil {
		ctx = userProfileRelUserTokensCtx.WithValue(ctx, true)
		for _, r := range o.r.UserTokens {
			if r.o.alreadyPersisted {
				m.R.UserTokens = append(m.R.UserTokens, r.o.Build())
			} else {
				rel6, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUserTokens(ctx, exec, rel6...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a userProfile and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserProfileTemplate) Create(ctx context.Context, exec bob.Executor) (*models.UserProfile, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUserProfile(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.UserProfiles.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["user_profile:mail_list:mail_list.mail_list_created_by_user_id_fkey"] = m
	newMInCreation["user_profile:mail_list:mail_list.mail_list_updated_by_user_id_fkey"] = m
	newMInCreation["user_profile:mail_template:mail_template.mail_template_created_by_user_id_fkey"] = m
	newMInCreation["user_profile:mail_template:mail_template.mail_template_updated_by_user_id_fkey"] = m
	newMInCreation["user_profile:mailing:mailing.mailing_created_by_user_id_fkey"] = m
	newMInCreation["user_profile:mailing:mailing.mailing_updated_by_user_id_fkey"] = m
	newMInCreation["user_profile:token:token.token_user_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a userProfile and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserProfileTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.UserProfile {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a userProfile and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserProfileTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.UserProfile {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple userProfiles and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserProfileTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserProfileSlice, error) {
	var err error
	m := make(models.UserProfileSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple userProfiles and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserProfileTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserProfileSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple userProfiles and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserProfileTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserProfileSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// UserProfile has methods that act as mods for the UserProfileTemplate
var UserProfileMods userProfileMods

type userProfileMods struct{}

func (m userProfileMods) RandomizeAllColumns(f *faker.Faker) UserProfileMod {
	return UserProfileModSlice{
		UserProfileMods.RandomID(f),
		UserProfileMods.RandomEmail(f),
		UserProfileMods.RandomSalutation(f),
		UserProfileMods.RandomForename(f),
		UserProfileMods.RandomLastname(f),
		UserProfileMods.RandomPassword(f),
		UserProfileMods.RandomMustResetPassword(f),
		UserProfileMods.RandomLastLogin(f),
		UserProfileMods.RandomCreatedByUserProfileID(f),
		UserProfileMods.RandomLastUpdatedByUserID(f),
		UserProfileMods.RandomDisabled(f),
		UserProfileMods.RandomEmailValidated(f),
		UserProfileMods.RandomCreatedAt(f),
		UserProfileMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m userProfileMods) ID(val int32) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) IDFunc(f func() int32) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetID() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomID(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) Email(val string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) EmailFunc(f func() string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetEmail() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomEmail(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Email = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) Salutation(val string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Salutation = func() string { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) SalutationFunc(f func() string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Salutation = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetSalutation() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Salutation = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomSalutation(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Salutation = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) Forename(val string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Forename = func() string { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) ForenameFunc(f func() string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Forename = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetForename() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Forename = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomForename(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Forename = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) Lastname(val string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Lastname = func() string { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) LastnameFunc(f func() string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Lastname = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetLastname() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Lastname = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomLastname(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Lastname = func() string {
			return random_string(f, "256")
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) Password(val string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Password = func() string { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) PasswordFunc(f func() string) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Password = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetPassword() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Password = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomPassword(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Password = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) MustResetPassword(val bool) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.MustResetPassword = func() bool { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) MustResetPasswordFunc(f func() bool) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.MustResetPassword = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetMustResetPassword() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.MustResetPassword = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomMustResetPassword(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.MustResetPassword = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) LastLogin(val null.Val[time.Time]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastLogin = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) LastLoginFunc(f func() null.Val[time.Time]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastLogin = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetLastLogin() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastLogin = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userProfileMods) RandomLastLogin(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastLogin = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userProfileMods) RandomLastLoginNotNull(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastLogin = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) CreatedByUserProfileID(val null.Val[int32]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedByUserProfileID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) CreatedByUserProfileIDFunc(f func() null.Val[int32]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedByUserProfileID = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetCreatedByUserProfileID() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedByUserProfileID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userProfileMods) RandomCreatedByUserProfileID(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedByUserProfileID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userProfileMods) RandomCreatedByUserProfileIDNotNull(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedByUserProfileID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) LastUpdatedByUserID(val null.Val[int32]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastUpdatedByUserID = func() null.Val[int32] { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) LastUpdatedByUserIDFunc(f func() null.Val[int32]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastUpdatedByUserID = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetLastUpdatedByUserID() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastUpdatedByUserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userProfileMods) RandomLastUpdatedByUserID(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastUpdatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userProfileMods) RandomLastUpdatedByUserIDNotNull(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.LastUpdatedByUserID = func() null.Val[int32] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int32(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) Disabled(val bool) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Disabled = func() bool { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) DisabledFunc(f func() bool) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Disabled = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetDisabled() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Disabled = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomDisabled(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.Disabled = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) EmailValidated(val bool) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.EmailValidated = func() bool { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) EmailValidatedFunc(f func() bool) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.EmailValidated = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetEmailValidated() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.EmailValidated = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomEmailValidated(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.EmailValidated = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) CreatedAt(val time.Time) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) CreatedAtFunc(f func() time.Time) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetCreatedAt() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userProfileMods) RandomCreatedAt(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userProfileMods) UpdatedAt(val null.Val[time.Time]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m userProfileMods) UpdatedAtFunc(f func() null.Val[time.Time]) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m userProfileMods) UnsetUpdatedAt() UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m userProfileMods) RandomUpdatedAt(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m userProfileMods) RandomUpdatedAtNotNull(f *faker.Faker) UserProfileMod {
	return UserProfileModFunc(func(_ context.Context, o *UserProfileTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m userProfileMods) WithParentsCascading() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		if isDone, _ := userProfileWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userProfileWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m userProfileMods) WithCreatedByUserMailLists(number int, related *MailListTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailLists = []*userProfileRCreatedByUserMailListsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userProfileMods) WithNewCreatedByUserMailLists(number int, mods ...MailListMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailListWithContext(ctx, mods...)
		m.WithCreatedByUserMailLists(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddCreatedByUserMailLists(number int, related *MailListTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailLists = append(o.r.CreatedByUserMailLists, &userProfileRCreatedByUserMailListsR{
			number: number,
			o:      related,
		})
	})
}

func (m userProfileMods) AddNewCreatedByUserMailLists(number int, mods ...MailListMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailListWithContext(ctx, mods...)
		m.AddCreatedByUserMailLists(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddExistingCreatedByUserMailLists(existingModels ...*models.MailList) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		for _, em := range existingModels {
			o.r.CreatedByUserMailLists = append(o.r.CreatedByUserMailLists, &userProfileRCreatedByUserMailListsR{
				o: o.f.fromExistingMailList(ctx, em),
			})
		}
	})
}

func (m userProfileMods) WithoutCreatedByUserMailLists() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailLists = nil
	})
}

func (m userProfileMods) WithUpdatedByUserMailLists(number int, related *MailListTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailLists = []*userProfileRUpdatedByUserMailListsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userProfileMods) WithNewUpdatedByUserMailLists(number int, mods ...MailListMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailListWithContext(ctx, mods...)
		m.WithUpdatedByUserMailLists(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddUpdatedByUserMailLists(number int, related *MailListTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailLists = append(o.r.UpdatedByUserMailLists, &userProfileRUpdatedByUserMailListsR{
			number: number,
			o:      related,
		})
	})
}

func (m userProfileMods) AddNewUpdatedByUserMailLists(number int, mods ...MailListMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailListWithContext(ctx, mods...)
		m.AddUpdatedByUserMailLists(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddExistingUpdatedByUserMailLists(existingModels ...*models.MailList) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		for _, em := range existingModels {
			o.r.UpdatedByUserMailLists = append(o.r.UpdatedByUserMailLists, &userProfileRUpdatedByUserMailListsR{
				o: o.f.fromExistingMailList(ctx, em),
			})
		}
	})
}

func (m userProfileMods) WithoutUpdatedByUserMailLists() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailLists = nil
	})
}

func (m userProfileMods) WithCreatedByUserMailTemplates(number int, related *MailTemplateTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailTemplates = []*userProfileRCreatedByUserMailTemplatesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userProfileMods) WithNewCreatedByUserMailTemplates(number int, mods ...MailTemplateMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailTemplateWithContext(ctx, mods...)
		m.WithCreatedByUserMailTemplates(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddCreatedByUserMailTemplates(number int, related *MailTemplateTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailTemplates = append(o.r.CreatedByUserMailTemplates, &userProfileRCreatedByUserMailTemplatesR{
			number: number,
			o:      related,
		})
	})
}

func (m userProfileMods) AddNewCreatedByUserMailTemplates(number int, mods ...MailTemplateMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailTemplateWithContext(ctx, mods...)
		m.AddCreatedByUserMailTemplates(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddExistingCreatedByUserMailTemplates(existingModels ...*models.MailTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		for _, em := range existingModels {
			o.r.CreatedByUserMailTemplates = append(o.r.CreatedByUserMailTemplates, &userProfileRCreatedByUserMailTemplatesR{
				o: o.f.fromExistingMailTemplate(ctx, em),
			})
		}
	})
}

func (m userProfileMods) WithoutCreatedByUserMailTemplates() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailTemplates = nil
	})
}

func (m userProfileMods) WithUpdatedByUserMailTemplates(number int, related *MailTemplateTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailTemplates = []*userProfileRUpdatedByUserMailTemplatesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userProfileMods) WithNewUpdatedByUserMailTemplates(number int, mods ...MailTemplateMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailTemplateWithContext(ctx, mods...)
		m.WithUpdatedByUserMailTemplates(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddUpdatedByUserMailTemplates(number int, related *MailTemplateTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailTemplates = append(o.r.UpdatedByUserMailTemplates, &userProfileRUpdatedByUserMailTemplatesR{
			number: number,
			o:      related,
		})
	})
}

func (m userProfileMods) AddNewUpdatedByUserMailTemplates(number int, mods ...MailTemplateMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailTemplateWithContext(ctx, mods...)
		m.AddUpdatedByUserMailTemplates(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddExistingUpdatedByUserMailTemplates(existingModels ...*models.MailTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		for _, em := range existingModels {
			o.r.UpdatedByUserMailTemplates = append(o.r.UpdatedByUserMailTemplates, &userProfileRUpdatedByUserMailTemplatesR{
				o: o.f.fromExistingMailTemplate(ctx, em),
			})
		}
	})
}

func (m userProfileMods) WithoutUpdatedByUserMailTemplates() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailTemplates = nil
	})
}

func (m userProfileMods) WithCreatedByUserMailings(number int, related *MailingTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailings = []*userProfileRCreatedByUserMailingsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userProfileMods) WithNewCreatedByUserMailings(number int, mods ...MailingMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.WithCreatedByUserMailings(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddCreatedByUserMailings(number int, related *MailingTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailings = append(o.r.CreatedByUserMailings, &userProfileRCreatedByUserMailingsR{
			number: number,
			o:      related,
		})
	})
}

func (m userProfileMods) AddNewCreatedByUserMailings(number int, mods ...MailingMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.AddCreatedByUserMailings(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddExistingCreatedByUserMailings(existingModels ...*models.Mailing) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		for _, em := range existingModels {
			o.r.CreatedByUserMailings = append(o.r.CreatedByUserMailings, &userProfileRCreatedByUserMailingsR{
				o: o.f.fromExistingMailing(ctx, em),
			})
		}
	})
}

func (m userProfileMods) WithoutCreatedByUserMailings() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.CreatedByUserMailings = nil
	})
}

func (m userProfileMods) WithUpdatedByUserMailings(number int, related *MailingTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailings = []*userProfileRUpdatedByUserMailingsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userProfileMods) WithNewUpdatedByUserMailings(number int, mods ...MailingMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.WithUpdatedByUserMailings(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddUpdatedByUserMailings(number int, related *MailingTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailings = append(o.r.UpdatedByUserMailings, &userProfileRUpdatedByUserMailingsR{
			number: number,
			o:      related,
		})
	})
}

func (m userProfileMods) AddNewUpdatedByUserMailings(number int, mods ...MailingMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewMailingWithContext(ctx, mods...)
		m.AddUpdatedByUserMailings(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddExistingUpdatedByUserMailings(existingModels ...*models.Mailing) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		for _, em := range existingModels {
			o.r.UpdatedByUserMailings = append(o.r.UpdatedByUserMailings, &userProfileRUpdatedByUserMailingsR{
				o: o.f.fromExistingMailing(ctx, em),
			})
		}
	})
}

func (m userProfileMods) WithoutUpdatedByUserMailings() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UpdatedByUserMailings = nil
	})
}

func (m userProfileMods) WithUserTokens(number int, related *TokenTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UserTokens = []*userProfileRUserTokensR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userProfileMods) WithNewUserTokens(number int, mods ...TokenMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewTokenWithContext(ctx, mods...)
		m.WithUserTokens(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddUserTokens(number int, related *TokenTemplate) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UserTokens = append(o.r.UserTokens, &userProfileRUserTokensR{
			number: number,
			o:      related,
		})
	})
}

func (m userProfileMods) AddNewUserTokens(number int, mods ...TokenMod) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		related := o.f.NewTokenWithContext(ctx, mods...)
		m.AddUserTokens(number, related).Apply(ctx, o)
	})
}

func (m userProfileMods) AddExistingUserTokens(existingModels ...*models.Token) UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		for _, em := range existingModels {
			o.r.UserTokens = append(o.r.UserTokens, &userProfileRUserTokensR{
				o: o.f.fromExistingToken(ctx, em),
			})
		}
	})
}

func (m userProfileMods) WithoutUserTokens() UserProfileMod {
	return UserProfileModFunc(func(ctx context.Context, o *UserProfileTemplate) {
		o.r.UserTokens = nil
	})
}
