// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mq

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	CasbinRulesV1S     casbinRulesV1Where[Q]
	Clients            clientWhere[Q]
	GooseVersions      gooseVersionWhere[Q]
	Mails              mailWhere[Q]
	MailBlacklists     mailBlacklistWhere[Q]
	MailDomains        mailDomainWhere[Q]
	MailLists          mailListWhere[Q]
	MailListRecipients mailListRecipientWhere[Q]
	MailTemplates      mailTemplateWhere[Q]
	Mailings           mailingWhere[Q]
	Tokens             tokenWhere[Q]
	UserGroups         userGroupWhere[Q]
	UserProfiles       userProfileWhere[Q]
} {
	return struct {
		CasbinRulesV1S     casbinRulesV1Where[Q]
		Clients            clientWhere[Q]
		GooseVersions      gooseVersionWhere[Q]
		Mails              mailWhere[Q]
		MailBlacklists     mailBlacklistWhere[Q]
		MailDomains        mailDomainWhere[Q]
		MailLists          mailListWhere[Q]
		MailListRecipients mailListRecipientWhere[Q]
		MailTemplates      mailTemplateWhere[Q]
		Mailings           mailingWhere[Q]
		Tokens             tokenWhere[Q]
		UserGroups         userGroupWhere[Q]
		UserProfiles       userProfileWhere[Q]
	}{
		CasbinRulesV1S:     buildCasbinRulesV1Where[Q](CasbinRulesV1S.Columns),
		Clients:            buildClientWhere[Q](Clients.Columns),
		GooseVersions:      buildGooseVersionWhere[Q](GooseVersions.Columns),
		Mails:              buildMailWhere[Q](Mails.Columns),
		MailBlacklists:     buildMailBlacklistWhere[Q](MailBlacklists.Columns),
		MailDomains:        buildMailDomainWhere[Q](MailDomains.Columns),
		MailLists:          buildMailListWhere[Q](MailLists.Columns),
		MailListRecipients: buildMailListRecipientWhere[Q](MailListRecipients.Columns),
		MailTemplates:      buildMailTemplateWhere[Q](MailTemplates.Columns),
		Mailings:           buildMailingWhere[Q](Mailings.Columns),
		Tokens:             buildTokenWhere[Q](Tokens.Columns),
		UserGroups:         buildUserGroupWhere[Q](UserGroups.Columns),
		UserProfiles:       buildUserProfileWhere[Q](UserProfiles.Columns),
	}
}
