// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mq

import (
	"context"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/expr"
)

// CasbinRulesV1 is an object representing the database table.
type CasbinRulesV1 struct {
	PType string `db:"p_type" json:"p_type"`
	V0    string `db:"v0" json:"v0"`
	V1    string `db:"v1" json:"v1"`
	V2    string `db:"v2" json:"v2"`
	V3    string `db:"v3" json:"v3"`
	V4    string `db:"v4" json:"v4"`
	V5    string `db:"v5" json:"v5"`
}

// CasbinRulesV1Slice is an alias for a slice of pointers to CasbinRulesV1.
// This should almost always be used instead of []*CasbinRulesV1.
type CasbinRulesV1Slice []*CasbinRulesV1

// CasbinRulesV1S contains methods to work with the casbin_rules_v1 view
var CasbinRulesV1S = psql.NewViewx[*CasbinRulesV1, CasbinRulesV1Slice]("", "casbin_rules_v1", buildCasbinRulesV1Columns("casbin_rules_v1"))

// CasbinRulesV1SQuery is a query on the casbin_rules_v1 view
type CasbinRulesV1SQuery = *psql.ViewQuery[*CasbinRulesV1, CasbinRulesV1Slice]

func buildCasbinRulesV1Columns(tableName string) casbinRulesV1Columns {
	columnsExpr := expr.NewColumnsExpr(
		"p_type", "v0", "v1", "v2", "v3", "v4", "v5",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return casbinRulesV1Columns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		PType:       buildCasbinRulesV1Column(tableName, "p_type"),
		V0:          buildCasbinRulesV1Column(tableName, "v0"),
		V1:          buildCasbinRulesV1Column(tableName, "v1"),
		V2:          buildCasbinRulesV1Column(tableName, "v2"),
		V3:          buildCasbinRulesV1Column(tableName, "v3"),
		V4:          buildCasbinRulesV1Column(tableName, "v4"),
		V5:          buildCasbinRulesV1Column(tableName, "v5"),
	}
}

type casbinRulesV1Columns struct {
	expr.ColumnsExpr
	tableAlias string
	PType      casbinRulesV1Column
	V0         casbinRulesV1Column
	V1         casbinRulesV1Column
	V2         casbinRulesV1Column
	V3         casbinRulesV1Column
	V4         casbinRulesV1Column
	V5         casbinRulesV1Column
}

// Alias returns the current table alias for the columns set.
func (c casbinRulesV1Columns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (casbinRulesV1Columns) AliasedAs(tableName string) casbinRulesV1Columns {
	return buildCasbinRulesV1Columns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c casbinRulesV1Columns) Unqualified() casbinRulesV1Columns {
	return buildCasbinRulesV1Columns("")
}

func buildCasbinRulesV1Column(alias, name string) casbinRulesV1Column {
	return casbinRulesV1Column{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type casbinRulesV1Column struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c casbinRulesV1Column) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c casbinRulesV1Column) ShouldOmitParens() bool {
	return true
}

// AfterQueryHook is called after CasbinRulesV1 is retrieved from the database
func (o *CasbinRulesV1) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CasbinRulesV1S.AfterSelectHooks.RunHooks(ctx, exec, CasbinRulesV1Slice{o})
	}

	return err
}

// AfterQueryHook is called after CasbinRulesV1Slice is retrieved from the database
func (o CasbinRulesV1Slice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CasbinRulesV1S.AfterSelectHooks.RunHooks(ctx, exec, o)
	}

	return err
}

type casbinRulesV1Where[Q psql.Filterable] struct {
	PType psql.WhereMod[Q, string]
	V0    psql.WhereMod[Q, string]
	V1    psql.WhereMod[Q, string]
	V2    psql.WhereMod[Q, string]
	V3    psql.WhereMod[Q, string]
	V4    psql.WhereMod[Q, string]
	V5    psql.WhereMod[Q, string]
}

func (casbinRulesV1Where[Q]) AliasedAs(alias string) casbinRulesV1Where[Q] {
	return buildCasbinRulesV1Where[Q](buildCasbinRulesV1Columns(alias))
}

func buildCasbinRulesV1Where[Q psql.Filterable](cols casbinRulesV1Columns) casbinRulesV1Where[Q] {
	return casbinRulesV1Where[Q]{
		PType: psql.Where[Q, string](cols.PType.Expression),
		V0:    psql.Where[Q, string](cols.V0.Expression),
		V1:    psql.Where[Q, string](cols.V1.Expression),
		V2:    psql.Where[Q, string](cols.V2.Expression),
		V3:    psql.Where[Q, string](cols.V3.Expression),
		V4:    psql.Where[Q, string](cols.V4.Expression),
		V5:    psql.Where[Q, string](cols.V5.Expression),
	}
}
