// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mq

import (
	"context"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Client is an object representing the database table.
type Client struct {
	ClientSeq       int64                    `db:"client_seq" json:"client_seq"`
	IP              string                   `db:"ip,pk" json:"ip"`
	EquipID         string                   `db:"equip_id" json:"equip_id"`
	Browser         string                   `db:"browser,pk" json:"browser"`
	OrderListEquips null.Val[pq.StringArray] `db:"order_list_equips" json:"order_list_equips"`
}

// ClientSlice is an alias for a slice of pointers to Client.
// This should almost always be used instead of []*Client.
type ClientSlice []*Client

// Clients contains methods to work with the client table
var Clients = psql.NewTablex[*Client, ClientSlice, *ClientSetter]("", "client", buildClientColumns("client"))

// ClientsQuery is a query on the client table
type ClientsQuery = *psql.ViewQuery[*Client, ClientSlice]

func buildClientColumns(tableName string) clientColumns {
	columnsExpr := expr.NewColumnsExpr(
		"client_seq", "ip", "equip_id", "browser", "order_list_equips",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return clientColumns{
		ColumnsExpr:     columnsExpr,
		tableAlias:      tableName,
		ClientSeq:       buildClientColumn(tableName, "client_seq"),
		IP:              buildClientColumn(tableName, "ip"),
		EquipID:         buildClientColumn(tableName, "equip_id"),
		Browser:         buildClientColumn(tableName, "browser"),
		OrderListEquips: buildClientColumn(tableName, "order_list_equips"),
	}
}

type clientColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ClientSeq       clientColumn
	IP              clientColumn
	EquipID         clientColumn
	Browser         clientColumn
	OrderListEquips clientColumn
}

// Alias returns the current table alias for the columns set.
func (c clientColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (clientColumns) AliasedAs(tableName string) clientColumns {
	return buildClientColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c clientColumns) Unqualified() clientColumns {
	return buildClientColumns("")
}

func buildClientColumn(alias, name string) clientColumn {
	return clientColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type clientColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c clientColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c clientColumn) ShouldOmitParens() bool {
	return true
}

// ClientSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ClientSetter struct {
	ClientSeq       omit.Val[int64]              `db:"client_seq" json:"client_seq"`
	IP              omit.Val[string]             `db:"ip,pk" json:"ip"`
	EquipID         omit.Val[string]             `db:"equip_id" json:"equip_id"`
	Browser         omit.Val[string]             `db:"browser,pk" json:"browser"`
	OrderListEquips omitnull.Val[pq.StringArray] `db:"order_list_equips" json:"order_list_equips"`
}

func (s ClientSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ClientSeq.IsValue() {
		vals = append(vals, "client_seq")
	}
	if s.IP.IsValue() {
		vals = append(vals, "ip")
	}
	if s.EquipID.IsValue() {
		vals = append(vals, "equip_id")
	}
	if s.Browser.IsValue() {
		vals = append(vals, "browser")
	}
	if !s.OrderListEquips.IsUnset() {
		vals = append(vals, "order_list_equips")
	}
	return vals
}

func (s ClientSetter) Overwrite(t *Client) {
	if s.ClientSeq.IsValue() {
		t.ClientSeq = s.ClientSeq.MustGet()
	}
	if s.IP.IsValue() {
		t.IP = s.IP.MustGet()
	}
	if s.EquipID.IsValue() {
		t.EquipID = s.EquipID.MustGet()
	}
	if s.Browser.IsValue() {
		t.Browser = s.Browser.MustGet()
	}
	if !s.OrderListEquips.IsUnset() {
		t.OrderListEquips = s.OrderListEquips.MustGetNull()
	}
}

func (s *ClientSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Clients.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ClientSeq.IsValue() {
			vals[0] = psql.Arg(s.ClientSeq.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.IP.IsValue() {
			vals[1] = psql.Arg(s.IP.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.EquipID.IsValue() {
			vals[2] = psql.Arg(s.EquipID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Browser.IsValue() {
			vals[3] = psql.Arg(s.Browser.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.OrderListEquips.IsUnset() {
			vals[4] = psql.Arg(s.OrderListEquips.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ClientSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ClientSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ClientSeq.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "client_seq")...),
			psql.Arg(s.ClientSeq),
		}})
	}

	if s.IP.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "ip")...),
			psql.Arg(s.IP),
		}})
	}

	if s.EquipID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "equip_id")...),
			psql.Arg(s.EquipID),
		}})
	}

	if s.Browser.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "browser")...),
			psql.Arg(s.Browser),
		}})
	}

	if !s.OrderListEquips.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "order_list_equips")...),
			psql.Arg(s.OrderListEquips),
		}})
	}

	return exprs
}

// FindClient retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindClient(ctx context.Context, exec bob.Executor, IPPK string, BrowserPK string, cols ...string) (*Client, error) {
	if len(cols) == 0 {
		return Clients.Query(
			sm.Where(Clients.Columns.IP.EQ(psql.Arg(IPPK))),
			sm.Where(Clients.Columns.Browser.EQ(psql.Arg(BrowserPK))),
		).One(ctx, exec)
	}

	return Clients.Query(
		sm.Where(Clients.Columns.IP.EQ(psql.Arg(IPPK))),
		sm.Where(Clients.Columns.Browser.EQ(psql.Arg(BrowserPK))),
		sm.Columns(Clients.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ClientExists checks the presence of a single record by primary key
func ClientExists(ctx context.Context, exec bob.Executor, IPPK string, BrowserPK string) (bool, error) {
	return Clients.Query(
		sm.Where(Clients.Columns.IP.EQ(psql.Arg(IPPK))),
		sm.Where(Clients.Columns.Browser.EQ(psql.Arg(BrowserPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Client is retrieved from the database
func (o *Client) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Clients.AfterSelectHooks.RunHooks(ctx, exec, ClientSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Clients.AfterInsertHooks.RunHooks(ctx, exec, ClientSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Clients.AfterUpdateHooks.RunHooks(ctx, exec, ClientSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Clients.AfterDeleteHooks.RunHooks(ctx, exec, ClientSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Clients.AfterMergeHooks.RunHooks(ctx, exec, ClientSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Client
func (o *Client) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.IP,
		o.Browser,
	)
}

func (o *Client) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("client", "ip"), psql.Quote("client", "browser")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Client
func (o *Client) Update(ctx context.Context, exec bob.Executor, s *ClientSetter) error {
	v, err := Clients.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Client record with an executor
func (o *Client) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Clients.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Client using the executor
func (o *Client) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Clients.Query(
		sm.Where(Clients.Columns.IP.EQ(psql.Arg(o.IP))),
		sm.Where(Clients.Columns.Browser.EQ(psql.Arg(o.Browser))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ClientSlice is retrieved from the database
func (o ClientSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Clients.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Clients.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Clients.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Clients.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Clients.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ClientSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("client", "ip"), psql.Quote("client", "browser")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ClientSlice) copyMatchingRows(from ...*Client) {
	for i, old := range o {
		for _, new := range from {
			if new.IP != old.IP {
				continue
			}
			if new.Browser != old.Browser {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ClientSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Clients.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Client:
				o.copyMatchingRows(retrieved)
			case []*Client:
				o.copyMatchingRows(retrieved...)
			case ClientSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Client or a slice of Client
				// then run the AfterUpdateHooks on the slice
				_, err = Clients.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ClientSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Clients.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Client:
				o.copyMatchingRows(retrieved)
			case []*Client:
				o.copyMatchingRows(retrieved...)
			case ClientSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Client or a slice of Client
				// then run the AfterDeleteHooks on the slice
				_, err = Clients.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o ClientSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Clients.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Client:
				o.copyMatchingRows(retrieved)
			case []*Client:
				o.copyMatchingRows(retrieved...)
			case ClientSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Client or a slice of Client
				// then run the AfterMergeHooks on the slice
				_, err = Clients.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o ClientSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ClientSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Clients.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ClientSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Clients.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ClientSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Clients.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type clientWhere[Q psql.Filterable] struct {
	ClientSeq       psql.WhereMod[Q, int64]
	IP              psql.WhereMod[Q, string]
	EquipID         psql.WhereMod[Q, string]
	Browser         psql.WhereMod[Q, string]
	OrderListEquips psql.WhereNullMod[Q, pq.StringArray]
}

func (clientWhere[Q]) AliasedAs(alias string) clientWhere[Q] {
	return buildClientWhere[Q](buildClientColumns(alias))
}

func buildClientWhere[Q psql.Filterable](cols clientColumns) clientWhere[Q] {
	return clientWhere[Q]{
		ClientSeq:       psql.Where[Q, int64](cols.ClientSeq.Expression),
		IP:              psql.Where[Q, string](cols.IP.Expression),
		EquipID:         psql.Where[Q, string](cols.EquipID.Expression),
		Browser:         psql.Where[Q, string](cols.Browser.Expression),
		OrderListEquips: psql.WhereNull[Q, pq.StringArray](cols.OrderListEquips.Expression),
	}
}
