// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mq

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// MailBlacklist is an object representing the database table.
type MailBlacklist struct {
	ID        int32               `db:"id,pk" json:"id"`
	Email     string              `db:"email" json:"email"`
	Reason    string              `db:"reason" json:"reason"`
	Origin    string              `db:"origin" json:"origin"`
	Stream    string              `db:"stream" json:"stream"`
	Source    string              `db:"source" json:"source"`
	CreatedAt time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt null.Val[time.Time] `db:"updated_at" json:"updated_at"`
}

// MailBlacklistSlice is an alias for a slice of pointers to MailBlacklist.
// This should almost always be used instead of []*MailBlacklist.
type MailBlacklistSlice []*MailBlacklist

// MailBlacklists contains methods to work with the mail_blacklist table
var MailBlacklists = psql.NewTablex[*MailBlacklist, MailBlacklistSlice, *MailBlacklistSetter]("", "mail_blacklist", buildMailBlacklistColumns("mail_blacklist"))

// MailBlacklistsQuery is a query on the mail_blacklist table
type MailBlacklistsQuery = *psql.ViewQuery[*MailBlacklist, MailBlacklistSlice]

func buildMailBlacklistColumns(tableName string) mailBlacklistColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "email", "reason", "origin", "stream", "source", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return mailBlacklistColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildMailBlacklistColumn(tableName, "id"),
		Email:       buildMailBlacklistColumn(tableName, "email"),
		Reason:      buildMailBlacklistColumn(tableName, "reason"),
		Origin:      buildMailBlacklistColumn(tableName, "origin"),
		Stream:      buildMailBlacklistColumn(tableName, "stream"),
		Source:      buildMailBlacklistColumn(tableName, "source"),
		CreatedAt:   buildMailBlacklistColumn(tableName, "created_at"),
		UpdatedAt:   buildMailBlacklistColumn(tableName, "updated_at"),
	}
}

type mailBlacklistColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mailBlacklistColumn
	Email      mailBlacklistColumn
	Reason     mailBlacklistColumn
	Origin     mailBlacklistColumn
	Stream     mailBlacklistColumn
	Source     mailBlacklistColumn
	CreatedAt  mailBlacklistColumn
	UpdatedAt  mailBlacklistColumn
}

// Alias returns the current table alias for the columns set.
func (c mailBlacklistColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (mailBlacklistColumns) AliasedAs(tableName string) mailBlacklistColumns {
	return buildMailBlacklistColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c mailBlacklistColumns) Unqualified() mailBlacklistColumns {
	return buildMailBlacklistColumns("")
}

func buildMailBlacklistColumn(alias, name string) mailBlacklistColumn {
	return mailBlacklistColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type mailBlacklistColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c mailBlacklistColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c mailBlacklistColumn) ShouldOmitParens() bool {
	return true
}

// MailBlacklistSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type MailBlacklistSetter struct {
	ID        omit.Val[int32]         `db:"id,pk" json:"id"`
	Email     omit.Val[string]        `db:"email" json:"email"`
	Reason    omit.Val[string]        `db:"reason" json:"reason"`
	Origin    omit.Val[string]        `db:"origin" json:"origin"`
	Stream    omit.Val[string]        `db:"stream" json:"stream"`
	Source    omit.Val[string]        `db:"source" json:"source"`
	CreatedAt omit.Val[time.Time]     `db:"created_at" json:"created_at"`
	UpdatedAt omitnull.Val[time.Time] `db:"updated_at" json:"updated_at"`
}

func (s MailBlacklistSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.Reason.IsValue() {
		vals = append(vals, "reason")
	}
	if s.Origin.IsValue() {
		vals = append(vals, "origin")
	}
	if s.Stream.IsValue() {
		vals = append(vals, "stream")
	}
	if s.Source.IsValue() {
		vals = append(vals, "source")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s MailBlacklistSetter) Overwrite(t *MailBlacklist) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.Reason.IsValue() {
		t.Reason = s.Reason.MustGet()
	}
	if s.Origin.IsValue() {
		t.Origin = s.Origin.MustGet()
	}
	if s.Stream.IsValue() {
		t.Stream = s.Stream.MustGet()
	}
	if s.Source.IsValue() {
		t.Source = s.Source.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *MailBlacklistSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return MailBlacklists.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Email.IsValue() {
			vals[1] = psql.Arg(s.Email.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Reason.IsValue() {
			vals[2] = psql.Arg(s.Reason.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Origin.IsValue() {
			vals[3] = psql.Arg(s.Origin.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Stream.IsValue() {
			vals[4] = psql.Arg(s.Stream.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Source.IsValue() {
			vals[5] = psql.Arg(s.Source.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.UpdatedAt.IsUnset() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s MailBlacklistSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s MailBlacklistSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.Reason.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "reason")...),
			psql.Arg(s.Reason),
		}})
	}

	if s.Origin.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "origin")...),
			psql.Arg(s.Origin),
		}})
	}

	if s.Stream.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "stream")...),
			psql.Arg(s.Stream),
		}})
	}

	if s.Source.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "source")...),
			psql.Arg(s.Source),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindMailBlacklist retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindMailBlacklist(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*MailBlacklist, error) {
	if len(cols) == 0 {
		return MailBlacklists.Query(
			sm.Where(MailBlacklists.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return MailBlacklists.Query(
		sm.Where(MailBlacklists.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(MailBlacklists.Columns.Only(cols...)),
	).One(ctx, exec)
}

// MailBlacklistExists checks the presence of a single record by primary key
func MailBlacklistExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return MailBlacklists.Query(
		sm.Where(MailBlacklists.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after MailBlacklist is retrieved from the database
func (o *MailBlacklist) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = MailBlacklists.AfterSelectHooks.RunHooks(ctx, exec, MailBlacklistSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = MailBlacklists.AfterInsertHooks.RunHooks(ctx, exec, MailBlacklistSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = MailBlacklists.AfterUpdateHooks.RunHooks(ctx, exec, MailBlacklistSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = MailBlacklists.AfterDeleteHooks.RunHooks(ctx, exec, MailBlacklistSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = MailBlacklists.AfterMergeHooks.RunHooks(ctx, exec, MailBlacklistSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the MailBlacklist
func (o *MailBlacklist) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *MailBlacklist) pkEQ() dialect.Expression {
	return psql.Quote("mail_blacklist", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the MailBlacklist
func (o *MailBlacklist) Update(ctx context.Context, exec bob.Executor, s *MailBlacklistSetter) error {
	v, err := MailBlacklists.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single MailBlacklist record with an executor
func (o *MailBlacklist) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := MailBlacklists.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the MailBlacklist using the executor
func (o *MailBlacklist) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := MailBlacklists.Query(
		sm.Where(MailBlacklists.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after MailBlacklistSlice is retrieved from the database
func (o MailBlacklistSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = MailBlacklists.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = MailBlacklists.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = MailBlacklists.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = MailBlacklists.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = MailBlacklists.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o MailBlacklistSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("mail_blacklist", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o MailBlacklistSlice) copyMatchingRows(from ...*MailBlacklist) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o MailBlacklistSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return MailBlacklists.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *MailBlacklist:
				o.copyMatchingRows(retrieved)
			case []*MailBlacklist:
				o.copyMatchingRows(retrieved...)
			case MailBlacklistSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a MailBlacklist or a slice of MailBlacklist
				// then run the AfterUpdateHooks on the slice
				_, err = MailBlacklists.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o MailBlacklistSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return MailBlacklists.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *MailBlacklist:
				o.copyMatchingRows(retrieved)
			case []*MailBlacklist:
				o.copyMatchingRows(retrieved...)
			case MailBlacklistSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a MailBlacklist or a slice of MailBlacklist
				// then run the AfterDeleteHooks on the slice
				_, err = MailBlacklists.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o MailBlacklistSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return MailBlacklists.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *MailBlacklist:
				o.copyMatchingRows(retrieved)
			case []*MailBlacklist:
				o.copyMatchingRows(retrieved...)
			case MailBlacklistSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a MailBlacklist or a slice of MailBlacklist
				// then run the AfterMergeHooks on the slice
				_, err = MailBlacklists.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o MailBlacklistSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals MailBlacklistSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := MailBlacklists.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o MailBlacklistSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := MailBlacklists.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o MailBlacklistSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := MailBlacklists.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type mailBlacklistWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int32]
	Email     psql.WhereMod[Q, string]
	Reason    psql.WhereMod[Q, string]
	Origin    psql.WhereMod[Q, string]
	Stream    psql.WhereMod[Q, string]
	Source    psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereNullMod[Q, time.Time]
}

func (mailBlacklistWhere[Q]) AliasedAs(alias string) mailBlacklistWhere[Q] {
	return buildMailBlacklistWhere[Q](buildMailBlacklistColumns(alias))
}

func buildMailBlacklistWhere[Q psql.Filterable](cols mailBlacklistColumns) mailBlacklistWhere[Q] {
	return mailBlacklistWhere[Q]{
		ID:        psql.Where[Q, int32](cols.ID.Expression),
		Email:     psql.Where[Q, string](cols.Email.Expression),
		Reason:    psql.Where[Q, string](cols.Reason.Expression),
		Origin:    psql.Where[Q, string](cols.Origin.Expression),
		Stream:    psql.Where[Q, string](cols.Stream.Expression),
		Source:    psql.Where[Q, string](cols.Source.Expression),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt: psql.WhereNull[Q, time.Time](cols.UpdatedAt.Expression),
	}
}
