// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mq

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// MailDomain is an object representing the database table.
type MailDomain struct {
	ID               int32               `db:"id,pk" json:"id"`
	Domain           string              `db:"domain" json:"domain"`
	FromEmail        string              `db:"from_email" json:"from_email"`
	FromName         string              `db:"from_name" json:"from_name"`
	PostmarkStreamID string              `db:"postmark_stream_id" json:"postmark_stream_id"`
	IsActive         bool                `db:"is_active" json:"is_active"`
	CreatedAt        time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt        null.Val[time.Time] `db:"updated_at" json:"updated_at"`

	R mailDomainR `db:"-" json:"R"`

	C mailDomainC `db:"-" json:"R"`
}

// MailDomainSlice is an alias for a slice of pointers to MailDomain.
// This should almost always be used instead of []*MailDomain.
type MailDomainSlice []*MailDomain

// MailDomains contains methods to work with the mail_domain table
var MailDomains = psql.NewTablex[*MailDomain, MailDomainSlice, *MailDomainSetter]("", "mail_domain", buildMailDomainColumns("mail_domain"))

// MailDomainsQuery is a query on the mail_domain table
type MailDomainsQuery = *psql.ViewQuery[*MailDomain, MailDomainSlice]

// mailDomainR is where relationships are stored.
type mailDomainR struct {
	DomainMailings MailingSlice `json:"DomainMailings"` // mailing.mailing_domain_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded mailDomainRLoaded `db:"-" json:"R"`
}

// mailDomainRLoaded tracks which relationships on MailDomain have been loaded.
type mailDomainRLoaded struct {
	DomainMailings bool `json:"DomainMailings"` // mailing.mailing_domain_id_fkey
}

func buildMailDomainColumns(tableName string) mailDomainColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "domain", "from_email", "from_name", "postmark_stream_id", "is_active", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return mailDomainColumns{
		ColumnsExpr:      columnsExpr,
		tableAlias:       tableName,
		ID:               buildMailDomainColumn(tableName, "id"),
		Domain:           buildMailDomainColumn(tableName, "domain"),
		FromEmail:        buildMailDomainColumn(tableName, "from_email"),
		FromName:         buildMailDomainColumn(tableName, "from_name"),
		PostmarkStreamID: buildMailDomainColumn(tableName, "postmark_stream_id"),
		IsActive:         buildMailDomainColumn(tableName, "is_active"),
		CreatedAt:        buildMailDomainColumn(tableName, "created_at"),
		UpdatedAt:        buildMailDomainColumn(tableName, "updated_at"),
	}
}

type mailDomainColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               mailDomainColumn
	Domain           mailDomainColumn
	FromEmail        mailDomainColumn
	FromName         mailDomainColumn
	PostmarkStreamID mailDomainColumn
	IsActive         mailDomainColumn
	CreatedAt        mailDomainColumn
	UpdatedAt        mailDomainColumn
}

// Alias returns the current table alias for the columns set.
func (c mailDomainColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (mailDomainColumns) AliasedAs(tableName string) mailDomainColumns {
	return buildMailDomainColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c mailDomainColumns) Unqualified() mailDomainColumns {
	return buildMailDomainColumns("")
}

func buildMailDomainColumn(alias, name string) mailDomainColumn {
	return mailDomainColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type mailDomainColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c mailDomainColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c mailDomainColumn) ShouldOmitParens() bool {
	return true
}

// MailDomainSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type MailDomainSetter struct {
	ID               omit.Val[int32]         `db:"id,pk" json:"id"`
	Domain           omit.Val[string]        `db:"domain" json:"domain"`
	FromEmail        omit.Val[string]        `db:"from_email" json:"from_email"`
	FromName         omit.Val[string]        `db:"from_name" json:"from_name"`
	PostmarkStreamID omit.Val[string]        `db:"postmark_stream_id" json:"postmark_stream_id"`
	IsActive         omit.Val[bool]          `db:"is_active" json:"is_active"`
	CreatedAt        omit.Val[time.Time]     `db:"created_at" json:"created_at"`
	UpdatedAt        omitnull.Val[time.Time] `db:"updated_at" json:"updated_at"`
}

func (s MailDomainSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Domain.IsValue() {
		vals = append(vals, "domain")
	}
	if s.FromEmail.IsValue() {
		vals = append(vals, "from_email")
	}
	if s.FromName.IsValue() {
		vals = append(vals, "from_name")
	}
	if s.PostmarkStreamID.IsValue() {
		vals = append(vals, "postmark_stream_id")
	}
	if s.IsActive.IsValue() {
		vals = append(vals, "is_active")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s MailDomainSetter) Overwrite(t *MailDomain) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Domain.IsValue() {
		t.Domain = s.Domain.MustGet()
	}
	if s.FromEmail.IsValue() {
		t.FromEmail = s.FromEmail.MustGet()
	}
	if s.FromName.IsValue() {
		t.FromName = s.FromName.MustGet()
	}
	if s.PostmarkStreamID.IsValue() {
		t.PostmarkStreamID = s.PostmarkStreamID.MustGet()
	}
	if s.IsActive.IsValue() {
		t.IsActive = s.IsActive.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *MailDomainSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return MailDomains.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Domain.IsValue() {
			vals[1] = psql.Arg(s.Domain.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.FromEmail.IsValue() {
			vals[2] = psql.Arg(s.FromEmail.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.FromName.IsValue() {
			vals[3] = psql.Arg(s.FromName.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.PostmarkStreamID.IsValue() {
			vals[4] = psql.Arg(s.PostmarkStreamID.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.IsActive.IsValue() {
			vals[5] = psql.Arg(s.IsActive.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.UpdatedAt.IsUnset() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s MailDomainSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s MailDomainSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Domain.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "domain")...),
			psql.Arg(s.Domain),
		}})
	}

	if s.FromEmail.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "from_email")...),
			psql.Arg(s.FromEmail),
		}})
	}

	if s.FromName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "from_name")...),
			psql.Arg(s.FromName),
		}})
	}

	if s.PostmarkStreamID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "postmark_stream_id")...),
			psql.Arg(s.PostmarkStreamID),
		}})
	}

	if s.IsActive.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_active")...),
			psql.Arg(s.IsActive),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindMailDomain retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindMailDomain(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*MailDomain, error) {
	if len(cols) == 0 {
		return MailDomains.Query(
			sm.Where(MailDomains.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return MailDomains.Query(
		sm.Where(MailDomains.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(MailDomains.Columns.Only(cols...)),
	).One(ctx, exec)
}

// MailDomainExists checks the presence of a single record by primary key
func MailDomainExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return MailDomains.Query(
		sm.Where(MailDomains.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after MailDomain is retrieved from the database
func (o *MailDomain) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = MailDomains.AfterSelectHooks.RunHooks(ctx, exec, MailDomainSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = MailDomains.AfterInsertHooks.RunHooks(ctx, exec, MailDomainSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = MailDomains.AfterUpdateHooks.RunHooks(ctx, exec, MailDomainSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = MailDomains.AfterDeleteHooks.RunHooks(ctx, exec, MailDomainSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = MailDomains.AfterMergeHooks.RunHooks(ctx, exec, MailDomainSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the MailDomain
func (o *MailDomain) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *MailDomain) pkEQ() dialect.Expression {
	return psql.Quote("mail_domain", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the MailDomain
func (o *MailDomain) Update(ctx context.Context, exec bob.Executor, s *MailDomainSetter) error {
	v, err := MailDomains.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single MailDomain record with an executor
func (o *MailDomain) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := MailDomains.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the MailDomain using the executor
func (o *MailDomain) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := MailDomains.Query(
		sm.Where(MailDomains.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after MailDomainSlice is retrieved from the database
func (o MailDomainSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = MailDomains.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = MailDomains.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = MailDomains.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = MailDomains.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = MailDomains.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o MailDomainSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("mail_domain", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o MailDomainSlice) copyMatchingRows(from ...*MailDomain) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o MailDomainSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return MailDomains.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *MailDomain:
				o.copyMatchingRows(retrieved)
			case []*MailDomain:
				o.copyMatchingRows(retrieved...)
			case MailDomainSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a MailDomain or a slice of MailDomain
				// then run the AfterUpdateHooks on the slice
				_, err = MailDomains.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o MailDomainSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return MailDomains.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *MailDomain:
				o.copyMatchingRows(retrieved)
			case []*MailDomain:
				o.copyMatchingRows(retrieved...)
			case MailDomainSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a MailDomain or a slice of MailDomain
				// then run the AfterDeleteHooks on the slice
				_, err = MailDomains.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o MailDomainSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return MailDomains.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *MailDomain:
				o.copyMatchingRows(retrieved)
			case []*MailDomain:
				o.copyMatchingRows(retrieved...)
			case MailDomainSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a MailDomain or a slice of MailDomain
				// then run the AfterMergeHooks on the slice
				_, err = MailDomains.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o MailDomainSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals MailDomainSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := MailDomains.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o MailDomainSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := MailDomains.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o MailDomainSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := MailDomains.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// DomainMailings starts a query for related objects on mailing
func (o *MailDomain) DomainMailings(mods ...bob.Mod[*dialect.SelectQuery]) MailingsQuery {
	return Mailings.Query(append(mods,
		sm.Where(Mailings.Columns.DomainID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os MailDomainSlice) DomainMailings(mods ...bob.Mod[*dialect.SelectQuery]) MailingsQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return Mailings.Query(append(mods,
		sm.Where(psql.Group(Mailings.Columns.DomainID).OP("IN", PKArgExpr)),
	)...)
}

func insertMailDomainDomainMailings0(ctx context.Context, exec bob.Executor, mailings1 []*MailingSetter, mailDomain0 *MailDomain) (MailingSlice, error) {
	for i := range mailings1 {
		mailings1[i].DomainID = omit.From(mailDomain0.ID)
	}

	ret, err := Mailings.Insert(bob.ToMods(mailings1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertMailDomainDomainMailings0: %w", err)
	}

	return ret, nil
}

func attachMailDomainDomainMailings0(ctx context.Context, exec bob.Executor, count int, mailings1 MailingSlice, mailDomain0 *MailDomain) (MailingSlice, error) {
	setter := &MailingSetter{
		DomainID: omit.From(mailDomain0.ID),
	}

	err := mailings1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachMailDomainDomainMailings0: %w", err)
	}

	return mailings1, nil
}

func (mailDomain0 *MailDomain) InsertDomainMailings(ctx context.Context, exec bob.Executor, related ...*MailingSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	mailings1, err := insertMailDomainDomainMailings0(ctx, exec, related, mailDomain0)
	if err != nil {
		return err
	}

	mailDomain0.R.DomainMailings = append(mailDomain0.R.DomainMailings, mailings1...)

	return nil
}

func (mailDomain0 *MailDomain) AttachDomainMailings(ctx context.Context, exec bob.Executor, related ...*Mailing) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	mailings1 := MailingSlice(related)

	_, err = attachMailDomainDomainMailings0(ctx, exec, len(related), mailings1, mailDomain0)
	if err != nil {
		return err
	}

	mailDomain0.R.DomainMailings = append(mailDomain0.R.DomainMailings, mailings1...)

	return nil
}

type mailDomainWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, int32]
	Domain           psql.WhereMod[Q, string]
	FromEmail        psql.WhereMod[Q, string]
	FromName         psql.WhereMod[Q, string]
	PostmarkStreamID psql.WhereMod[Q, string]
	IsActive         psql.WhereMod[Q, bool]
	CreatedAt        psql.WhereMod[Q, time.Time]
	UpdatedAt        psql.WhereNullMod[Q, time.Time]
}

func (mailDomainWhere[Q]) AliasedAs(alias string) mailDomainWhere[Q] {
	return buildMailDomainWhere[Q](buildMailDomainColumns(alias))
}

func buildMailDomainWhere[Q psql.Filterable](cols mailDomainColumns) mailDomainWhere[Q] {
	return mailDomainWhere[Q]{
		ID:               psql.Where[Q, int32](cols.ID.Expression),
		Domain:           psql.Where[Q, string](cols.Domain.Expression),
		FromEmail:        psql.Where[Q, string](cols.FromEmail.Expression),
		FromName:         psql.Where[Q, string](cols.FromName.Expression),
		PostmarkStreamID: psql.Where[Q, string](cols.PostmarkStreamID.Expression),
		IsActive:         psql.Where[Q, bool](cols.IsActive.Expression),
		CreatedAt:        psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:        psql.WhereNull[Q, time.Time](cols.UpdatedAt.Expression),
	}
}

func (o *MailDomain) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "DomainMailings":
		rels, ok := retrieved.(MailingSlice)
		if !ok {
			return fmt.Errorf("mailDomain cannot load %T as %q", retrieved, name)
		}

		o.R.DomainMailings = rels
		o.R.Loaded.DomainMailings = true

		return nil
	default:
		return fmt.Errorf("mailDomain has no relationship %q", name)
	}
}

type mailDomainPreloader struct{}

func buildMailDomainPreloader() mailDomainPreloader {
	return mailDomainPreloader{}
}

type mailDomainThenLoader[Q orm.Loadable] struct {
	DomainMailings func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildMailDomainThenLoader[Q orm.Loadable]() mailDomainThenLoader[Q] {
	type DomainMailingsLoadInterface interface {
		LoadDomainMailings(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return mailDomainThenLoader[Q]{
		DomainMailings: thenLoadBuilder[Q](
			"DomainMailings",
			func(ctx context.Context, exec bob.Executor, retrieved DomainMailingsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadDomainMailings(ctx, exec, mods...)
			},
		),
	}
}

// LoadDomainMailings loads the mailDomain's DomainMailings into the .R struct
func (o *MailDomain) LoadDomainMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.DomainMailings = nil
	o.R.Loaded.DomainMailings = false

	related, err := o.DomainMailings(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.DomainMailings = related
	o.R.Loaded.DomainMailings = true
	return nil
}

// LoadDomainMailings loads the mailDomain's DomainMailings into the .R struct
func (os MailDomainSlice) LoadDomainMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	mailings, err := os.DomainMailings(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.DomainMailings = nil
		o.R.Loaded.DomainMailings = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range mailings {

			if !(o.ID == rel.DomainID) {
				continue
			}

			o.R.DomainMailings = append(o.R.DomainMailings, rel)
		}
	}

	return nil
}

// mailDomainC is where relationship counts are stored.
type mailDomainC struct {
	DomainMailings *int64 `json:"DomainMailings"`
}

// PreloadCount sets a count in the C struct by name
func (o *MailDomain) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "DomainMailings":
		o.C.DomainMailings = &count
	}
	return nil
}

type mailDomainCountPreloader struct {
	DomainMailings func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildMailDomainCountPreloader() mailDomainCountPreloader {
	return mailDomainCountPreloader{
		DomainMailings: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*MailDomain]("DomainMailings", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = MailDomains.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Mailings.Name()),
					sm.Where(psql.Quote(Mailings.Alias(), "domain_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type mailDomainCountThenLoader[Q orm.Loadable] struct {
	DomainMailings func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildMailDomainCountThenLoader[Q orm.Loadable]() mailDomainCountThenLoader[Q] {
	type DomainMailingsCountInterface interface {
		LoadCountDomainMailings(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return mailDomainCountThenLoader[Q]{
		DomainMailings: countThenLoadBuilder[Q](
			"DomainMailings",
			func(ctx context.Context, exec bob.Executor, retrieved DomainMailingsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountDomainMailings(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountDomainMailings loads the count of DomainMailings into the C struct
func (o *MailDomain) LoadCountDomainMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.DomainMailings(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.DomainMailings = &count
	return nil
}

// LoadCountDomainMailings loads the count of DomainMailings for a slice in a single batch query
func (os MailDomainSlice) LoadCountDomainMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Mailings.Columns.DomainID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Mailings.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Mailings.Columns.DomainID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Mailings.Columns.DomainID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.DomainMailings = &count
	}

	return nil
}

type mailDomainJoins[Q dialect.Joinable] struct {
	typ            string
	DomainMailings modAs[Q, mailingColumns]
}

func (j mailDomainJoins[Q]) aliasedAs(alias string) mailDomainJoins[Q] {
	return buildMailDomainJoins[Q](buildMailDomainColumns(alias), j.typ)
}

func buildMailDomainJoins[Q dialect.Joinable](cols mailDomainColumns, typ string) mailDomainJoins[Q] {
	return mailDomainJoins[Q]{
		typ: typ,
		DomainMailings: modAs[Q, mailingColumns]{
			c: Mailings.Columns,
			f: func(to mailingColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Mailings.Name().As(to.Alias())).On(
						to.DomainID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
