// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mq

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// UserProfile is an object representing the database table.
type UserProfile struct {
	ID                     int32               `db:"id,pk" json:"id"`
	Email                  string              `db:"email" json:"email"`
	Salutation             string              `db:"salutation" json:"salutation"`
	Forename               string              `db:"forename" json:"forename"`
	Lastname               string              `db:"lastname" json:"lastname"`
	Password               string              `db:"password" json:"password"`
	MustResetPassword      bool                `db:"must_reset_password" json:"must_reset_password"`
	LastLogin              null.Val[time.Time] `db:"last_login" json:"last_login"`
	CreatedByUserProfileID null.Val[int32]     `db:"created_by_user_profile_id" json:"created_by_user_profile_id"`
	LastUpdatedByUserID    null.Val[int32]     `db:"last_updated_by_user_id" json:"last_updated_by_user_id"`
	Disabled               bool                `db:"disabled" json:"disabled"`
	EmailValidated         bool                `db:"email_validated" json:"email_validated"`
	CreatedAt              time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt              null.Val[time.Time] `db:"updated_at" json:"updated_at"`

	R userProfileR `db:"-" json:"R"`

	C userProfileC `db:"-" json:"R"`
}

// UserProfileSlice is an alias for a slice of pointers to UserProfile.
// This should almost always be used instead of []*UserProfile.
type UserProfileSlice []*UserProfile

// UserProfiles contains methods to work with the user_profile table
var UserProfiles = psql.NewTablex[*UserProfile, UserProfileSlice, *UserProfileSetter]("", "user_profile", buildUserProfileColumns("user_profile"))

// UserProfilesQuery is a query on the user_profile table
type UserProfilesQuery = *psql.ViewQuery[*UserProfile, UserProfileSlice]

// userProfileR is where relationships are stored.
type userProfileR struct {
	CreatedByUserMailLists     MailListSlice     `json:"CreatedByUserMailLists"`     // mail_list.mail_list_created_by_user_id_fkey
	UpdatedByUserMailLists     MailListSlice     `json:"UpdatedByUserMailLists"`     // mail_list.mail_list_updated_by_user_id_fkey
	CreatedByUserMailTemplates MailTemplateSlice `json:"CreatedByUserMailTemplates"` // mail_template.mail_template_created_by_user_id_fkey
	UpdatedByUserMailTemplates MailTemplateSlice `json:"UpdatedByUserMailTemplates"` // mail_template.mail_template_updated_by_user_id_fkey
	CreatedByUserMailings      MailingSlice      `json:"CreatedByUserMailings"`      // mailing.mailing_created_by_user_id_fkey
	UpdatedByUserMailings      MailingSlice      `json:"UpdatedByUserMailings"`      // mailing.mailing_updated_by_user_id_fkey
	UserTokens                 TokenSlice        `json:"UserTokens"`                 // token.token_user_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded userProfileRLoaded `db:"-" json:"R"`
}

// userProfileRLoaded tracks which relationships on UserProfile have been loaded.
type userProfileRLoaded struct {
	CreatedByUserMailLists     bool `json:"CreatedByUserMailLists"`     // mail_list.mail_list_created_by_user_id_fkey
	UpdatedByUserMailLists     bool `json:"UpdatedByUserMailLists"`     // mail_list.mail_list_updated_by_user_id_fkey
	CreatedByUserMailTemplates bool `json:"CreatedByUserMailTemplates"` // mail_template.mail_template_created_by_user_id_fkey
	UpdatedByUserMailTemplates bool `json:"UpdatedByUserMailTemplates"` // mail_template.mail_template_updated_by_user_id_fkey
	CreatedByUserMailings      bool `json:"CreatedByUserMailings"`      // mailing.mailing_created_by_user_id_fkey
	UpdatedByUserMailings      bool `json:"UpdatedByUserMailings"`      // mailing.mailing_updated_by_user_id_fkey
	UserTokens                 bool `json:"UserTokens"`                 // token.token_user_id_fkey
}

func buildUserProfileColumns(tableName string) userProfileColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "email", "salutation", "forename", "lastname", "password", "must_reset_password", "last_login", "created_by_user_profile_id", "last_updated_by_user_id", "disabled", "email_validated", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return userProfileColumns{
		ColumnsExpr:            columnsExpr,
		tableAlias:             tableName,
		ID:                     buildUserProfileColumn(tableName, "id"),
		Email:                  buildUserProfileColumn(tableName, "email"),
		Salutation:             buildUserProfileColumn(tableName, "salutation"),
		Forename:               buildUserProfileColumn(tableName, "forename"),
		Lastname:               buildUserProfileColumn(tableName, "lastname"),
		Password:               buildUserProfileColumn(tableName, "password"),
		MustResetPassword:      buildUserProfileColumn(tableName, "must_reset_password"),
		LastLogin:              buildUserProfileColumn(tableName, "last_login"),
		CreatedByUserProfileID: buildUserProfileColumn(tableName, "created_by_user_profile_id"),
		LastUpdatedByUserID:    buildUserProfileColumn(tableName, "last_updated_by_user_id"),
		Disabled:               buildUserProfileColumn(tableName, "disabled"),
		EmailValidated:         buildUserProfileColumn(tableName, "email_validated"),
		CreatedAt:              buildUserProfileColumn(tableName, "created_at"),
		UpdatedAt:              buildUserProfileColumn(tableName, "updated_at"),
	}
}

type userProfileColumns struct {
	expr.ColumnsExpr
	tableAlias             string
	ID                     userProfileColumn
	Email                  userProfileColumn
	Salutation             userProfileColumn
	Forename               userProfileColumn
	Lastname               userProfileColumn
	Password               userProfileColumn
	MustResetPassword      userProfileColumn
	LastLogin              userProfileColumn
	CreatedByUserProfileID userProfileColumn
	LastUpdatedByUserID    userProfileColumn
	Disabled               userProfileColumn
	EmailValidated         userProfileColumn
	CreatedAt              userProfileColumn
	UpdatedAt              userProfileColumn
}

// Alias returns the current table alias for the columns set.
func (c userProfileColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (userProfileColumns) AliasedAs(tableName string) userProfileColumns {
	return buildUserProfileColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c userProfileColumns) Unqualified() userProfileColumns {
	return buildUserProfileColumns("")
}

func buildUserProfileColumn(alias, name string) userProfileColumn {
	return userProfileColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type userProfileColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c userProfileColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c userProfileColumn) ShouldOmitParens() bool {
	return true
}

// UserProfileSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserProfileSetter struct {
	ID                     omit.Val[int32]         `db:"id,pk" json:"id"`
	Email                  omit.Val[string]        `db:"email" json:"email"`
	Salutation             omit.Val[string]        `db:"salutation" json:"salutation"`
	Forename               omit.Val[string]        `db:"forename" json:"forename"`
	Lastname               omit.Val[string]        `db:"lastname" json:"lastname"`
	Password               omit.Val[string]        `db:"password" json:"password"`
	MustResetPassword      omit.Val[bool]          `db:"must_reset_password" json:"must_reset_password"`
	LastLogin              omitnull.Val[time.Time] `db:"last_login" json:"last_login"`
	CreatedByUserProfileID omitnull.Val[int32]     `db:"created_by_user_profile_id" json:"created_by_user_profile_id"`
	LastUpdatedByUserID    omitnull.Val[int32]     `db:"last_updated_by_user_id" json:"last_updated_by_user_id"`
	Disabled               omit.Val[bool]          `db:"disabled" json:"disabled"`
	EmailValidated         omit.Val[bool]          `db:"email_validated" json:"email_validated"`
	CreatedAt              omit.Val[time.Time]     `db:"created_at" json:"created_at"`
	UpdatedAt              omitnull.Val[time.Time] `db:"updated_at" json:"updated_at"`
}

func (s UserProfileSetter) SetColumns() []string {
	vals := make([]string, 0, 14)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.Salutation.IsValue() {
		vals = append(vals, "salutation")
	}
	if s.Forename.IsValue() {
		vals = append(vals, "forename")
	}
	if s.Lastname.IsValue() {
		vals = append(vals, "lastname")
	}
	if s.Password.IsValue() {
		vals = append(vals, "password")
	}
	if s.MustResetPassword.IsValue() {
		vals = append(vals, "must_reset_password")
	}
	if !s.LastLogin.IsUnset() {
		vals = append(vals, "last_login")
	}
	if !s.CreatedByUserProfileID.IsUnset() {
		vals = append(vals, "created_by_user_profile_id")
	}
	if !s.LastUpdatedByUserID.IsUnset() {
		vals = append(vals, "last_updated_by_user_id")
	}
	if s.Disabled.IsValue() {
		vals = append(vals, "disabled")
	}
	if s.EmailValidated.IsValue() {
		vals = append(vals, "email_validated")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserProfileSetter) Overwrite(t *UserProfile) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.Salutation.IsValue() {
		t.Salutation = s.Salutation.MustGet()
	}
	if s.Forename.IsValue() {
		t.Forename = s.Forename.MustGet()
	}
	if s.Lastname.IsValue() {
		t.Lastname = s.Lastname.MustGet()
	}
	if s.Password.IsValue() {
		t.Password = s.Password.MustGet()
	}
	if s.MustResetPassword.IsValue() {
		t.MustResetPassword = s.MustResetPassword.MustGet()
	}
	if !s.LastLogin.IsUnset() {
		t.LastLogin = s.LastLogin.MustGetNull()
	}
	if !s.CreatedByUserProfileID.IsUnset() {
		t.CreatedByUserProfileID = s.CreatedByUserProfileID.MustGetNull()
	}
	if !s.LastUpdatedByUserID.IsUnset() {
		t.LastUpdatedByUserID = s.LastUpdatedByUserID.MustGetNull()
	}
	if s.Disabled.IsValue() {
		t.Disabled = s.Disabled.MustGet()
	}
	if s.EmailValidated.IsValue() {
		t.EmailValidated = s.EmailValidated.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *UserProfileSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UserProfiles.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 14)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Email.IsValue() {
			vals[1] = psql.Arg(s.Email.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Salutation.IsValue() {
			vals[2] = psql.Arg(s.Salutation.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Forename.IsValue() {
			vals[3] = psql.Arg(s.Forename.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Lastname.IsValue() {
			vals[4] = psql.Arg(s.Lastname.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Password.IsValue() {
			vals[5] = psql.Arg(s.Password.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.MustResetPassword.IsValue() {
			vals[6] = psql.Arg(s.MustResetPassword.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.LastLogin.IsUnset() {
			vals[7] = psql.Arg(s.LastLogin.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.CreatedByUserProfileID.IsUnset() {
			vals[8] = psql.Arg(s.CreatedByUserProfileID.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.LastUpdatedByUserID.IsUnset() {
			vals[9] = psql.Arg(s.LastUpdatedByUserID.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.Disabled.IsValue() {
			vals[10] = psql.Arg(s.Disabled.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.EmailValidated.IsValue() {
			vals[11] = psql.Arg(s.EmailValidated.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[12] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if !s.UpdatedAt.IsUnset() {
			vals[13] = psql.Arg(s.UpdatedAt.MustGetNull())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserProfileSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserProfileSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 14)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.Salutation.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "salutation")...),
			psql.Arg(s.Salutation),
		}})
	}

	if s.Forename.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "forename")...),
			psql.Arg(s.Forename),
		}})
	}

	if s.Lastname.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lastname")...),
			psql.Arg(s.Lastname),
		}})
	}

	if s.Password.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password")...),
			psql.Arg(s.Password),
		}})
	}

	if s.MustResetPassword.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "must_reset_password")...),
			psql.Arg(s.MustResetPassword),
		}})
	}

	if !s.LastLogin.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_login")...),
			psql.Arg(s.LastLogin),
		}})
	}

	if !s.CreatedByUserProfileID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_by_user_profile_id")...),
			psql.Arg(s.CreatedByUserProfileID),
		}})
	}

	if !s.LastUpdatedByUserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_updated_by_user_id")...),
			psql.Arg(s.LastUpdatedByUserID),
		}})
	}

	if s.Disabled.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "disabled")...),
			psql.Arg(s.Disabled),
		}})
	}

	if s.EmailValidated.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email_validated")...),
			psql.Arg(s.EmailValidated),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUserProfile retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserProfile(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*UserProfile, error) {
	if len(cols) == 0 {
		return UserProfiles.Query(
			sm.Where(UserProfiles.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return UserProfiles.Query(
		sm.Where(UserProfiles.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(UserProfiles.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserProfileExists checks the presence of a single record by primary key
func UserProfileExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return UserProfiles.Query(
		sm.Where(UserProfiles.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UserProfile is retrieved from the database
func (o *UserProfile) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserProfiles.AfterSelectHooks.RunHooks(ctx, exec, UserProfileSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UserProfiles.AfterInsertHooks.RunHooks(ctx, exec, UserProfileSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UserProfiles.AfterUpdateHooks.RunHooks(ctx, exec, UserProfileSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UserProfiles.AfterDeleteHooks.RunHooks(ctx, exec, UserProfileSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = UserProfiles.AfterMergeHooks.RunHooks(ctx, exec, UserProfileSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the UserProfile
func (o *UserProfile) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *UserProfile) pkEQ() dialect.Expression {
	return psql.Quote("user_profile", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UserProfile
func (o *UserProfile) Update(ctx context.Context, exec bob.Executor, s *UserProfileSetter) error {
	v, err := UserProfiles.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UserProfile record with an executor
func (o *UserProfile) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UserProfiles.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UserProfile using the executor
func (o *UserProfile) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserProfiles.Query(
		sm.Where(UserProfiles.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserProfileSlice is retrieved from the database
func (o UserProfileSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserProfiles.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UserProfiles.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UserProfiles.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UserProfiles.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = UserProfiles.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserProfileSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("user_profile", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserProfileSlice) copyMatchingRows(from ...*UserProfile) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserProfileSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserProfiles.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserProfile:
				o.copyMatchingRows(retrieved)
			case []*UserProfile:
				o.copyMatchingRows(retrieved...)
			case UserProfileSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserProfile or a slice of UserProfile
				// then run the AfterUpdateHooks on the slice
				_, err = UserProfiles.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserProfileSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserProfiles.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserProfile:
				o.copyMatchingRows(retrieved)
			case []*UserProfile:
				o.copyMatchingRows(retrieved...)
			case UserProfileSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserProfile or a slice of UserProfile
				// then run the AfterDeleteHooks on the slice
				_, err = UserProfiles.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o UserProfileSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserProfiles.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserProfile:
				o.copyMatchingRows(retrieved)
			case []*UserProfile:
				o.copyMatchingRows(retrieved...)
			case UserProfileSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserProfile or a slice of UserProfile
				// then run the AfterMergeHooks on the slice
				_, err = UserProfiles.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o UserProfileSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserProfileSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserProfiles.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserProfileSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserProfiles.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserProfileSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UserProfiles.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// CreatedByUserMailLists starts a query for related objects on mail_list
func (o *UserProfile) CreatedByUserMailLists(mods ...bob.Mod[*dialect.SelectQuery]) MailListsQuery {
	return MailLists.Query(append(mods,
		sm.Where(MailLists.Columns.CreatedByUserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserProfileSlice) CreatedByUserMailLists(mods ...bob.Mod[*dialect.SelectQuery]) MailListsQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return MailLists.Query(append(mods,
		sm.Where(psql.Group(MailLists.Columns.CreatedByUserID).OP("IN", PKArgExpr)),
	)...)
}

// UpdatedByUserMailLists starts a query for related objects on mail_list
func (o *UserProfile) UpdatedByUserMailLists(mods ...bob.Mod[*dialect.SelectQuery]) MailListsQuery {
	return MailLists.Query(append(mods,
		sm.Where(MailLists.Columns.UpdatedByUserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserProfileSlice) UpdatedByUserMailLists(mods ...bob.Mod[*dialect.SelectQuery]) MailListsQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return MailLists.Query(append(mods,
		sm.Where(psql.Group(MailLists.Columns.UpdatedByUserID).OP("IN", PKArgExpr)),
	)...)
}

// CreatedByUserMailTemplates starts a query for related objects on mail_template
func (o *UserProfile) CreatedByUserMailTemplates(mods ...bob.Mod[*dialect.SelectQuery]) MailTemplatesQuery {
	return MailTemplates.Query(append(mods,
		sm.Where(MailTemplates.Columns.CreatedByUserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserProfileSlice) CreatedByUserMailTemplates(mods ...bob.Mod[*dialect.SelectQuery]) MailTemplatesQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return MailTemplates.Query(append(mods,
		sm.Where(psql.Group(MailTemplates.Columns.CreatedByUserID).OP("IN", PKArgExpr)),
	)...)
}

// UpdatedByUserMailTemplates starts a query for related objects on mail_template
func (o *UserProfile) UpdatedByUserMailTemplates(mods ...bob.Mod[*dialect.SelectQuery]) MailTemplatesQuery {
	return MailTemplates.Query(append(mods,
		sm.Where(MailTemplates.Columns.UpdatedByUserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserProfileSlice) UpdatedByUserMailTemplates(mods ...bob.Mod[*dialect.SelectQuery]) MailTemplatesQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return MailTemplates.Query(append(mods,
		sm.Where(psql.Group(MailTemplates.Columns.UpdatedByUserID).OP("IN", PKArgExpr)),
	)...)
}

// CreatedByUserMailings starts a query for related objects on mailing
func (o *UserProfile) CreatedByUserMailings(mods ...bob.Mod[*dialect.SelectQuery]) MailingsQuery {
	return Mailings.Query(append(mods,
		sm.Where(Mailings.Columns.CreatedByUserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserProfileSlice) CreatedByUserMailings(mods ...bob.Mod[*dialect.SelectQuery]) MailingsQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return Mailings.Query(append(mods,
		sm.Where(psql.Group(Mailings.Columns.CreatedByUserID).OP("IN", PKArgExpr)),
	)...)
}

// UpdatedByUserMailings starts a query for related objects on mailing
func (o *UserProfile) UpdatedByUserMailings(mods ...bob.Mod[*dialect.SelectQuery]) MailingsQuery {
	return Mailings.Query(append(mods,
		sm.Where(Mailings.Columns.UpdatedByUserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserProfileSlice) UpdatedByUserMailings(mods ...bob.Mod[*dialect.SelectQuery]) MailingsQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return Mailings.Query(append(mods,
		sm.Where(psql.Group(Mailings.Columns.UpdatedByUserID).OP("IN", PKArgExpr)),
	)...)
}

// UserTokens starts a query for related objects on token
func (o *UserProfile) UserTokens(mods ...bob.Mod[*dialect.SelectQuery]) TokensQuery {
	return Tokens.Query(append(mods,
		sm.Where(Tokens.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserProfileSlice) UserTokens(mods ...bob.Mod[*dialect.SelectQuery]) TokensQuery {
	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	return Tokens.Query(append(mods,
		sm.Where(psql.Group(Tokens.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func insertUserProfileCreatedByUserMailLists0(ctx context.Context, exec bob.Executor, mailLists1 []*MailListSetter, userProfile0 *UserProfile) (MailListSlice, error) {
	for i := range mailLists1 {
		mailLists1[i].CreatedByUserID = omitnull.From(userProfile0.ID)
	}

	ret, err := MailLists.Insert(bob.ToMods(mailLists1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProfileCreatedByUserMailLists0: %w", err)
	}

	return ret, nil
}

func attachUserProfileCreatedByUserMailLists0(ctx context.Context, exec bob.Executor, count int, mailLists1 MailListSlice, userProfile0 *UserProfile) (MailListSlice, error) {
	setter := &MailListSetter{
		CreatedByUserID: omitnull.From(userProfile0.ID),
	}

	err := mailLists1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProfileCreatedByUserMailLists0: %w", err)
	}

	return mailLists1, nil
}

func (userProfile0 *UserProfile) InsertCreatedByUserMailLists(ctx context.Context, exec bob.Executor, related ...*MailListSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	mailLists1, err := insertUserProfileCreatedByUserMailLists0(ctx, exec, related, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.CreatedByUserMailLists = append(userProfile0.R.CreatedByUserMailLists, mailLists1...)

	return nil
}

func (userProfile0 *UserProfile) AttachCreatedByUserMailLists(ctx context.Context, exec bob.Executor, related ...*MailList) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	mailLists1 := MailListSlice(related)

	_, err = attachUserProfileCreatedByUserMailLists0(ctx, exec, len(related), mailLists1, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.CreatedByUserMailLists = append(userProfile0.R.CreatedByUserMailLists, mailLists1...)

	return nil
}

func insertUserProfileUpdatedByUserMailLists0(ctx context.Context, exec bob.Executor, mailLists1 []*MailListSetter, userProfile0 *UserProfile) (MailListSlice, error) {
	for i := range mailLists1 {
		mailLists1[i].UpdatedByUserID = omitnull.From(userProfile0.ID)
	}

	ret, err := MailLists.Insert(bob.ToMods(mailLists1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProfileUpdatedByUserMailLists0: %w", err)
	}

	return ret, nil
}

func attachUserProfileUpdatedByUserMailLists0(ctx context.Context, exec bob.Executor, count int, mailLists1 MailListSlice, userProfile0 *UserProfile) (MailListSlice, error) {
	setter := &MailListSetter{
		UpdatedByUserID: omitnull.From(userProfile0.ID),
	}

	err := mailLists1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProfileUpdatedByUserMailLists0: %w", err)
	}

	return mailLists1, nil
}

func (userProfile0 *UserProfile) InsertUpdatedByUserMailLists(ctx context.Context, exec bob.Executor, related ...*MailListSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	mailLists1, err := insertUserProfileUpdatedByUserMailLists0(ctx, exec, related, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UpdatedByUserMailLists = append(userProfile0.R.UpdatedByUserMailLists, mailLists1...)

	return nil
}

func (userProfile0 *UserProfile) AttachUpdatedByUserMailLists(ctx context.Context, exec bob.Executor, related ...*MailList) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	mailLists1 := MailListSlice(related)

	_, err = attachUserProfileUpdatedByUserMailLists0(ctx, exec, len(related), mailLists1, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UpdatedByUserMailLists = append(userProfile0.R.UpdatedByUserMailLists, mailLists1...)

	return nil
}

func insertUserProfileCreatedByUserMailTemplates0(ctx context.Context, exec bob.Executor, mailTemplates1 []*MailTemplateSetter, userProfile0 *UserProfile) (MailTemplateSlice, error) {
	for i := range mailTemplates1 {
		mailTemplates1[i].CreatedByUserID = omitnull.From(userProfile0.ID)
	}

	ret, err := MailTemplates.Insert(bob.ToMods(mailTemplates1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProfileCreatedByUserMailTemplates0: %w", err)
	}

	return ret, nil
}

func attachUserProfileCreatedByUserMailTemplates0(ctx context.Context, exec bob.Executor, count int, mailTemplates1 MailTemplateSlice, userProfile0 *UserProfile) (MailTemplateSlice, error) {
	setter := &MailTemplateSetter{
		CreatedByUserID: omitnull.From(userProfile0.ID),
	}

	err := mailTemplates1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProfileCreatedByUserMailTemplates0: %w", err)
	}

	return mailTemplates1, nil
}

func (userProfile0 *UserProfile) InsertCreatedByUserMailTemplates(ctx context.Context, exec bob.Executor, related ...*MailTemplateSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	mailTemplates1, err := insertUserProfileCreatedByUserMailTemplates0(ctx, exec, related, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.CreatedByUserMailTemplates = append(userProfile0.R.CreatedByUserMailTemplates, mailTemplates1...)

	return nil
}

func (userProfile0 *UserProfile) AttachCreatedByUserMailTemplates(ctx context.Context, exec bob.Executor, related ...*MailTemplate) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	mailTemplates1 := MailTemplateSlice(related)

	_, err = attachUserProfileCreatedByUserMailTemplates0(ctx, exec, len(related), mailTemplates1, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.CreatedByUserMailTemplates = append(userProfile0.R.CreatedByUserMailTemplates, mailTemplates1...)

	return nil
}

func insertUserProfileUpdatedByUserMailTemplates0(ctx context.Context, exec bob.Executor, mailTemplates1 []*MailTemplateSetter, userProfile0 *UserProfile) (MailTemplateSlice, error) {
	for i := range mailTemplates1 {
		mailTemplates1[i].UpdatedByUserID = omitnull.From(userProfile0.ID)
	}

	ret, err := MailTemplates.Insert(bob.ToMods(mailTemplates1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProfileUpdatedByUserMailTemplates0: %w", err)
	}

	return ret, nil
}

func attachUserProfileUpdatedByUserMailTemplates0(ctx context.Context, exec bob.Executor, count int, mailTemplates1 MailTemplateSlice, userProfile0 *UserProfile) (MailTemplateSlice, error) {
	setter := &MailTemplateSetter{
		UpdatedByUserID: omitnull.From(userProfile0.ID),
	}

	err := mailTemplates1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProfileUpdatedByUserMailTemplates0: %w", err)
	}

	return mailTemplates1, nil
}

func (userProfile0 *UserProfile) InsertUpdatedByUserMailTemplates(ctx context.Context, exec bob.Executor, related ...*MailTemplateSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	mailTemplates1, err := insertUserProfileUpdatedByUserMailTemplates0(ctx, exec, related, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UpdatedByUserMailTemplates = append(userProfile0.R.UpdatedByUserMailTemplates, mailTemplates1...)

	return nil
}

func (userProfile0 *UserProfile) AttachUpdatedByUserMailTemplates(ctx context.Context, exec bob.Executor, related ...*MailTemplate) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	mailTemplates1 := MailTemplateSlice(related)

	_, err = attachUserProfileUpdatedByUserMailTemplates0(ctx, exec, len(related), mailTemplates1, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UpdatedByUserMailTemplates = append(userProfile0.R.UpdatedByUserMailTemplates, mailTemplates1...)

	return nil
}

func insertUserProfileCreatedByUserMailings0(ctx context.Context, exec bob.Executor, mailings1 []*MailingSetter, userProfile0 *UserProfile) (MailingSlice, error) {
	for i := range mailings1 {
		mailings1[i].CreatedByUserID = omitnull.From(userProfile0.ID)
	}

	ret, err := Mailings.Insert(bob.ToMods(mailings1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProfileCreatedByUserMailings0: %w", err)
	}

	return ret, nil
}

func attachUserProfileCreatedByUserMailings0(ctx context.Context, exec bob.Executor, count int, mailings1 MailingSlice, userProfile0 *UserProfile) (MailingSlice, error) {
	setter := &MailingSetter{
		CreatedByUserID: omitnull.From(userProfile0.ID),
	}

	err := mailings1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProfileCreatedByUserMailings0: %w", err)
	}

	return mailings1, nil
}

func (userProfile0 *UserProfile) InsertCreatedByUserMailings(ctx context.Context, exec bob.Executor, related ...*MailingSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	mailings1, err := insertUserProfileCreatedByUserMailings0(ctx, exec, related, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.CreatedByUserMailings = append(userProfile0.R.CreatedByUserMailings, mailings1...)

	return nil
}

func (userProfile0 *UserProfile) AttachCreatedByUserMailings(ctx context.Context, exec bob.Executor, related ...*Mailing) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	mailings1 := MailingSlice(related)

	_, err = attachUserProfileCreatedByUserMailings0(ctx, exec, len(related), mailings1, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.CreatedByUserMailings = append(userProfile0.R.CreatedByUserMailings, mailings1...)

	return nil
}

func insertUserProfileUpdatedByUserMailings0(ctx context.Context, exec bob.Executor, mailings1 []*MailingSetter, userProfile0 *UserProfile) (MailingSlice, error) {
	for i := range mailings1 {
		mailings1[i].UpdatedByUserID = omitnull.From(userProfile0.ID)
	}

	ret, err := Mailings.Insert(bob.ToMods(mailings1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProfileUpdatedByUserMailings0: %w", err)
	}

	return ret, nil
}

func attachUserProfileUpdatedByUserMailings0(ctx context.Context, exec bob.Executor, count int, mailings1 MailingSlice, userProfile0 *UserProfile) (MailingSlice, error) {
	setter := &MailingSetter{
		UpdatedByUserID: omitnull.From(userProfile0.ID),
	}

	err := mailings1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProfileUpdatedByUserMailings0: %w", err)
	}

	return mailings1, nil
}

func (userProfile0 *UserProfile) InsertUpdatedByUserMailings(ctx context.Context, exec bob.Executor, related ...*MailingSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	mailings1, err := insertUserProfileUpdatedByUserMailings0(ctx, exec, related, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UpdatedByUserMailings = append(userProfile0.R.UpdatedByUserMailings, mailings1...)

	return nil
}

func (userProfile0 *UserProfile) AttachUpdatedByUserMailings(ctx context.Context, exec bob.Executor, related ...*Mailing) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	mailings1 := MailingSlice(related)

	_, err = attachUserProfileUpdatedByUserMailings0(ctx, exec, len(related), mailings1, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UpdatedByUserMailings = append(userProfile0.R.UpdatedByUserMailings, mailings1...)

	return nil
}

func insertUserProfileUserTokens0(ctx context.Context, exec bob.Executor, tokens1 []*TokenSetter, userProfile0 *UserProfile) (TokenSlice, error) {
	for i := range tokens1 {
		tokens1[i].UserID = omitnull.From(userProfile0.ID)
	}

	ret, err := Tokens.Insert(bob.ToMods(tokens1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserProfileUserTokens0: %w", err)
	}

	return ret, nil
}

func attachUserProfileUserTokens0(ctx context.Context, exec bob.Executor, count int, tokens1 TokenSlice, userProfile0 *UserProfile) (TokenSlice, error) {
	setter := &TokenSetter{
		UserID: omitnull.From(userProfile0.ID),
	}

	err := tokens1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserProfileUserTokens0: %w", err)
	}

	return tokens1, nil
}

func (userProfile0 *UserProfile) InsertUserTokens(ctx context.Context, exec bob.Executor, related ...*TokenSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	tokens1, err := insertUserProfileUserTokens0(ctx, exec, related, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UserTokens = append(userProfile0.R.UserTokens, tokens1...)

	return nil
}

func (userProfile0 *UserProfile) AttachUserTokens(ctx context.Context, exec bob.Executor, related ...*Token) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tokens1 := TokenSlice(related)

	_, err = attachUserProfileUserTokens0(ctx, exec, len(related), tokens1, userProfile0)
	if err != nil {
		return err
	}

	userProfile0.R.UserTokens = append(userProfile0.R.UserTokens, tokens1...)

	return nil
}

type userProfileWhere[Q psql.Filterable] struct {
	ID                     psql.WhereMod[Q, int32]
	Email                  psql.WhereMod[Q, string]
	Salutation             psql.WhereMod[Q, string]
	Forename               psql.WhereMod[Q, string]
	Lastname               psql.WhereMod[Q, string]
	Password               psql.WhereMod[Q, string]
	MustResetPassword      psql.WhereMod[Q, bool]
	LastLogin              psql.WhereNullMod[Q, time.Time]
	CreatedByUserProfileID psql.WhereNullMod[Q, int32]
	LastUpdatedByUserID    psql.WhereNullMod[Q, int32]
	Disabled               psql.WhereMod[Q, bool]
	EmailValidated         psql.WhereMod[Q, bool]
	CreatedAt              psql.WhereMod[Q, time.Time]
	UpdatedAt              psql.WhereNullMod[Q, time.Time]
}

func (userProfileWhere[Q]) AliasedAs(alias string) userProfileWhere[Q] {
	return buildUserProfileWhere[Q](buildUserProfileColumns(alias))
}

func buildUserProfileWhere[Q psql.Filterable](cols userProfileColumns) userProfileWhere[Q] {
	return userProfileWhere[Q]{
		ID:                     psql.Where[Q, int32](cols.ID.Expression),
		Email:                  psql.Where[Q, string](cols.Email.Expression),
		Salutation:             psql.Where[Q, string](cols.Salutation.Expression),
		Forename:               psql.Where[Q, string](cols.Forename.Expression),
		Lastname:               psql.Where[Q, string](cols.Lastname.Expression),
		Password:               psql.Where[Q, string](cols.Password.Expression),
		MustResetPassword:      psql.Where[Q, bool](cols.MustResetPassword.Expression),
		LastLogin:              psql.WhereNull[Q, time.Time](cols.LastLogin.Expression),
		CreatedByUserProfileID: psql.WhereNull[Q, int32](cols.CreatedByUserProfileID.Expression),
		LastUpdatedByUserID:    psql.WhereNull[Q, int32](cols.LastUpdatedByUserID.Expression),
		Disabled:               psql.Where[Q, bool](cols.Disabled.Expression),
		EmailValidated:         psql.Where[Q, bool](cols.EmailValidated.Expression),
		CreatedAt:              psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:              psql.WhereNull[Q, time.Time](cols.UpdatedAt.Expression),
	}
}

func (o *UserProfile) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CreatedByUserMailLists":
		rels, ok := retrieved.(MailListSlice)
		if !ok {
			return fmt.Errorf("userProfile cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByUserMailLists = rels
		o.R.Loaded.CreatedByUserMailLists = true

		return nil
	case "UpdatedByUserMailLists":
		rels, ok := retrieved.(MailListSlice)
		if !ok {
			return fmt.Errorf("userProfile cannot load %T as %q", retrieved, name)
		}

		o.R.UpdatedByUserMailLists = rels
		o.R.Loaded.UpdatedByUserMailLists = true

		return nil
	case "CreatedByUserMailTemplates":
		rels, ok := retrieved.(MailTemplateSlice)
		if !ok {
			return fmt.Errorf("userProfile cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByUserMailTemplates = rels
		o.R.Loaded.CreatedByUserMailTemplates = true

		return nil
	case "UpdatedByUserMailTemplates":
		rels, ok := retrieved.(MailTemplateSlice)
		if !ok {
			return fmt.Errorf("userProfile cannot load %T as %q", retrieved, name)
		}

		o.R.UpdatedByUserMailTemplates = rels
		o.R.Loaded.UpdatedByUserMailTemplates = true

		return nil
	case "CreatedByUserMailings":
		rels, ok := retrieved.(MailingSlice)
		if !ok {
			return fmt.Errorf("userProfile cannot load %T as %q", retrieved, name)
		}

		o.R.CreatedByUserMailings = rels
		o.R.Loaded.CreatedByUserMailings = true

		return nil
	case "UpdatedByUserMailings":
		rels, ok := retrieved.(MailingSlice)
		if !ok {
			return fmt.Errorf("userProfile cannot load %T as %q", retrieved, name)
		}

		o.R.UpdatedByUserMailings = rels
		o.R.Loaded.UpdatedByUserMailings = true

		return nil
	case "UserTokens":
		rels, ok := retrieved.(TokenSlice)
		if !ok {
			return fmt.Errorf("userProfile cannot load %T as %q", retrieved, name)
		}

		o.R.UserTokens = rels
		o.R.Loaded.UserTokens = true

		return nil
	default:
		return fmt.Errorf("userProfile has no relationship %q", name)
	}
}

type userProfilePreloader struct{}

func buildUserProfilePreloader() userProfilePreloader {
	return userProfilePreloader{}
}

type userProfileThenLoader[Q orm.Loadable] struct {
	CreatedByUserMailLists     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpdatedByUserMailLists     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedByUserMailTemplates func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpdatedByUserMailTemplates func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedByUserMailings      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpdatedByUserMailings      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UserTokens                 func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserProfileThenLoader[Q orm.Loadable]() userProfileThenLoader[Q] {
	type CreatedByUserMailListsLoadInterface interface {
		LoadCreatedByUserMailLists(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpdatedByUserMailListsLoadInterface interface {
		LoadUpdatedByUserMailLists(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByUserMailTemplatesLoadInterface interface {
		LoadCreatedByUserMailTemplates(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpdatedByUserMailTemplatesLoadInterface interface {
		LoadUpdatedByUserMailTemplates(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByUserMailingsLoadInterface interface {
		LoadCreatedByUserMailings(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpdatedByUserMailingsLoadInterface interface {
		LoadUpdatedByUserMailings(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserTokensLoadInterface interface {
		LoadUserTokens(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userProfileThenLoader[Q]{
		CreatedByUserMailLists: thenLoadBuilder[Q](
			"CreatedByUserMailLists",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserMailListsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByUserMailLists(ctx, exec, mods...)
			},
		),
		UpdatedByUserMailLists: thenLoadBuilder[Q](
			"UpdatedByUserMailLists",
			func(ctx context.Context, exec bob.Executor, retrieved UpdatedByUserMailListsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUpdatedByUserMailLists(ctx, exec, mods...)
			},
		),
		CreatedByUserMailTemplates: thenLoadBuilder[Q](
			"CreatedByUserMailTemplates",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserMailTemplatesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByUserMailTemplates(ctx, exec, mods...)
			},
		),
		UpdatedByUserMailTemplates: thenLoadBuilder[Q](
			"UpdatedByUserMailTemplates",
			func(ctx context.Context, exec bob.Executor, retrieved UpdatedByUserMailTemplatesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUpdatedByUserMailTemplates(ctx, exec, mods...)
			},
		),
		CreatedByUserMailings: thenLoadBuilder[Q](
			"CreatedByUserMailings",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserMailingsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCreatedByUserMailings(ctx, exec, mods...)
			},
		),
		UpdatedByUserMailings: thenLoadBuilder[Q](
			"UpdatedByUserMailings",
			func(ctx context.Context, exec bob.Executor, retrieved UpdatedByUserMailingsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUpdatedByUserMailings(ctx, exec, mods...)
			},
		),
		UserTokens: thenLoadBuilder[Q](
			"UserTokens",
			func(ctx context.Context, exec bob.Executor, retrieved UserTokensLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserTokens(ctx, exec, mods...)
			},
		),
	}
}

// LoadCreatedByUserMailLists loads the userProfile's CreatedByUserMailLists into the .R struct
func (o *UserProfile) LoadCreatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByUserMailLists = nil
	o.R.Loaded.CreatedByUserMailLists = false

	related, err := o.CreatedByUserMailLists(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.CreatedByUserMailLists = related
	o.R.Loaded.CreatedByUserMailLists = true
	return nil
}

// LoadCreatedByUserMailLists loads the userProfile's CreatedByUserMailLists into the .R struct
func (os UserProfileSlice) LoadCreatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	mailLists, err := os.CreatedByUserMailLists(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CreatedByUserMailLists = nil
		o.R.Loaded.CreatedByUserMailLists = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range mailLists {

			if !rel.CreatedByUserID.IsValue() {
				continue
			}
			if !(rel.CreatedByUserID.IsValue() && o.ID == rel.CreatedByUserID.MustGet()) {
				continue
			}

			o.R.CreatedByUserMailLists = append(o.R.CreatedByUserMailLists, rel)
		}
	}

	return nil
}

// LoadUpdatedByUserMailLists loads the userProfile's UpdatedByUserMailLists into the .R struct
func (o *UserProfile) LoadUpdatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UpdatedByUserMailLists = nil
	o.R.Loaded.UpdatedByUserMailLists = false

	related, err := o.UpdatedByUserMailLists(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.UpdatedByUserMailLists = related
	o.R.Loaded.UpdatedByUserMailLists = true
	return nil
}

// LoadUpdatedByUserMailLists loads the userProfile's UpdatedByUserMailLists into the .R struct
func (os UserProfileSlice) LoadUpdatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	mailLists, err := os.UpdatedByUserMailLists(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UpdatedByUserMailLists = nil
		o.R.Loaded.UpdatedByUserMailLists = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range mailLists {

			if !rel.UpdatedByUserID.IsValue() {
				continue
			}
			if !(rel.UpdatedByUserID.IsValue() && o.ID == rel.UpdatedByUserID.MustGet()) {
				continue
			}

			o.R.UpdatedByUserMailLists = append(o.R.UpdatedByUserMailLists, rel)
		}
	}

	return nil
}

// LoadCreatedByUserMailTemplates loads the userProfile's CreatedByUserMailTemplates into the .R struct
func (o *UserProfile) LoadCreatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByUserMailTemplates = nil
	o.R.Loaded.CreatedByUserMailTemplates = false

	related, err := o.CreatedByUserMailTemplates(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.CreatedByUserMailTemplates = related
	o.R.Loaded.CreatedByUserMailTemplates = true
	return nil
}

// LoadCreatedByUserMailTemplates loads the userProfile's CreatedByUserMailTemplates into the .R struct
func (os UserProfileSlice) LoadCreatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	mailTemplates, err := os.CreatedByUserMailTemplates(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CreatedByUserMailTemplates = nil
		o.R.Loaded.CreatedByUserMailTemplates = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range mailTemplates {

			if !rel.CreatedByUserID.IsValue() {
				continue
			}
			if !(rel.CreatedByUserID.IsValue() && o.ID == rel.CreatedByUserID.MustGet()) {
				continue
			}

			o.R.CreatedByUserMailTemplates = append(o.R.CreatedByUserMailTemplates, rel)
		}
	}

	return nil
}

// LoadUpdatedByUserMailTemplates loads the userProfile's UpdatedByUserMailTemplates into the .R struct
func (o *UserProfile) LoadUpdatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UpdatedByUserMailTemplates = nil
	o.R.Loaded.UpdatedByUserMailTemplates = false

	related, err := o.UpdatedByUserMailTemplates(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.UpdatedByUserMailTemplates = related
	o.R.Loaded.UpdatedByUserMailTemplates = true
	return nil
}

// LoadUpdatedByUserMailTemplates loads the userProfile's UpdatedByUserMailTemplates into the .R struct
func (os UserProfileSlice) LoadUpdatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	mailTemplates, err := os.UpdatedByUserMailTemplates(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UpdatedByUserMailTemplates = nil
		o.R.Loaded.UpdatedByUserMailTemplates = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range mailTemplates {

			if !rel.UpdatedByUserID.IsValue() {
				continue
			}
			if !(rel.UpdatedByUserID.IsValue() && o.ID == rel.UpdatedByUserID.MustGet()) {
				continue
			}

			o.R.UpdatedByUserMailTemplates = append(o.R.UpdatedByUserMailTemplates, rel)
		}
	}

	return nil
}

// LoadCreatedByUserMailings loads the userProfile's CreatedByUserMailings into the .R struct
func (o *UserProfile) LoadCreatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CreatedByUserMailings = nil
	o.R.Loaded.CreatedByUserMailings = false

	related, err := o.CreatedByUserMailings(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.CreatedByUserMailings = related
	o.R.Loaded.CreatedByUserMailings = true
	return nil
}

// LoadCreatedByUserMailings loads the userProfile's CreatedByUserMailings into the .R struct
func (os UserProfileSlice) LoadCreatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	mailings, err := os.CreatedByUserMailings(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.CreatedByUserMailings = nil
		o.R.Loaded.CreatedByUserMailings = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range mailings {

			if !rel.CreatedByUserID.IsValue() {
				continue
			}
			if !(rel.CreatedByUserID.IsValue() && o.ID == rel.CreatedByUserID.MustGet()) {
				continue
			}

			o.R.CreatedByUserMailings = append(o.R.CreatedByUserMailings, rel)
		}
	}

	return nil
}

// LoadUpdatedByUserMailings loads the userProfile's UpdatedByUserMailings into the .R struct
func (o *UserProfile) LoadUpdatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UpdatedByUserMailings = nil
	o.R.Loaded.UpdatedByUserMailings = false

	related, err := o.UpdatedByUserMailings(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.UpdatedByUserMailings = related
	o.R.Loaded.UpdatedByUserMailings = true
	return nil
}

// LoadUpdatedByUserMailings loads the userProfile's UpdatedByUserMailings into the .R struct
func (os UserProfileSlice) LoadUpdatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	mailings, err := os.UpdatedByUserMailings(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UpdatedByUserMailings = nil
		o.R.Loaded.UpdatedByUserMailings = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range mailings {

			if !rel.UpdatedByUserID.IsValue() {
				continue
			}
			if !(rel.UpdatedByUserID.IsValue() && o.ID == rel.UpdatedByUserID.MustGet()) {
				continue
			}

			o.R.UpdatedByUserMailings = append(o.R.UpdatedByUserMailings, rel)
		}
	}

	return nil
}

// LoadUserTokens loads the userProfile's UserTokens into the .R struct
func (o *UserProfile) LoadUserTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserTokens = nil
	o.R.Loaded.UserTokens = false

	related, err := o.UserTokens(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.UserTokens = related
	o.R.Loaded.UserTokens = true
	return nil
}

// LoadUserTokens loads the userProfile's UserTokens into the .R struct
func (os UserProfileSlice) LoadUserTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tokens, err := os.UserTokens(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UserTokens = nil
		o.R.Loaded.UserTokens = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range tokens {

			if !rel.UserID.IsValue() {
				continue
			}
			if !(rel.UserID.IsValue() && o.ID == rel.UserID.MustGet()) {
				continue
			}

			o.R.UserTokens = append(o.R.UserTokens, rel)
		}
	}

	return nil
}

// userProfileC is where relationship counts are stored.
type userProfileC struct {
	CreatedByUserMailLists     *int64 `json:"CreatedByUserMailLists"`
	UpdatedByUserMailLists     *int64 `json:"UpdatedByUserMailLists"`
	CreatedByUserMailTemplates *int64 `json:"CreatedByUserMailTemplates"`
	UpdatedByUserMailTemplates *int64 `json:"UpdatedByUserMailTemplates"`
	CreatedByUserMailings      *int64 `json:"CreatedByUserMailings"`
	UpdatedByUserMailings      *int64 `json:"UpdatedByUserMailings"`
	UserTokens                 *int64 `json:"UserTokens"`
}

// PreloadCount sets a count in the C struct by name
func (o *UserProfile) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CreatedByUserMailLists":
		o.C.CreatedByUserMailLists = &count
	case "UpdatedByUserMailLists":
		o.C.UpdatedByUserMailLists = &count
	case "CreatedByUserMailTemplates":
		o.C.CreatedByUserMailTemplates = &count
	case "UpdatedByUserMailTemplates":
		o.C.UpdatedByUserMailTemplates = &count
	case "CreatedByUserMailings":
		o.C.CreatedByUserMailings = &count
	case "UpdatedByUserMailings":
		o.C.UpdatedByUserMailings = &count
	case "UserTokens":
		o.C.UserTokens = &count
	}
	return nil
}

type userProfileCountPreloader struct {
	CreatedByUserMailLists     func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	UpdatedByUserMailLists     func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	CreatedByUserMailTemplates func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	UpdatedByUserMailTemplates func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	CreatedByUserMailings      func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	UpdatedByUserMailings      func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	UserTokens                 func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildUserProfileCountPreloader() userProfileCountPreloader {
	return userProfileCountPreloader{
		CreatedByUserMailLists: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserProfile]("CreatedByUserMailLists", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserProfiles.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(MailLists.Name()),
					sm.Where(psql.Quote(MailLists.Alias(), "created_by_user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		UpdatedByUserMailLists: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserProfile]("UpdatedByUserMailLists", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserProfiles.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(MailLists.Name()),
					sm.Where(psql.Quote(MailLists.Alias(), "updated_by_user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		CreatedByUserMailTemplates: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserProfile]("CreatedByUserMailTemplates", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserProfiles.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(MailTemplates.Name()),
					sm.Where(psql.Quote(MailTemplates.Alias(), "created_by_user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		UpdatedByUserMailTemplates: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserProfile]("UpdatedByUserMailTemplates", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserProfiles.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(MailTemplates.Name()),
					sm.Where(psql.Quote(MailTemplates.Alias(), "updated_by_user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		CreatedByUserMailings: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserProfile]("CreatedByUserMailings", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserProfiles.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Mailings.Name()),
					sm.Where(psql.Quote(Mailings.Alias(), "created_by_user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		UpdatedByUserMailings: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserProfile]("UpdatedByUserMailings", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserProfiles.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Mailings.Name()),
					sm.Where(psql.Quote(Mailings.Alias(), "updated_by_user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		UserTokens: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*UserProfile]("UserTokens", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = UserProfiles.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Tokens.Name()),
					sm.Where(psql.Quote(Tokens.Alias(), "user_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type userProfileCountThenLoader[Q orm.Loadable] struct {
	CreatedByUserMailLists     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpdatedByUserMailLists     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedByUserMailTemplates func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpdatedByUserMailTemplates func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	CreatedByUserMailings      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpdatedByUserMailings      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UserTokens                 func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserProfileCountThenLoader[Q orm.Loadable]() userProfileCountThenLoader[Q] {
	type CreatedByUserMailListsCountInterface interface {
		LoadCountCreatedByUserMailLists(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpdatedByUserMailListsCountInterface interface {
		LoadCountUpdatedByUserMailLists(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByUserMailTemplatesCountInterface interface {
		LoadCountCreatedByUserMailTemplates(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpdatedByUserMailTemplatesCountInterface interface {
		LoadCountUpdatedByUserMailTemplates(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CreatedByUserMailingsCountInterface interface {
		LoadCountCreatedByUserMailings(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpdatedByUserMailingsCountInterface interface {
		LoadCountUpdatedByUserMailings(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserTokensCountInterface interface {
		LoadCountUserTokens(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userProfileCountThenLoader[Q]{
		CreatedByUserMailLists: countThenLoadBuilder[Q](
			"CreatedByUserMailLists",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserMailListsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountCreatedByUserMailLists(ctx, exec, mods...)
			},
		),
		UpdatedByUserMailLists: countThenLoadBuilder[Q](
			"UpdatedByUserMailLists",
			func(ctx context.Context, exec bob.Executor, retrieved UpdatedByUserMailListsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUpdatedByUserMailLists(ctx, exec, mods...)
			},
		),
		CreatedByUserMailTemplates: countThenLoadBuilder[Q](
			"CreatedByUserMailTemplates",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserMailTemplatesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountCreatedByUserMailTemplates(ctx, exec, mods...)
			},
		),
		UpdatedByUserMailTemplates: countThenLoadBuilder[Q](
			"UpdatedByUserMailTemplates",
			func(ctx context.Context, exec bob.Executor, retrieved UpdatedByUserMailTemplatesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUpdatedByUserMailTemplates(ctx, exec, mods...)
			},
		),
		CreatedByUserMailings: countThenLoadBuilder[Q](
			"CreatedByUserMailings",
			func(ctx context.Context, exec bob.Executor, retrieved CreatedByUserMailingsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountCreatedByUserMailings(ctx, exec, mods...)
			},
		),
		UpdatedByUserMailings: countThenLoadBuilder[Q](
			"UpdatedByUserMailings",
			func(ctx context.Context, exec bob.Executor, retrieved UpdatedByUserMailingsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUpdatedByUserMailings(ctx, exec, mods...)
			},
		),
		UserTokens: countThenLoadBuilder[Q](
			"UserTokens",
			func(ctx context.Context, exec bob.Executor, retrieved UserTokensCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountUserTokens(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountCreatedByUserMailLists loads the count of CreatedByUserMailLists into the C struct
func (o *UserProfile) LoadCountCreatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.CreatedByUserMailLists(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.CreatedByUserMailLists = &count
	return nil
}

// LoadCountCreatedByUserMailLists loads the count of CreatedByUserMailLists for a slice in a single batch query
func (os UserProfileSlice) LoadCountCreatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			MailLists.Columns.CreatedByUserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(MailLists.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(MailLists.Columns.CreatedByUserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(MailLists.Columns.CreatedByUserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.CreatedByUserMailLists = &count
	}

	return nil
}

// LoadCountUpdatedByUserMailLists loads the count of UpdatedByUserMailLists into the C struct
func (o *UserProfile) LoadCountUpdatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.UpdatedByUserMailLists(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.UpdatedByUserMailLists = &count
	return nil
}

// LoadCountUpdatedByUserMailLists loads the count of UpdatedByUserMailLists for a slice in a single batch query
func (os UserProfileSlice) LoadCountUpdatedByUserMailLists(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			MailLists.Columns.UpdatedByUserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(MailLists.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(MailLists.Columns.UpdatedByUserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(MailLists.Columns.UpdatedByUserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.UpdatedByUserMailLists = &count
	}

	return nil
}

// LoadCountCreatedByUserMailTemplates loads the count of CreatedByUserMailTemplates into the C struct
func (o *UserProfile) LoadCountCreatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.CreatedByUserMailTemplates(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.CreatedByUserMailTemplates = &count
	return nil
}

// LoadCountCreatedByUserMailTemplates loads the count of CreatedByUserMailTemplates for a slice in a single batch query
func (os UserProfileSlice) LoadCountCreatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			MailTemplates.Columns.CreatedByUserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(MailTemplates.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(MailTemplates.Columns.CreatedByUserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(MailTemplates.Columns.CreatedByUserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.CreatedByUserMailTemplates = &count
	}

	return nil
}

// LoadCountUpdatedByUserMailTemplates loads the count of UpdatedByUserMailTemplates into the C struct
func (o *UserProfile) LoadCountUpdatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.UpdatedByUserMailTemplates(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.UpdatedByUserMailTemplates = &count
	return nil
}

// LoadCountUpdatedByUserMailTemplates loads the count of UpdatedByUserMailTemplates for a slice in a single batch query
func (os UserProfileSlice) LoadCountUpdatedByUserMailTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			MailTemplates.Columns.UpdatedByUserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(MailTemplates.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(MailTemplates.Columns.UpdatedByUserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(MailTemplates.Columns.UpdatedByUserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.UpdatedByUserMailTemplates = &count
	}

	return nil
}

// LoadCountCreatedByUserMailings loads the count of CreatedByUserMailings into the C struct
func (o *UserProfile) LoadCountCreatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.CreatedByUserMailings(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.CreatedByUserMailings = &count
	return nil
}

// LoadCountCreatedByUserMailings loads the count of CreatedByUserMailings for a slice in a single batch query
func (os UserProfileSlice) LoadCountCreatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Mailings.Columns.CreatedByUserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Mailings.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Mailings.Columns.CreatedByUserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Mailings.Columns.CreatedByUserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.CreatedByUserMailings = &count
	}

	return nil
}

// LoadCountUpdatedByUserMailings loads the count of UpdatedByUserMailings into the C struct
func (o *UserProfile) LoadCountUpdatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.UpdatedByUserMailings(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.UpdatedByUserMailings = &count
	return nil
}

// LoadCountUpdatedByUserMailings loads the count of UpdatedByUserMailings for a slice in a single batch query
func (os UserProfileSlice) LoadCountUpdatedByUserMailings(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Mailings.Columns.UpdatedByUserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Mailings.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Mailings.Columns.UpdatedByUserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Mailings.Columns.UpdatedByUserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.UpdatedByUserMailings = &count
	}

	return nil
}

// LoadCountUserTokens loads the count of UserTokens into the C struct
func (o *UserProfile) LoadCountUserTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.UserTokens(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.UserTokens = &count
	return nil
}

// LoadCountUserTokens loads the count of UserTokens for a slice in a single batch query
func (os UserProfileSlice) LoadCountUserTokens(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "integer[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int32
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Tokens.Columns.UserID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Tokens.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(Tokens.Columns.UserID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Tokens.Columns.UserID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int32]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.UserTokens = &count
	}

	return nil
}

type userProfileJoins[Q dialect.Joinable] struct {
	typ                        string
	CreatedByUserMailLists     modAs[Q, mailListColumns]
	UpdatedByUserMailLists     modAs[Q, mailListColumns]
	CreatedByUserMailTemplates modAs[Q, mailTemplateColumns]
	UpdatedByUserMailTemplates modAs[Q, mailTemplateColumns]
	CreatedByUserMailings      modAs[Q, mailingColumns]
	UpdatedByUserMailings      modAs[Q, mailingColumns]
	UserTokens                 modAs[Q, tokenColumns]
}

func (j userProfileJoins[Q]) aliasedAs(alias string) userProfileJoins[Q] {
	return buildUserProfileJoins[Q](buildUserProfileColumns(alias), j.typ)
}

func buildUserProfileJoins[Q dialect.Joinable](cols userProfileColumns, typ string) userProfileJoins[Q] {
	return userProfileJoins[Q]{
		typ: typ,
		CreatedByUserMailLists: modAs[Q, mailListColumns]{
			c: MailLists.Columns,
			f: func(to mailListColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MailLists.Name().As(to.Alias())).On(
						to.CreatedByUserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UpdatedByUserMailLists: modAs[Q, mailListColumns]{
			c: MailLists.Columns,
			f: func(to mailListColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MailLists.Name().As(to.Alias())).On(
						to.UpdatedByUserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		CreatedByUserMailTemplates: modAs[Q, mailTemplateColumns]{
			c: MailTemplates.Columns,
			f: func(to mailTemplateColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MailTemplates.Name().As(to.Alias())).On(
						to.CreatedByUserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UpdatedByUserMailTemplates: modAs[Q, mailTemplateColumns]{
			c: MailTemplates.Columns,
			f: func(to mailTemplateColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MailTemplates.Name().As(to.Alias())).On(
						to.UpdatedByUserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		CreatedByUserMailings: modAs[Q, mailingColumns]{
			c: Mailings.Columns,
			f: func(to mailingColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Mailings.Name().As(to.Alias())).On(
						to.CreatedByUserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UpdatedByUserMailings: modAs[Q, mailingColumns]{
			c: Mailings.Columns,
			f: func(to mailingColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Mailings.Name().As(to.Alias())).On(
						to.UpdatedByUserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UserTokens: modAs[Q, tokenColumns]{
			c: Tokens.Columns,
			f: func(to tokenColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tokens.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
