// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MailTemplateErrors = &mailTemplateErrors{
	ErrUniqueMailTemplatePkey: &UniqueConstraintError{
		schema:  "",
		table:   "mail_template",
		columns: []string{"id"},
		s:       "mail_template_pkey",
	},
}

type mailTemplateErrors struct {
	ErrUniqueMailTemplatePkey *UniqueConstraintError
}
