// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MailBlacklistErrors = &mailBlacklistErrors{
	ErrUniqueMailBlacklistPkey: &UniqueConstraintError{
		schema:  "",
		table:   "mail_blacklist",
		columns: []string{"id"},
		s:       "mail_blacklist_pkey",
	},
}

type mailBlacklistErrors struct {
	ErrUniqueMailBlacklistPkey *UniqueConstraintError
}
