// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MailListRecipientErrors = &mailListRecipientErrors{
	ErrUniqueMailListRecipientPkey: &UniqueConstraintError{
		schema:  "",
		table:   "mail_list_recipient",
		columns: []string{"id"},
		s:       "mail_list_recipient_pkey",
	},
}

type mailListRecipientErrors struct {
	ErrUniqueMailListRecipientPkey *UniqueConstraintError
}
