// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MailDomainErrors = &mailDomainErrors{
	ErrUniqueMailDomainPkey: &UniqueConstraintError{
		schema:  "",
		table:   "mail_domain",
		columns: []string{"id"},
		s:       "mail_domain_pkey",
	},
}

type mailDomainErrors struct {
	ErrUniqueMailDomainPkey *UniqueConstraintError
}
