// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MailErrors = &mailErrors{
	ErrUniqueMailPkey: &UniqueConstraintError{
		schema:  "",
		table:   "mail",
		columns: []string{"id"},
		s:       "mail_pkey",
	},
}

type mailErrors struct {
	ErrUniqueMailPkey *UniqueConstraintError
}
