// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MailListErrors = &mailListErrors{
	ErrUniqueMailListPkey: &UniqueConstraintError{
		schema:  "",
		table:   "mail_list",
		columns: []string{"id"},
		s:       "mail_list_pkey",
	},
}

type mailListErrors struct {
	ErrUniqueMailListPkey *UniqueConstraintError
}
