// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TokenErrors = &tokenErrors{
	ErrUniqueTokenPkey: &UniqueConstraintError{
		schema:  "",
		table:   "token",
		columns: []string{"id"},
		s:       "token_pkey",
	},
}

type tokenErrors struct {
	ErrUniqueTokenPkey *UniqueConstraintError
}
