// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserGroupErrors = &userGroupErrors{
	ErrUniqueUserGroupPkey: &UniqueConstraintError{
		schema:  "",
		table:   "user_group",
		columns: []string{"group_name"},
		s:       "user_group_pkey",
	},
}

type userGroupErrors struct {
	ErrUniqueUserGroupPkey *UniqueConstraintError
}
