// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var CasbinRulesV1S = Table[
	casbinRulesV1Columns,
	casbinRulesV1Indexes,
	casbinRulesV1ForeignKeys,
	casbinRulesV1Uniques,
	casbinRulesV1Checks,
]{
	Schema: "",
	Name:   "casbin_rules_v1",
	Columns: casbinRulesV1Columns{
		PType: column{
			Name:      "p_type",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		V0: column{
			Name:      "v0",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		V1: column{
			Name:      "v1",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		V2: column{
			Name:      "v2",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		V3: column{
			Name:      "v3",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		V4: column{
			Name:      "v4",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		V5: column{
			Name:      "v5",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: casbinRulesV1Indexes{
		IdxCasbinRulesV1: index{
			Type: "btree",
			Name: "idx_casbin_rules_v1",
			Columns: []indexColumn{
				{
					Name:         "p_type",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "v0",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "v1",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},

	Comment: "",
}

type casbinRulesV1Columns struct {
	PType column
	V0    column
	V1    column
	V2    column
	V3    column
	V4    column
	V5    column
}

func (c casbinRulesV1Columns) AsSlice() []column {
	return []column{
		c.PType, c.V0, c.V1, c.V2, c.V3, c.V4, c.V5,
	}
}

type casbinRulesV1Indexes struct {
	IdxCasbinRulesV1 index
}

func (i casbinRulesV1Indexes) AsSlice() []index {
	return []index{
		i.IdxCasbinRulesV1,
	}
}

type casbinRulesV1ForeignKeys struct{}

func (f casbinRulesV1ForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type casbinRulesV1Uniques struct{}

func (u casbinRulesV1Uniques) AsSlice() []constraint {
	return []constraint{}
}

type casbinRulesV1Checks struct{}

func (c casbinRulesV1Checks) AsSlice() []check {
	return []check{}
}
