// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Mailings = Table[
	mailingColumns,
	mailingIndexes,
	mailingForeignKeys,
	mailingUniques,
	mailingChecks,
]{
	Schema: "",
	Name:   "mailing",
	Columns: mailingColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('mailing_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TemplateID: column{
			Name:      "template_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ListID: column{
			Name:      "list_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DomainID: column{
			Name:      "domain_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "character varying",
			Default:   "'draft'::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SubjectSnapshot: column{
			Name:      "subject_snapshot",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		BodySnapshot: column{
			Name:      "body_snapshot",
			DBType:    "text",
			Default:   "''::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PostmarkBulkRequestID: column{
			Name:      "postmark_bulk_request_id",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PostmarkStatus: column{
			Name:      "postmark_status",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PostmarkSubmittedAt: column{
			Name:      "postmark_submitted_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		PostmarkTotalMessages: column{
			Name:      "postmark_total_messages",
			DBType:    "integer",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PostmarkPercentageCompleted: column{
			Name:      "postmark_percentage_completed",
			DBType:    "double precision",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartedAt: column{
			Name:      "started_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		FinishedAt: column{
			Name:      "finished_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedByUserID: column{
			Name:      "created_by_user_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedByUserID: column{
			Name:      "updated_by_user_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Archived: column{
			Name:      "archived",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: mailingIndexes{
		MailingPkey: index{
			Type: "btree",
			Name: "mailing_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailingIxDomain: index{
			Type: "btree",
			Name: "mailing_ix_domain",
			Columns: []indexColumn{
				{
					Name:         "domain_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailingIxList: index{
			Type: "btree",
			Name: "mailing_ix_list",
			Columns: []indexColumn{
				{
					Name:         "list_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailingIxStatus: index{
			Type: "btree",
			Name: "mailing_ix_status",
			Columns: []indexColumn{
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailingIxTemplate: index{
			Type: "btree",
			Name: "mailing_ix_template",
			Columns: []indexColumn{
				{
					Name:         "template_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "mailing_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: mailingForeignKeys{
		MailingMailingCreatedByUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "mailing.mailing_created_by_user_id_fkey",
				Columns: []string{"created_by_user_id"},
				Comment: "",
			},
			ForeignTable:   "user_profile",
			ForeignColumns: []string{"id"},
		},
		MailingMailingDomainIDFkey: foreignKey{
			constraint: constraint{
				Name:    "mailing.mailing_domain_id_fkey",
				Columns: []string{"domain_id"},
				Comment: "",
			},
			ForeignTable:   "mail_domain",
			ForeignColumns: []string{"id"},
		},
		MailingMailingListIDFkey: foreignKey{
			constraint: constraint{
				Name:    "mailing.mailing_list_id_fkey",
				Columns: []string{"list_id"},
				Comment: "",
			},
			ForeignTable:   "mail_list",
			ForeignColumns: []string{"id"},
		},
		MailingMailingTemplateIDFkey: foreignKey{
			constraint: constraint{
				Name:    "mailing.mailing_template_id_fkey",
				Columns: []string{"template_id"},
				Comment: "",
			},
			ForeignTable:   "mail_template",
			ForeignColumns: []string{"id"},
		},
		MailingMailingUpdatedByUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "mailing.mailing_updated_by_user_id_fkey",
				Columns: []string{"updated_by_user_id"},
				Comment: "",
			},
			ForeignTable:   "user_profile",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type mailingColumns struct {
	ID                          column
	Name                        column
	TemplateID                  column
	ListID                      column
	DomainID                    column
	Status                      column
	SubjectSnapshot             column
	BodySnapshot                column
	PostmarkBulkRequestID       column
	PostmarkStatus              column
	PostmarkSubmittedAt         column
	PostmarkTotalMessages       column
	PostmarkPercentageCompleted column
	StartedAt                   column
	FinishedAt                  column
	CreatedByUserID             column
	UpdatedByUserID             column
	CreatedAt                   column
	UpdatedAt                   column
	Archived                    column
}

func (c mailingColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.TemplateID, c.ListID, c.DomainID, c.Status, c.SubjectSnapshot, c.BodySnapshot, c.PostmarkBulkRequestID, c.PostmarkStatus, c.PostmarkSubmittedAt, c.PostmarkTotalMessages, c.PostmarkPercentageCompleted, c.StartedAt, c.FinishedAt, c.CreatedByUserID, c.UpdatedByUserID, c.CreatedAt, c.UpdatedAt, c.Archived,
	}
}

type mailingIndexes struct {
	MailingPkey       index
	MailingIxDomain   index
	MailingIxList     index
	MailingIxStatus   index
	MailingIxTemplate index
}

func (i mailingIndexes) AsSlice() []index {
	return []index{
		i.MailingPkey, i.MailingIxDomain, i.MailingIxList, i.MailingIxStatus, i.MailingIxTemplate,
	}
}

type mailingForeignKeys struct {
	MailingMailingCreatedByUserIDFkey foreignKey
	MailingMailingDomainIDFkey        foreignKey
	MailingMailingListIDFkey          foreignKey
	MailingMailingTemplateIDFkey      foreignKey
	MailingMailingUpdatedByUserIDFkey foreignKey
}

func (f mailingForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.MailingMailingCreatedByUserIDFkey, f.MailingMailingDomainIDFkey, f.MailingMailingListIDFkey, f.MailingMailingTemplateIDFkey, f.MailingMailingUpdatedByUserIDFkey,
	}
}

type mailingUniques struct{}

func (u mailingUniques) AsSlice() []constraint {
	return []constraint{}
}

type mailingChecks struct{}

func (c mailingChecks) AsSlice() []check {
	return []check{}
}
