// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var MailLists = Table[
	mailListColumns,
	mailListIndexes,
	mailListForeignKeys,
	mailListUniques,
	mailListChecks,
]{
	Schema: "",
	Name:   "mail_list",
	Columns: mailListColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('mail_list_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedByUserID: column{
			Name:      "created_by_user_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedByUserID: column{
			Name:      "updated_by_user_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: mailListIndexes{
		MailListPkey: index{
			Type: "btree",
			Name: "mail_list_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailListIxName: index{
			Type: "btree",
			Name: "mail_list_ix_name",
			Columns: []indexColumn{
				{
					Name:         "lower(name::text)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "mail_list_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: mailListForeignKeys{
		MailListMailListCreatedByUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "mail_list.mail_list_created_by_user_id_fkey",
				Columns: []string{"created_by_user_id"},
				Comment: "",
			},
			ForeignTable:   "user_profile",
			ForeignColumns: []string{"id"},
		},
		MailListMailListUpdatedByUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "mail_list.mail_list_updated_by_user_id_fkey",
				Columns: []string{"updated_by_user_id"},
				Comment: "",
			},
			ForeignTable:   "user_profile",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type mailListColumns struct {
	ID              column
	Name            column
	Description     column
	CreatedByUserID column
	UpdatedByUserID column
	CreatedAt       column
	UpdatedAt       column
}

func (c mailListColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Description, c.CreatedByUserID, c.UpdatedByUserID, c.CreatedAt, c.UpdatedAt,
	}
}

type mailListIndexes struct {
	MailListPkey   index
	MailListIxName index
}

func (i mailListIndexes) AsSlice() []index {
	return []index{
		i.MailListPkey, i.MailListIxName,
	}
}

type mailListForeignKeys struct {
	MailListMailListCreatedByUserIDFkey foreignKey
	MailListMailListUpdatedByUserIDFkey foreignKey
}

func (f mailListForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.MailListMailListCreatedByUserIDFkey, f.MailListMailListUpdatedByUserIDFkey,
	}
}

type mailListUniques struct{}

func (u mailListUniques) AsSlice() []constraint {
	return []constraint{}
}

type mailListChecks struct{}

func (c mailListChecks) AsSlice() []check {
	return []check{}
}
