// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var MailBlacklists = Table[
	mailBlacklistColumns,
	mailBlacklistIndexes,
	mailBlacklistForeignKeys,
	mailBlacklistUniques,
	mailBlacklistChecks,
]{
	Schema: "",
	Name:   "mail_blacklist",
	Columns: mailBlacklistColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('mail_blacklist_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Reason: column{
			Name:      "reason",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Origin: column{
			Name:      "origin",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Stream: column{
			Name:      "stream",
			DBType:    "character varying",
			Default:   "''::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Source: column{
			Name:      "source",
			DBType:    "character varying",
			Default:   "'postmark'::character varying",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: mailBlacklistIndexes{
		MailBlacklistPkey: index{
			Type: "btree",
			Name: "mail_blacklist_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailBlacklistIxEmail: index{
			Type: "btree",
			Name: "mail_blacklist_ix_email",
			Columns: []indexColumn{
				{
					Name:         "lower(email::text)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailBlacklistIxReason: index{
			Type: "btree",
			Name: "mail_blacklist_ix_reason",
			Columns: []indexColumn{
				{
					Name:         "reason",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		MailBlacklistIxSource: index{
			Type: "btree",
			Name: "mail_blacklist_ix_source",
			Columns: []indexColumn{
				{
					Name:         "source",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "mail_blacklist_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type mailBlacklistColumns struct {
	ID        column
	Email     column
	Reason    column
	Origin    column
	Stream    column
	Source    column
	CreatedAt column
	UpdatedAt column
}

func (c mailBlacklistColumns) AsSlice() []column {
	return []column{
		c.ID, c.Email, c.Reason, c.Origin, c.Stream, c.Source, c.CreatedAt, c.UpdatedAt,
	}
}

type mailBlacklistIndexes struct {
	MailBlacklistPkey     index
	MailBlacklistIxEmail  index
	MailBlacklistIxReason index
	MailBlacklistIxSource index
}

func (i mailBlacklistIndexes) AsSlice() []index {
	return []index{
		i.MailBlacklistPkey, i.MailBlacklistIxEmail, i.MailBlacklistIxReason, i.MailBlacklistIxSource,
	}
}

type mailBlacklistForeignKeys struct{}

func (f mailBlacklistForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type mailBlacklistUniques struct{}

func (u mailBlacklistUniques) AsSlice() []constraint {
	return []constraint{}
}

type mailBlacklistChecks struct{}

func (c mailBlacklistChecks) AsSlice() []check {
	return []check{}
}
