// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var UserGroups = Table[
	userGroupColumns,
	userGroupIndexes,
	userGroupForeignKeys,
	userGroupUniques,
	userGroupChecks,
]{
	Schema: "",
	Name:   "user_group",
	Columns: userGroupColumns{
		GroupName: column{
			Name:      "group_name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CanBeDelete: column{
			Name:      "can_be_delete",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsAdmin: column{
			Name:      "is_admin",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ChangedByUserID: column{
			Name:      "changed_by_user_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userGroupIndexes{
		UserGroupPkey: index{
			Type: "btree",
			Name: "user_group_pkey",
			Columns: []indexColumn{
				{
					Name:         "group_name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "user_group_pkey",
		Columns: []string{"group_name"},
		Comment: "",
	},

	Comment: "",
}

type userGroupColumns struct {
	GroupName       column
	Description     column
	CanBeDelete     column
	IsAdmin         column
	ChangedByUserID column
	CreatedAt       column
	UpdatedAt       column
}

func (c userGroupColumns) AsSlice() []column {
	return []column{
		c.GroupName, c.Description, c.CanBeDelete, c.IsAdmin, c.ChangedByUserID, c.CreatedAt, c.UpdatedAt,
	}
}

type userGroupIndexes struct {
	UserGroupPkey index
}

func (i userGroupIndexes) AsSlice() []index {
	return []index{
		i.UserGroupPkey,
	}
}

type userGroupForeignKeys struct{}

func (f userGroupForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userGroupUniques struct{}

func (u userGroupUniques) AsSlice() []constraint {
	return []constraint{}
}

type userGroupChecks struct{}

func (c userGroupChecks) AsSlice() []check {
	return []check{}
}
