// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var UserProfiles = Table[
	userProfileColumns,
	userProfileIndexes,
	userProfileForeignKeys,
	userProfileUniques,
	userProfileChecks,
]{
	Schema: "",
	Name:   "user_profile",
	Columns: userProfileColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('user_profile_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Salutation: column{
			Name:      "salutation",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Forename: column{
			Name:      "forename",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Lastname: column{
			Name:      "lastname",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Password: column{
			Name:      "password",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MustResetPassword: column{
			Name:      "must_reset_password",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastLogin: column{
			Name:      "last_login",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedByUserProfileID: column{
			Name:      "created_by_user_profile_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		LastUpdatedByUserID: column{
			Name:      "last_updated_by_user_id",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Disabled: column{
			Name:      "disabled",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EmailValidated: column{
			Name:      "email_validated",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userProfileIndexes{
		UserProfilePkey: index{
			Type: "btree",
			Name: "user_profile_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UserIxProfileEmail: index{
			Type: "btree",
			Name: "user_ix_profile_email",
			Columns: []indexColumn{
				{
					Name:         "lower(email::text)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UserIxProfileForename: index{
			Type: "btree",
			Name: "user_ix_profile_forename",
			Columns: []indexColumn{
				{
					Name:         "lower(forename::text)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UserIxProfileLastname: index{
			Type: "btree",
			Name: "user_ix_profile_lastname",
			Columns: []indexColumn{
				{
					Name:         "lower(lastname::text)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "user_profile_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type userProfileColumns struct {
	ID                     column
	Email                  column
	Salutation             column
	Forename               column
	Lastname               column
	Password               column
	MustResetPassword      column
	LastLogin              column
	CreatedByUserProfileID column
	LastUpdatedByUserID    column
	Disabled               column
	EmailValidated         column
	CreatedAt              column
	UpdatedAt              column
}

func (c userProfileColumns) AsSlice() []column {
	return []column{
		c.ID, c.Email, c.Salutation, c.Forename, c.Lastname, c.Password, c.MustResetPassword, c.LastLogin, c.CreatedByUserProfileID, c.LastUpdatedByUserID, c.Disabled, c.EmailValidated, c.CreatedAt, c.UpdatedAt,
	}
}

type userProfileIndexes struct {
	UserProfilePkey       index
	UserIxProfileEmail    index
	UserIxProfileForename index
	UserIxProfileLastname index
}

func (i userProfileIndexes) AsSlice() []index {
	return []index{
		i.UserProfilePkey, i.UserIxProfileEmail, i.UserIxProfileForename, i.UserIxProfileLastname,
	}
}

type userProfileForeignKeys struct{}

func (f userProfileForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userProfileUniques struct{}

func (u userProfileUniques) AsSlice() []constraint {
	return []constraint{}
}

type userProfileChecks struct{}

func (c userProfileChecks) AsSlice() []check {
	return []check{}
}
